### ISSUE TITLE
Include additional imagemounter option

### ISSUE THREAD

**Issue by ralphje** [teamdfir/sift#131]
I have been working on a utility to mount disk images for a few years, and only recently discovered that SIFT workstation also includes a similar script. It is even similarly named, though it does not originate from the same code base! I just released a new version that adds BDE support, making it feature-complete with imageMounter.py.

Its feature set is far more extensive than the current script included in SIFT workstation, including support for LVM, Linux RAID and other volume types. It can even mount ext volumes in gpt volume systems contained in an LVM contained in Linux RAID on a dos volume system, would you encounter something like that. It also has an extensive Python library that can be used to automate mounting volumes in scripts.

This issue may come across as some shameless self-promotion, but I know it is being used by several law enforcement agencies for some time now, and they are happy using it, so there's that :wink:. The repository can be found at https://github.com/ralphje/imagemounter

Obviously, I'm willing to work on updating the script further if you have some additions. Thank you for your consideration 😄

**Comment by PoorBillionaire** [comment]
As a daily User of SIFT, I like the idea of including Ralph's utility; however I think imageMounter.py should remain in the build as well.

**Comment by ekristen** [comment]
I'm not opposed to adding this to the next release. I'll take a look at it.

**Comment by ralphje** [comment]
In that case, @ekristen, have you had the time to look at it yet?

**Comment by ekristen** [comment]
Looks like this can be installed via pip, so this should be easy to add. Let me chat about it with a couple other people.

**Comment by ralphje** [comment]
@ekristen, have you had the time to chat with the other people about it yet?

**Comment by ekristen** [comment]
Everyone is ok with adding another tool but not replacing the existing tool.

**Comment by rj-chap** [comment]
Just found a solid use case to have Ralph's version.  Updating this Issue as a bump.  Thanks gang.
