### ISSUE TITLE
Special Proxy Config Requirements Should be Clearly Documented or Automated

### ISSUE THREAD

**Issue by johnmccash** [teamdfir/sift#236]
Hi,
Sorry for the apparently trivial bug, but I really did have to work at this for over a day (and I like to think I know enough that it shouldn't have been that big a deal), just to get the sift upgrade process to finally succeed from behind my proxy. It would be nice if some of these steps could be automated. The user should just have to set up the proxy in the System Settings/Network GUI. I did all of the following:

1. Downloaded the most recent SIFT .ova file, & imported into VMware Workstation
2. Set the proxy configuration in the System Settings/Network GUI
3. Manually added the following two additional lines to /etc/environment (The uppercase HTTP_PROXY & HTTPS_PROXY lines are critical, as some component apparently doesn't recognize the lowercase ones that are added by the GUI step above. I also note that the GUI forces the https proxy URL to itself be https, which doesn't work in my environment, but that's likely an Ubuntu issue.)
export HTTPS_PROXY=http://<my proxy host>:<port>
export HTTP_PROXY=http://<my proxy host>:<port>
4. set the following two lines into a newly created '/etc/salt/minion' file (Note: The space after the colon is REQUIRED):
proxy_host: <my proxy host>
proxy_port: <port>
5. sudo sift upgrade

After all this, the sift upgrade to the new 2018 version finally succeeded.

Thanks
John

**Comment by ekristen** [comment]
Thanks for the feedback. I agree, the proxy information can be documented better.

**Comment by johnmccash** [comment]
oops.. The post was supposed to have  more detail in it. I had included data in angle brackets, and those got stripped. Let's see if it works when I use the 'insert code' function in the comment tool...

```
3. Manually added the following two additional lines to /etc/environment (The uppercase HTTP_PROXY & HTTPS_PROXY lines are critical, as some component apparently doesn't recognize the lowercase ones that are added by the GUI step above. I also note that the GUI forces the https proxy URL to itself be https, which doesn't work in my environment, but that's likely an Ubuntu issue.)
export HTTPS_PROXY=http://<hostname>:<port number>
export HTTP_PROXY=http://<hostname>:<port number>
4. set the following two lines into a newly created '/etc/salt/minion' file (Note: The space after the colon is REQUIRED):
proxy_host: <hostname>
proxy_port: <port number>
```

**Comment by johnmccash** [comment]
I also neglected to mention the required reboot or services restart after making the changes, but before running 'sudo sift upgrade'.

**Comment by ekristen** [comment]
Please also note, that once https://github.com/teamdfir/sift-saltstack/pull/80 is merged, SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)

Proxy support is still missing from cast.
