### ISSUE TITLE
[SALTSTACK] Can't locate Perl modules

### ISSUE THREAD

**Issue by esecrpm** [teamdfir/sift#249]
I recently reviewed all .pl files in /usr/local/bin of the 2018.08.0 build and found the following would not run because a module could not be found.

docx-font-extractor.pl	XML/XPath.pm
exif2map.pl			HTML/QuickTable.pm
fb.pl					JSON.pm
ff.pl					DBI.pm
ff_signons.pl			DBI.pm
jl.pl					JumpList.pm
json-printer.pl			JSON.pm
lnk.pl				LNK.pm
pref.pl				Pref.pm
squirrelgripper.pl		DBI.pm, also requires ExifTool
timediff32.pl			Date/Calc.pm
tln.pl				Win32/GUI.pm
vmail-db-2-html.pl		DBI.pm

**Comment by ekristen** [comment]
@esecrpm thanks for the repo. I'll take a look.

**Comment by threeplanetssoftware** [comment]
I created PR #22 over on the saltstack repo to address this issue (https://github.com/teamdfir/sift-saltstack/pull/22). It uses the normal packaging systems (vice CPAN), but would add (DBI, JSON, Image::ExifTool, XML::XPath, and Date::Calc) to address the following tools:

- docx-font-extractor.pl XML/XPath.pm
- fb.pl JSON.pm
- ff.pl DBI.pm
- ff_signons.pl DBI.pm
- json-printer.pl JSON.pm
- squirrelgripper.pl DBI.pm, also requires ExifTool
- timediff32.pl Date/Calc.pm
- vmail-db-2-html.pl DBI.pm

A proper solution should pivot over to using CPAN, but this will at least get all of these tools working finally.

**Comment by threeplanetssoftware** [comment]
PR #23 over in SIFT-saltstack should add the rest of the modules that can be. Win32::GUI can't build on Linux, but that PR will add JumpList.pm, LNK.pm, Pref.pm, and HTML/QuickTable.pm. A more elegant solution would still use CPAN, but this should allow the ticket to be closed, assuming additional testing confirms this works.

**Comment by ekristen** [comment]
Issue Cleanup -- I believe this is now all resolved.
