### ISSUE TITLE
APFS Support

### ISSUE THREAD

**Issue by mac4n6** [teamdfir/sift#259]
Please add https://github.com/sgan81/apfs-fuse thanks!

**Comment by ekristen** [comment]
@mac4n6 I've opened a ticket https://github.com/sgan81/apfs-fuse/issues/26 asking for this to get built for distribution by the author, it'll go a long way in helping to make sure we can get it installed.

Ideally we don't want to have to build and manage it ourselves as it will most likely fall out of date quickly.

**Comment by joachimmetz** [comment]
In case you are looking for an alternative the GIFT PPA provides libfsapfs-tools which contains fsapfsmount.

**Comment by ekristen** [comment]
@mac4n6 would this option from @joachimmetz work?
