### ISSUE TITLE
sift v2018.08.0 doesn't install Python PIL imaging library, required by volatility screenshot plugin

### ISSUE THREAD

**Issue by johnmccash** [teamdfir/sift#261]
I just went to run the 'screenshot' volatility plugin under sift v2018.08.0, and discovered that the Python PIL imaging library (a required prerequisite) wasn't installed. I was able to get around the problem by doing 'apt-get install python-imaging'.

**Comment by esecrpm** [comment]
Confirmed, I am getting the same error in latest SIFT on top of clean Ubuntu install.
sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0


vol.py -f PhysicalMemory --profile=Win7SP1x64 screenshot
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Please install PIL

**Comment by aktas** [comment]
```pip2.7 install Pillow``` I solved my problem with this command.
