### ISSUE TITLE
[CLI] Can't Locate Perl Modules

### ISSUE THREAD

**Issue by esecrpm** [teamdfir/sift#263]
Hi Erik,

I have just installed the latest sift on a clean ubuntu install with 0 (zero) failures.  The following perl scripts indicate a module can't be loaded. I have included the sift version and salt-call version info below.  Please let me know if you need the saltstack.log or any other information.

Thanks,
Erik

docx-font-extractor.pl   XML/XPath.pm
exif2map.pl   HTML/QuickTable.pm
fb.pl   JSON.pm
ff.pl   DBI.pm
ff_signons.pl   DBI.pm
jl.pl   JumpList.pm
json-printer.pl   JSON.pm
lnk.pl   LNK.pm
pref.pl   Pref.pm
sqlite_miner.pl   DBI.pm
squirrelgripper.pl   DBI.pm, also requires ExifTool
timediff32.pl   Date/Calc.pm
tln.pl   Win32/GUI.pm
vmail-db-2-html.pl   DBI.pm

sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0

salt-call --versions
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-39-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Fetchered** [comment]
Bump.
JumpList and LNK will not install separately, and pref.pl (which requires Pref.pm, but only pref.pm exists in perl namespace) does not work with installed perl module.
Also, Win32::GUI is not supported on linux environments.
These modules still are not available with SIFT CLI 1.7.1 and SaltStack v2018.35.0

**Comment by ekristen** [comment]
Thanks for bringing this back to my attention, what would be helpful is the commands you are attempting to run and ideally if you can profile any input artifacts and resulting output in a zip file that'd be really appreciated.

We are in the process of writing tests for all tools so that we can hopefully know when tools are not working properly from a CI/CD process.

**Comment by threeplanetssoftware** [comment]
I created PR #22 over on the saltstack repo to address the Perl aspects of this issue (https://github.com/teamdfir/sift-saltstack/pull/22). It uses the normal packaging systems (vice CPAN), but would add (DBI, JSON, Image::ExifTool, XML::XPath, and Date::Calc) to address the following tools:

- docx-font-extractor.pl XML/XPath.pm
- fb.pl JSON.pm
- ff.pl DBI.pm
- ff_signons.pl DBI.pm
- json-printer.pl JSON.pm
- squirrelgripper.pl DBI.pm, also requires ExifTool
- timediff32.pl Date/Calc.pm
- vmail-db-2-html.pl DBI.pm

A proper solution should pivot over to using CPAN, but this will at least get all of these tools working finally.

**Comment by ekristen** [comment]
Thanks @threeplanetssoftware for the help so far. I'm ok using apt packages as long as there is consistency. Happy to have it converted to CPAN too.

**Comment by threeplanetssoftware** [comment]
Happy to help!

PR #23 over in SIFT-saltstack should add the rest of the modules that can be. Win32::GUI can't build on Linux, but that PR will add JumpList.pm, LNK.pm, Pref.pm, and HTML/QuickTable.pm. A more elegant solution would still use CPAN, but this should allow the ticket to be closed, assuming additional testing confirms this works.

**Comment by ekristen** [comment]
I believe this is now resolved.
