### ISSUE TITLE
[CLI] Missing Exiftool, INDXParse, shellbags

### ISSUE THREAD

**Issue by esecrpm** [teamdfir/sift#264]
Hi Erik,

I have just installed the latest sift on a clean ubuntu install with 0 (zero) failures. The following tools cannot be found in the /usr/bin or /usr/local/bin directories. I was able to locate the sls file for all three.  I have included the sift version and salt-call version info below. Please let me know if you need the saltstack.log or any other information.

Thanks,
Erik

exiftool
/var/cache/sift/cli/v2018.16.0/sift-saltstack-2018.16.0/sift/scripts/exiftool.sls

INDXparse.py
/var/cache/sift/cli/v2018.16.0/sift-saltstack-2018.16.0/sift/python-packages/indxparse.sls

shellbags.py
/var/cache/sift/cli/v2018.16.0/sift-saltstack-2018.16.0/sift/python-packages/shellbags.sls

sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0

salt-call --versions
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-39-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by ekristen** [comment]
Issue Clean -- this has been resolved.
