### ISSUE TITLE
pstotal volatility plugin doesn't work in v2018.16.0

### ISSUE THREAD

**Issue by johnmccash** [teamdfir/sift#269]
I'm getting the following error when attempting to use the pstotal volatility plugin in v2018.16.0:

$ vol.py -f x --profile=Win7SP1x64 pstotal
Volatility Foundation Volatility Framework 2.6
Offset (P)     Name          PID    PPID   PDB        Time created             Time exited             Interesting 
---------- ---------------- ------ ------ ---------- ------------------------ ------------------------ ----------- 
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/sift/pstotal.py", line 62, in render_text
    if interest[processes[eprocess].obj_offset] == 1:
NameError: global name 'eprocess' is not defined

This looks to me like an error that was fixed a while back...

**Comment by ekristen** [comment]
Looks like we need to update our fork of the plugins. It's really hard to make sure we stay on top of this because the community plugins conflict with each other.

**Comment by TheMuttster** [comment]
I fixed the issue with this locally. Commit 27dcac6018ef8a660bdb1af61f9cb4b246321ea4 introduced the error which removed the immediately preceding line from the error:

`        for eprocess in processes:`

I also noticed some text misaligning so I replaced lines 56-73 with,

`   def render_text(self, outfd, data):`
`        processes = data[0]`
`        interest = data[1]`
`        outfd.write("Offset (P)        Name        PID    PPID      PDB             Time created                 Time exited          Interesting \n" + \`
`                    "----------- ---------------- ------ ------ ----------- ---------------------------- ---------------------------- ----------- \n”)`
`                for eprocess in processes:`
`                    if interest[processes[eprocess].obj_offset] == 1:`
`                interesting = 'TRUE’`
`            else:`
`                interesting = ' ‘`
`            outfd.write("0x{0:09x} {1:16} {2:6} {3:6} 0x{4:09x} {5:28} {6:28} {7:7}\n".format(`
`                    processes[eprocess].obj_offset,`
`                    processes[eprocess].ImageFileName,`
`                    processes[eprocess].UniqueProcessId,`
`                    processes[eprocess].InheritedFromUniqueProcessId,`
`                    processes[eprocess].Pcb.DirectoryTableBase,`
`                    processes[eprocess].CreateTime or ‘’,`
`                    processes[eprocess].ExitTime or '', interesting))`

**Comment by CrustyBarnacle** [comment]
Fix as documented in previous comment still works, but still has to be manually applied? Did this break again, or ??

        for eprocess in processes:
            if interest[processes[eprocess].obj_offset] == 1:
                interesting = 'TRUE'
            else:
                interesting = ' '
            outfd.write("0x{0:08x} {1:16} {2:6} {3:6} 0x{4:08x} {5:24} {6:24} {7:7}\n".format(
                    processes[eprocess].obj_offset,
                    processes[eprocess].ImageFileName,
                    processes[eprocess].UniqueProcessId,
                    processes[eprocess].InheritedFromUniqueProcessId,
                    processes[eprocess].Pcb.DirectoryTableBase,
                    processes[eprocess].CreateTime or '',
                    processes[eprocess].ExitTime or '', interesting))

**Comment by digitalsleuth** [comment]
@johnmccash and @CrustyBarnacle , the pstotal plugin has been fixed using the recommendations from @Pitteuchar. Do you still require this issue to remain open?

**Comment by ekristen** [comment]
Thanks @digitalsleuth.

@johnmccash @CrustyBarnacle if you still experience issues please feel free to re-open.
