### ISSUE TITLE
Is there a download for SIFT workstation ova that is compatible with ESXi 6.0?  

### ISSUE THREAD

**Issue by ghost** [teamdfir/sift#279]
The hardware family type would be vmx-11.  The current ova here: https://digital-forensics.sans.org/community/downloads is vmx-12.

**Comment by icepaule** [comment]
Hi patulskitime,

unfortunatly, your link end's up in a 404.  :-/
Is there any alternative known?

Thanks so much.

Marcus

**Comment by patulskitime** [comment]
Hi icepaule,

Link still works for me, but here are steps from the DIRS SANS home page (https://digital-forensics.sans.org/) Community (tab) >> SIFT Workstation (drop down option) >> page with SIFT ova download link.

**Comment by ekristen** [comment]
There's a new OVA being uploaded soon, I'm unsure about it's compatibility level at the moment.

**Comment by icepaule** [comment]
Hi @ekristen,

looking forward the new version. compatibility will be no issue as starting from scratch anyway.

Thx a lot
Marcus

**Comment by muchar** [comment]
It's been some time and still a 404 trying to download the workstation...

**Comment by ekristen** [comment]
@muchar downloads work just fine for me. You can also use the instructions on GitHub to build your own. As for ESXi 6 compatibility, I'm unsure. THe focus is on VMWare Workstation compatibility.
