### ISSUE TITLE
[SOLVED] [WORKAROUND] log2timeline cannot output plaso file due to dependencies failure

### ISSUE THREAD

**Issue by ljw001** [teamdfir/sift#283]
Hi,

i receive the following errors while creating a super timeline using log2timeline. This is a fresh import of ova appliance (SIFT workstation v3.0) Please advice on resolution.
Thank you

log2timeline.py /tmp/output /cases/nps-jeans/nps-2008-jean.E01
Checking availability and versions of dependencies.
[FAILURE]	elasticsearch version: 6.2.0 is too recent, 5.5.1 or earlier required.

Regards
Jun Wei

**Comment by ljw001** [comment]
I shall wait for the fix.  I have installed 5 but had a hard time figuring out how to link the python scripts together.

**Comment by mark-hallman** [comment]
Jun Wei,

I have experienced the same issue.  Try this as a work around.  The Plaso team has acknowledged this issue and are working on a fix.  They gave me the work around.  

If this command works for you,  you should be all set.  Just include it as the 1st parameter on all your Plaso commands (log2timeline, psort, image_info, etc.).

-Mark

`log2timeline.py --no-dependencies-check -V`

**Comment by ljw001** [comment]
Hi Mark,

Thanks. The workaround did work! 

Regards
Jun Wei

**Comment by joachimmetz** [comment]
FYI Providing a work-around is not a fix

**Comment by chadmreams** [comment]
I would be interested in the fix vs. the workaround as well. I installed elasticsearch v5.5.1 but still received the dependency error. When providing the '--no-dependencies-check' switch it kicks off processing, but I'm not sure if this impacts log2timeline functionality. Thanks in advance!

**Comment by joachimmetz** [comment]
> I would be interested in the fix vs. the workaround as well.

The `--no-dependencies-check` is there to skip the dependency check. But this check is there for a reason, given that some dependencies are only needed to support specific data format. Unless you know for sure that you are not going to use the format that a missing dependency provides, it is risky to use this flag.

A **fix** would be to install the missing dependency or if a potential bug in plaso file an issue with the plaso project.

Plaso added support for both elasticsearch5-py and elasticsearch-py in the end: https://github.com/log2timeline/plaso/commit/00ef17c545041f711a4403a47ab2c39ac31a1445. So this should no longer be an issue.
