### ISSUE TITLE
[CLI] Built in upgrade feature?

### ISSUE THREAD

**Issue by zappeee** [teamdfir/sift#298]
Would be great if the CLI was updated during "sift upgrade" also.
Or just a hint that you are using an old CLI.

**Comment by ekristen** [comment]
I agree, I'd like to add a version check in and a self-update feature that's outside of upgrade. I want the CLI to standalone, it's a helper tool that I'd prefer to not be reliant on the saltstack process to be updated.

**Comment by jackdyson1399** [comment]
Is there a way to identify if there is a new version of sift-cli available via terminal?
Like for new SIFT releases there is the 'sift list-upgrades' command, I was wondering if there was something for sift-cli as I just by chance noticed you released a new version recently.

**Comment by ekristen** [comment]
There is no feature built in at this time. Looking at this projects releases is about the only way. I'm looking into adding a new feature for it though, but have no ETA.

**Comment by jackdyson1399** [comment]
No worries. Just wanted to check. It's easy enough scripting to open the releases url.

**Comment by ekristen** [comment]
Please also note, that once https://github.com/teamdfir/sift-saltstack/pull/80 is merged, SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)

This feature is being looked at for [cast](https://github.com/ekristen/cast)
