### ISSUE TITLE
mactime - DateTime module not loaded

### ISSUE THREAD

**Issue by glocker1** [teamdfir/sift#323]
mactime -z list 

returns:
DateTime module not loaded -- cannot list timezones

mactime -V
version 4.2.0

I have the latest sift installed.

**Comment by ekristen** [comment]
pip install datetime

**Comment by glocker1** [comment]
The pip install worked, but it didn't fix the issue.

mactime is complaining about a module named DateTime with cap D and cap T.
The datetime module installed via the pip command appears to have functions
name with all small letters.

**Comment by ekristen** [comment]
try `sudo apt-get install libdatetime-perl`

**Comment by glocker1** [comment]
That worked.  Thanks.

**Comment by ekristen** [comment]
Looks like `libdatetime-perl` is missing from the installation process, will get that added.
