### ISSUE TITLE
Add libguestfs tools to SIFT

### ISSUE THREAD

**Issue by mpilking** [teamdfir/sift#327]
libguestfs tools support mounting various types of virtual hard drive types.  Specifically, it works well with Microsoft's VHD and VHDX formats.  We need this to mount VHDX files from EZ's kape triage image tool.

Installation in the current SIFT is simple via apt:  apt-get install libguestfs-tools

More info: http://libguestfs.org/

**Comment by ekristen** [comment]
Bump to remove stale. I’ve got this part way in

**Comment by ekristen** [comment]
This has been added.
