### ISSUE TITLE
End of Life Support for 16.04

### ISSUE THREAD

**Issue by ekristen** [teamdfir/sift#349]
This is purely a placeholder for further discussion and tracking of ending support for 16.04 for the SIFT Workstation.

## Requirements
* [ ] - SANS Class USBs must be on Bionic for 6-12 months

**Comment by joachimmetz** [comment]
Ubuntu 16.04 is now end of life https://wiki.ubuntu.com/Releases

**Comment by ekristen** [comment]
16.04 is essentially no longer supported. 18.04 is the default VM now, and 20.04 is being built as we speak. Unsure on the ETA for 20.04 but it is ASAP. I'm working on it almost every day. Lots of work due to py2 being deprecated as well.
