### ISSUE TITLE
cannot import the PGP key - key 22598A94 can't be retrieved

### ISSUE THREAD

**Issue by nydman** [teamdfir/sift#352]
When I try to import the PGP key I get the below error:
gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94
gpg: requesting key 22598A94 from hkp server pgp.mit.edu
gpgkeys: key 22598A94 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm

**Comment by vincecertoma** [comment]
This worked for me.

`gpg --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 22598A94`

Thanks to @SaintHeimFyrstr (https://github.com/sans-dfir/sift/issues/326).

**Comment by ekristen** [comment]
@nydman @vincecertoma I've been doing a bit of research without much luck, but I have found some references to possible differences when it comes to IPv4 vs IPv6 networks.

What type of network are you on?

**Comment by vincecertoma** [comment]
@ekristen I am on an IPv4 network.

**Comment by VernMcC** [comment]
I was having a similar problem with doing this on WSL, when VMs built on the same host would work fine.  Some research revealed that there is a pool of pgp key servers that the mit server is a part of, and by using that to get the key solved the problem.
`gpg --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 22598A94`
The pool includes the mit pgp server, as well as others, so if there are problems with a server or the connection with one, another will have a chance to provide an answer.  This solved my error problem on the WSL builds.
