### ISSUE TITLE
Check if SIFT PPA sleuthkit overrides GIFT PPA and potentially causes issues

### ISSUE THREAD

**Issue by joachimmetz** [teamdfir/sift#358]
@ekristen heads up, I've promoted sleuthkit as part of GIFT PPA stable track.

As requested several times before, please set up automated tests to catch issues, before they are promoted to stable. (package was added to dev track on 2019-03-17)

Due to the lack of such tests, I'm letting you know via this issue.

A simple work-around is to bump the build number on `4.6.5-1sift5~xenial`

**Comment by ekristen** [comment]
Published newer version based off of the GIFT one with the extra libraries enabled. Thanks.
