### ISSUE TITLE
sift install triggered antivirus alerts

### ISSUE THREAD

**Issue by chokupittu** [teamdfir/sift#359]
Antivirus Triggered while installing sift on new install of Security Onion virtual machine ( checksum valid)

sudo sift install

Virus/Worm detected: Linux/Agent.A!tr Protocol: "HTTP" vn=Linux%2FAgent.A%21tr
date=2019-04-02 time=15:49:25 subtype="virus" eventtype="infected" level="warning" msg="File is infected." action="blocked" service="HTTP"   dstip=91.189.91.23 srcport=59858 dstport=80 dstintfrole="wan"  direction="incoming" filename="ettercap-common_0.8.2-2ubuntu1.16.04.1_amd64.deb" quarskip="File-was-not-quarantined." virus="Linux/Agent.A!tr" dtype="Virus" url="http://au.archive.ubuntu.com/ubuntu/pool/universe/e/ettercap/ettercap-common_0.8.2-2ubuntu1.16.04.1_amd64.deb" profile="AVS" agent="Debian" analyticscksum="734899d1f29faf0d7c093a42b71b365762e9ee2c85a6a039cf8d99353fe570e7" analyticssubmit="false"

**Comment by ekristen** [comment]
That's a package outside of our control. Most likely the AV is warning against tools that can be used for bad.
