### ISSUE TITLE
[SALTSTACK] - libxslt-dev causing issues (installation fails for some packages)

### ISSUE THREAD

**Issue by ericzinnikas** [teamdfir/sift#362]
Just used salt to install the SIFT packages only (`sift.pkgs`) and the installation succeeded except for 9 packages. It all traced back to salt thinking `libxslt-dev` was not being installed. Checking with apt, it turns out it was installed (but provided by `libxslt1-dev`). After going through the salt files and replacing every reference of `libxslt-dev` with `libxslt1-dev` (and moving 1 file) and re-running `sudo salt-call -l info --local --file-root=/tmp/salt state.apply sift.pkgs` everything now completes successfully:

```
Summary for local
--------------
Succeeded: 285 (changed=4)
Failed:      0
--------------
Total states run:     285
```

**Comment by ekristen** [comment]
What OS version?

**Comment by ericzinnikas** [comment]
Sorry, forgot to include:
```
$ cat  /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

**Comment by ekristen** [comment]
Interesting. Nothing on my end has changed about this. Let me dig into it.

**Comment by ericzinnikas** [comment]
Just did some searching and seems it is due to the [virtual package](https://packages.ubuntu.com/xenial/libxslt-dev).

https://github.com/saltstack/salt/issues/47092

> After discussing the matter internally, we have decided to drop "virtual package" support

**Comment by ekristen** [comment]
We aren't using that version of saltstack. Plus the libxslt1-dev is in the apt repo. 

I appreciate the PR and might still use it but I need to do some more due diligence first.

Can you provide 

`apt-cache showpkg libxslt1-dev` and `apt-cache showpkg libxslt-dev` and `apt-cache policy`

**Comment by ericzinnikas** [comment]
So, since I followed the `Installing Saltstack` instructions from the sift-saltstack page (i.e. it says, run `sudo apt-get install salt-minion`) I've just got the latest version. So, seems it might not apply to `sift-cli` usage, but would apply to direct usage of salt configs.

```
$ salt-minion -V
Salt Version:
           Salt: 2019.2.0
```

Output you asked for: https://gist.github.com/ericzinnikas/66d6c304b8558973466decdb0b179fbf
Had to sanitize some internal domains, but I don't think that will affect anything.

**Comment by ekristen** [comment]
So libxslt1-dev does exist for you, so that should work just fine. 

I didn't realize you were using saltstack on it's own, but I'm not sure this virtual package thing is the culprit yet.

libxslt1-dev installs just fine in my testing and on a fresh 16.04 instance.

**Comment by ericzinnikas** [comment]
It exists, but it is a virtual package, so salt cannot handle it. If I revert my changes and use the repo:

```
/tmp# git clone https://github.com/teamdfir/sift-saltstack.git
Cloning into 'sift-saltstack'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 2417 (delta 8), reused 27 (delta 7), pack-reused 2386
Receiving objects: 100% (2417/2417), 12.01 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1113/1113), done.
Checking connectivity... done.
/tmp# sudo salt-call -l info --local --file-root=/tmp/sift-saltstack state.apply sift.pkgs >> salt.out
```

It fails:
```
          ID: libxslt-dev
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: libxslt-dev
```
https://gist.github.com/ericzinnikas/d723a6a8425669a4b26c1c1ac4725d62

It is definitely installed/available, and apt can handle it fine:
```
$ sudo apt install libxslt-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libxslt1-dev is already the newest version (1.1.28-2.1ubuntu0.1).
The following packages were automatically installed and are no longer required:
  auth-client-config ldap-auth-config libsodium18 libzmq5 python-cffi-backend python-cryptography python-enum34 python-ipaddress python-pyasn1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Comment by ekristen** [comment]
Fair enough. I need to go through and make sure nothing else is actually depending on it first and run it through a battery of tests I have. 

Thank you for running this down, it's greatly appreciated!

**Comment by ekristen** [comment]
This has been resolved.
