### ISSUE TITLE
Regripper 

### ISSUE THREAD

**Issue by MMULLINIX1** [teamdfir/sift#367]
I had a Regripper script failure when I built a new SIFT Workstation this morning.
 ID: sift-scripts-regripper-git
        SLS: sift.scripts.regripper
        Run#: 398
        Comment: error: Your local changes to the following files would be overwritten by merge:
	plugins/sam
Please, commit your changes or stash them before you can merge.
Aborting

Changes already made: https://github.com/keydet89/RegRipper2.8.git was fetched, resulting in updated refs. Local changes were discarded.
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 399
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 400
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 401
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git, sift.scripts.regripper.sift-scripts-regripper-directory
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 402
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-binary
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 403
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 404
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 405
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 406
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 407
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git

**Comment by ekristen** [comment]
@MMULLINIX1 looks like there were local changes? Did you by chance make any changes to the regripper plugins?

**Comment by ekristen** [comment]
I cannot reproduce, if you still have the issues, please re-open.
