### ISSUE TITLE
[CLI] New Issues Installing SIFT within Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by guardian703** [teamdfir/sift#368]
I was trying to install SIFT after updating the default Ubuntu 16.04 LTS and received the followign errors:

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: colorama
        SLS: sift.python-packages.colorama
        Run#: 175
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: construct
        SLS: sift.python-packages.construct
        Run#: 176
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: dpapick
        SLS: sift.python-packages.dpapick
        Run#: 177
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: distorm3
        SLS: sift.python-packages.distorm3
        Run#: 178
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: haystack
        SLS: sift.python-packages.haystack
        Run#: 179
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: lxml
        SLS: sift.python-packages.lxml
        Run#: 180
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: undefined
        SLS: sift.python-packages.ioc_writer
        Run#: 181
        Comment: One or more requisite failed: sift.python-packages.lxml.lxml
      - ID: pefile
        SLS: sift.python-packages.pefile
        Run#: 182
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pycoin
        SLS: sift.python-packages.pycoin
        Run#: 183
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pysocks
        SLS: sift.python-packages.pysocks
        Run#: 184
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.

**Comment by guardian703** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/3169465/saltstack.log)

**Comment by guardian703** [comment]
Event trying to install the specific failed packages via pip (pip 2 is default) did not work:

$ python -m pip install colorama
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: The directory '/home/username/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/username.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: colorama in /usr/local/lib/python2.7/dist-packages (0.4.1)
username@siftworkstation -> ~ 
$ python -m pip install construct
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: The directory '/home/username/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/username/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: construct in /usr/local/lib/python2.7/dist-packages (2.5.3)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from construct) (1.10.0)

**Comment by ekristen** [comment]
Please try and re-install python-pip, then for any packages already installed with pip you have to specify the --upgrade option

**Comment by guardian703** [comment]
Did all that, and it still didn't work.  So, decided to just try Ubuntu 18.04 LTS new install, upgraded pip, packages, everything beforehand.  Finished all apt updates, and then tried the following the curl cli installation instructions, ran sudo sift install and received the following (I gotta tell you, it seems SIFT is just NOT working and requires a very particular environment to work properly):

> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz

Hashes for sift-saltstack-v2019.06.0.tar.gz do not match. Expected: dd58f05a41d242d4850a53ba7669c1265d49cb4baa8f3fd3a87df99ca1984d9a  /tmp/sift-saltstack-v2019.06.0.tar.gz
, Actual: 285504883bc7fcb27a31b1713c5aca6d1165c2450bc5e60467c187114877abbd  /tmp/sift-saltstack-v2019.06.0.tar.gz

Error: Hashes for sift-saltstack-v2019.06.0.tar.gz do not match. Expected: dd58f05a41d242d4850a53ba7669c1265d49cb4baa8f3fd3a87df99ca1984d9a  /tmp/sift-saltstack-v2019.06.0.tar.gz
, Actual: 285504883bc7fcb27a31b1713c5aca6d1165c2450bc5e60467c187114877abbd  /tmp/sift-saltstack-v2019.06.0.tar.gz

    at Object.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:375:13)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by guardian703** [comment]
Again ran:
sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.7.1/sift-cli-linux
sudo chmod +x /usr/local/bin/sift

**Comment by guardian703** [comment]
Okay, removed all sift saltstacks through rm -rf, then re-tried curl command and follow up commands.  waiting to see the results..weird how the saltstacks were different.

**Comment by ekristen** [comment]
The mismatch just means that something got downloaded partially. 

18.04 isn't supported yet, I'm currently working on it right now.

I've only seen this issue once before.  

Try this https://github.com/teamdfir/sift/issues/292#issuecomment-404863662

**Comment by guardian703** [comment]
Eric, sorry, but it looks like it's finally working mostly.  I'll report on the status at the end.  I kept track of all the commands I made sequentially.  You're smarter than me, but if this works I'll post it step by step if you wish.

**Comment by guardian703** [comment]
Okay, not bad, failed only on 93:

>> Incomplete due to Failures -- Success: 447, Failure: 93

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python-software-properties
        SLS: sift.packages.python-software-properties
        Run#: 0
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r522d37d77eb74036b413a49b7d098000.scope
      E: Package 'python-software-properties' has no installation candidate
      - ID: undefined
        SLS: sift.repos.docker
        Run#: 2
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.gift
        Run#: 4
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.sift
        Run#: 7
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.openjdk
        Run#: 12
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos
        Run#: 16
        Comment: The following requisites were not found:
                   require:
                       sls: sift.repos.ubuntu-universe

      - ID: afterglow
        SLS: sift.packages.afterglow
        Run#: 21
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-rff402a2b6f97494fa1868cdd8a4a9d6f.scope
      E: Unable to locate package afterglow
      - ID: undefined
        SLS: sift.packages.bitpim
        Run#: 27
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bitpim-lib
        Run#: 28
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bulk-extractor
        Run#: 33
        Comment: One or more requisite failed: sift.repos.sift.sift-repo, sift.repos.openjdk.openjdk-repo

**Comment by guardian703** [comment]
What log files would you like from me to assist?

**Comment by ekristen** [comment]
18.04 isn’t supported yet.

**Comment by michael-wiznowski** [comment]
@ekristen - Can you please include a list of requirements? I've been trying and failing to install on AWS using Ubuntu 18.04 Server as a base OS, not realizing it is not supported yet.

This is what I received, and I assume now it is from having 18.04 server as my base. I've previously added the user named 'sift', unless you recommend using ubuntu or root (hope not).

```
root $ sift --user=sift install
> sift-cli@1.7.1-master.f1177e4
Warning: You are running as root.
> sift-version: notinstalled

> Error! You must be root to execute this.
```
Is there a preferred method of installation for AWS and can you eventually make an AMI available (ideally with REMnux also installed) that can be launched and tailored as needed?

Thank you,
Mike

**Comment by ekristen** [comment]
@michael-wiznowski thanks for the feedback, it does seem that the docs are a bit out of date.

Ideally you want to run `sift` as the user you want to install as then with `sudo`.

At the time this was originally created 18.04 didn't exist therefore there was no check, but yes, I'm working on adding in verification to make sure it only works on certain distributions.

For this to work, I would recommend to switch user to sift, then `sudo sift install`.

I'm in the process of overhauling the CLI and supporting 18.04.

**Comment by michael-wiznowski** [comment]
@ekristen - thanks for the quick response and help. The install went well until the following:

Any ideas on how to finish the install? FYI - This is an Ubuntu server - do I need to install some Desktop packages?

```
>> Completed: sift-config-tools (Took: 0.413 ms)
>> Incomplete due to Failures -- Success: 528, Failure: 14
>>>> List of Failures (first 10 only)
     NOTE: First failure is generally the root cause.
     IMPORTANT: If opening a ticket, please include this information.
      - ID: dpapick
        SLS: sift.python-packages.dpapick
        Run#: 177
        Comment: Failed to install packages: dpapick. Error: Collecting dpapick
```

This is the output of `unname -a`
`Linux siftworkstation 4.4.0-1075-aws #85-Ubuntu
`
Thanks,
Mike

**Comment by ekristen** [comment]
`--mode=packages-only` if you are installing on a server.  

dpapick recently started failing in different scenarios, I'm trying to understand the best way to fix it. Seems to have to do with m2crypto mostly.

**Comment by cyberpasta** [comment]
It seems I am having similar problem, I am having issues installing and it seems related to m2crypto
ubuntu version:  Ubuntu 16.04.6
I am attaching the log file. Hope you can help..v been trying for a whole day to install with no success.
[saltstack.log](https://github.com/teamdfir/sift/files/3199977/saltstack.log)

**Comment by ahusmc** [comment]
I'm having the same issue on and AWS EC2 instance: 
Static hostname: siftworkstation
Icon name: computer-vm
Chassis: vm  
Virtualization: xen
Operating System: Ubuntu 16.04.6 LTS
Kernel: Linux 4.4.0-1083-aws
Architecture: x86-64

**Comment by ahusmc** [comment]
Any way we can get a legit SIFT AMI on the AWS marketplace?

**Comment by ekristen** [comment]
It’s on the roadmap.

**Comment by ahusmc** [comment]
Thanks @ekristen

**Comment by michael-wiznowski** [comment]
I second the need for a SIFT AMI that is ready to go. After initial launch, I would add some of our own specific tools, add our keys etc, and then save its as my AMI. I'd then update as needed to keep current. 

Thanks again for your help @ekristen

**Comment by ekristen** [comment]
Working on a server only version too.

**Comment by R34rvi3w** [comment]
I have it on 16.04 fresh install today, seems SANS pushes SIFT but I'm having better luck using Flare VM with less troubles. Not looking forward to getting an older SIFT workstation handed out again on USB... 
>> Completed: sift-config-tools (Took: 0.675 ms)

>> Incomplete due to Failures -- Success: 446, Failure: 94

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python-software-properties
        SLS: sift.packages.python-software-properties
        Run#: 0
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-rb3d6bcfefeb94d6b9f252c5480ea9377.scope
      E: Package 'python-software-properties' has no installation candidate
      - ID: undefined
        SLS: sift.repos.docker
        Run#: 2
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.gift
        Run#: 4
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.sift
        Run#: 7
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.openjdk
        Run#: 12
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos
        Run#: 16
        Comment: The following requisites were not found:
                   require:
                       sls: sift.repos.ubuntu-universe

      - ID: afterglow
        SLS: sift.packages.afterglow
        Run#: 21
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r1e14576cc3a24b2fb76aeffa831db052.scope
      E: Unable to locate package afterglow
      - ID: undefined
        SLS: sift.packages.bitpim
        Run#: 27
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bitpim-lib
        Run#: 28
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bulk-extractor
        Run#: 33
        Comment: One or more requisite failed: sift.repos.sift.sift-repo, sift.repos.openjdk.openjdk-repo

**Comment by ekristen** [comment]
@R34rvi3w the errors shown state that there's an underlying problem with the host OS. APT Lock or something is preventing the apt repos from being setup properly. The fact that it **can't** find a package is the key here.

The installs are tested daily and I haven't seen any failures recently.

I will do a full install right now to verify.

**Comment by ekristen** [comment]
I just released v2019.03.01-rc2, it's available by using the `--pre-release` flag. This is all the latest updates to include beta support for 18.04.

**Comment by ekristen** [comment]
I've already gotten past all the errors you've called out, so in general I know the build process is not broken, so lets troubleshoot your specific issues.

@R34rvi3w -- are you seeing any other errors on screen? Any system errors that unity/gnome is asking to report? I've noticed on my last few fresh installs of 16.04 I get an error about appstreamcli, which could be interfering. Otherwise the system could be attempting to get apt updates in the background (like if you enabled auto security updates) which would also interfere with the install process.

**Comment by R34rvi3w** [comment]
My bad, wrong image was used. Good to know we have 18.04 on the way shortly. Thank you for the follow up!

**Comment by ekristen** [comment]
16.04 and 18.04 are building successfully right now with the latest pre-release.

**Comment by guardian703** [comment]
Copy thanks I will try it out. Thanks for all your work Erik!


-------- Original message --------

**Comment by ekristen** [comment]
I'm marking this resolved for now.

**Comment by guardian703** [comment]
Quick question. What is the full command to run to have this pre release work? I arrive back in office Monday from alot of travel and planned to do it then. Thanks for your hard work on this!


-------- Original message --------

**Comment by ekristen** [comment]
sift install —pre-release

**Comment by guardian703** [comment]
Works great from what I can see on Ubuntu 18.04 LTS.  Thanks Erik for all your hard work!

Christopher W. Guest

________________________________

**Comment by BadIdea6** [comment]
So should we be using 18.04. All documentation indicates 16.04. Even the .ova is 16.04.
