### ISSUE TITLE
I can't move any case to my sift workstation

### ISSUE THREAD

**Issue by OxidePenetration** [teamdfir/sift#369]
I am following the getting started video by Rob Lee , but I am stuck at the part where he adding a new case to Sift workstation.
 My problem is after Ifconfig, I notice that my ip address is start with 172.17.0.1 instead of 192.168.x.x. My computer can't really search for that ip 172.17.0.1 , and there is no any credentials to login at all pls help

**Comment by ekristen** [comment]
The IP is all depending on the network. Share the output of ifconfig so I can take a look.

**Comment by OxidePenetration** [comment]
![ip](https://user-images.githubusercontent.com/50785556/57976664-0567c000-7a18-11e9-9ae1-8a4d3ff186e0.PNG)

**Comment by ekristen** [comment]
enp0s17 is your main interface, it has a 10.0.2.15 addr.

**Comment by OxidePenetration** [comment]
nothing happen after trying to search with 10.0.2.15. 
Is there any step that i could go wrong?

**Comment by ekristen** [comment]
I don't know what you mean by "search".

**Comment by OxidePenetration** [comment]
![run](https://user-images.githubusercontent.com/50785556/57976759-78723600-7a1a-11e9-8e70-28e8e0d13c15.PNG)
Run it at the document just like the video.

**Comment by ekristen** [comment]
I would suspect there is a problem with your networking then with virtualbox.

**Comment by OxidePenetration** [comment]
How do i fix that, any suggestion?
I have already try to redownload the ova file and reinstall virtualbox

**Comment by mark-hallman** [comment]
OxidePenetration,

First thing...  VirtualBox is not supported for the SANS DFIR VM's,
whether it is the free community version like you are using or the VM's
that come with SANS DFIR.  That is not to say that these VM's can't work in
VirtualBox,  they might.

First thing I would suggest it to download the free VMware Player or the
trial version of VMware Workstation (or Fusion for the Mac)  and try to use
the VM with those tools.  If they work,  then you know where the problem
is.  I know that the VM Tools work.

• https://www.vmware.com/products/workstation
• https://www.vmware.com/products/player
• http://www.vmware.com/products/fusion


Can you ping the VM from your host and the host from the VM?  Using the
10.0.2.15 IP Erik suggested.   Is your host's firewall enabled?  If so, try
turning it off.

What OS is your host using?  Windows, Linux, Mac?  If the host is running
Windows, try adjusting this setting via the Group Policy Editor.  Google
how to use the editor if you are unfamiliar.

In gpedit.msc, set Computer Configuration > Administrative Templates >
Network > Lanman Workstation > *Set Enable insecure guest logons to
Enabled.* This might allow you to access the Linux SIFT share.

-Mark
