### ISSUE TITLE
consider adding cyber chef to standard build

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#370]
would love to have an integrated, on-VM cyber chef install.  Ideally, one that can be updated with git or similar, as they add more capabilities all the time.

**Comment by ekristen** [comment]
Love the idea.

**Comment by ekristen** [comment]
I think the best way to do this is with a docker image. We can setup a build process for it and include the image. 

@philhagen how would you like to see this work? Have a script to start/stop/restart cyberchef?

**Comment by philhagen** [comment]
it's not a service that starts/stops - just a node app that can run via a web server+browser, as far as I understand.

It's my understanding that after building the raw HTML file, it's just dropped onto the VM.  Tried compiling it on SIFT 16.04, but there are some node issues.  I'm not sure docker is needed for making it available...

**Comment by ekristen** [comment]
I’ll look into it. AFAICT its a web app, so it runs via node on a port as a web service.

**Comment by Fetchered** [comment]
There happens to be a docker for this under remnux (docker pull remnux/cyberchef) however, contains 8.22 and last updated 6 months ago). Could be worthwhile to look at that and modify rather than start over.
Dockerfile on github: https://github.com/REMnux/docker/blob/master/cyberchef/Dockerfile

**Comment by ekristen** [comment]
That is what I had in mind.

**Comment by krisgelijkaan** [comment]
Indeed, https://hub.docker.com/r/remnux/cyberchef would be a great addition

**Comment by philhagen** [comment]
With the addition of electronic workbooks, this is even easier than ever.  I host the workbook at hxxp://localhost/workbook and put the CyberChef distro at hxxp://localhost/cyberchef.  Just drop files from the zip (currently https://gchq.github.io/CyberChef/CyberChef_v9.11.7.zip) into `/var/www/html/cyberchef/` and you're good to go.

**Comment by ekristen** [comment]
Great idea

**Comment by ekristen** [comment]
Done. Added as of https://github.com/teamdfir/sift-saltstack/releases/tag/v2019.11.1-rc2, installs to /var/www/html/cyberchef, now available by default at `localhost/cyberchef`
