### ISSUE TITLE
Volatility malsysproc missing

### ISSUE THREAD

**Issue by saltydog4n6** [teamdfir/sift#371]
Hi,
Can malsysproc be added back to SIFT? I have an old version of the SIFT workstation from FOR508 (Ubuntu 14.04) with malsysproc and a clean build on 16.04, and malsysproc is MIA.

I copied the files over to the new install, works until I rebuild and forget what I did. ;)

Thanks,
Salty

**Comment by ekristen** [comment]
If malsysproc isn't here https://github.com/volatilityfoundation/community then it's not included. I do not see it there.
