### ISSUE TITLE
(CLI) Ubuntu 16.04 failed install

### ISSUE THREAD

**Issue by bobiii84** [teamdfir/sift#372]
>> Incomplete due to Failures -- Success: 536, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 476
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 490
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 491
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 492
        Comment: One or more requisite failed: sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 549
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 550
        Comment: One or more requisite failed: sift.config.sift-config

**Comment by bobiii84** [comment]
Okay so I updated my pip version and it broke it worse, so I reinstalled pip to 9.0.3 and ran again. This time it seems to have installed, but still dropped these errors:

>> Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 550
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

**Comment by bobiii84** [comment]
Latest after reinstalling python:

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-wine-apt-update
        SLS: sift.packages.wine
        Run#: 249
        Comment: Problem encountered upgrading packages. Additional info follows:

result:
    ----------
    pid:
        15961
    retcode:
        100
    stderr:
        Running scope as unit run-rfab35d60b66048f7aaad668b294c5a6f.scope.
        E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/z/zeromq3/libzmq5_4.1.4-7ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.26 80]
        
        E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    stdout:
        Reading package lists...
        Building dependency tree...
        Reading state information...
        Calculating upgrade...
        The following packages were automatically installed and are no longer required:
          libsodium18 libzmq5 python-cffi-backend python-cryptography python-enum34
          python-ipaddress python-ndg-httpsclient python-openssl python-pyasn1
          snapd-login-service
        Use 'sudo apt autoremove' to remove them.
        The following packages will be upgraded:
          libzmq5
        1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
        Need to get 149 kB of archives.
        After this operation, 0 B of additional disk space will be used.
        Err:1 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 libzmq5 amd64 4.1.4-7ubuntu0.1
          404  Not Found [IP: 91.189.91.26 80]
      - ID: undefined
        SLS: sift.packages.wine
        Run#: 250
        Comment: One or more requisite failed: sift.packages.wine.sift-wine-apt-update
      - ID: undefined
        SLS: sift.packages
        Run#: 257
        Comment: One or more requisite failed: sift.packages.wine.sift-wine, sift.packages.wine.sift-wine-apt-update
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.packages.sift-packages

**Comment by bobiii84** [comment]
All this said, it seems to have installed. Verifying now.

**Comment by bobiii84** [comment]
Okay so I ran it one more time, just "sift install" and everything completed successfully. Very odd.

**Comment by CiscoCapa** [comment]
Hi,
Getting the same error here:

I tried all the documentation possible and I am still having the same issue

Any help

>>Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
