### ISSUE TITLE
Tweak ssh client configuration

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#373]
When ssh'ing to a remote system in certain classroom environments (notably those without internet access), the client hangs on connect due to the GSSAPI authentication.

Propose modifying `/etc/ssh/ssh_config` to set the following:
```
GSSAPIAuthentication no
```
This is the default, so commenting out or deleting the line that sets it to "yes" should be sufficient.

To test, run `ssh -v <user>@<hostname>` and verify that there are *no messages* stating the following:
`debug1: Unspecified GSS failure.  Minor code may provide more information`

**Comment by philhagen** [comment]
Note that in an network-connected environment, the `ssh` command will show the `debug1` message several times without delay.  When disconnecting the SIFT VM, resulting in a hung DNS request, the login will take around 15 seconds to continue.

**Comment by ekristen** [comment]
Interesting. I generally see dns as the cause of delays. I think we can probably make this change without affecting anything based on what I'm looking.

**Comment by philhagen** [comment]
Yep - same.  In the past I just disabled `UseDNS` on the server, but this is the first I've seen a client-side settings have such an effect.
