### ISSUE TITLE
SIFT on Ubuntu 19.04

### ISSUE THREAD

**Issue by jmccs50** [teamdfir/sift#374]
I have been trying to install SIFT Workstation on my VM Ubuntu19.04 but I don't have python-software-properties, instead I have python3-software-properties, is there any workaround?

**Comment by ekristen** [comment]
19.04 is not supported. Initial support for 18.04 is in place and we will support 20.04 shortly after it comes out, but we only support LTS versions

**Comment by ekristen** [comment]
As for a workaround you could clone the saltstack repo and attempt to change package names on the install instructions.

**Comment by ekristen** [comment]
Since we are not planning on supporting 19.04 at this time, I'm going to close this issue.

**Comment by jmccs50** [comment]
Thank you so much for the reply, I really appreciate

Please close the issue
