### ISSUE TITLE
[SALTSTACK] 18.04 Pre-Release Rekall Errors

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#375]
Minimal install Ubuntu 18.04.2 x64
Command: sudo sift install --pre-release
Pre-release selected was v2019.03.01-rc3
Errors after install:
```
>> Incomplete due to Failures -- Success: 536, Failure: 9

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: rekall-virtualenv
        SLS: sift.python-packages.rekall
        Run#: 245
        Comment: Created new virtualenv
Collecting pip==9.0.3
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Requirement already satisfied: setuptools in /opt/rekall/lib/python2.7/site-packages (41.0.1)
Requirement already satisfied: wheel in /opt/rekall/lib/python2.7/site-packages (0.33.4)
Collecting rekall
  Downloading https://files.pythonhosted.org/packages/af/38/af50983839850a2f803ee7d67a4659580906c32aabc6467eca5695b7c95a/rekall-1.7.1.zip (1.7MB)
Collecting rekall-agent<1.8,>=1.7.0rc1 (from rekall)
  Downloading https://files.pythonhosted.org/packages/7e/d3/e4ec0107839e8743ced4b5df869547096e3e5b840c5966e8e88883066f26/rekall_agent-1.7.1.zip (866kB)
Collecting rekall-lib<1.8,>=1.7.0rc1 (from rekall)
  Downloading https://files.pythonhosted.org/packages/89/15/82152b7aec6f7a0154863bec76402a084ed64bc370cbebd21a4ddd2d8690/rekall_lib-1.7.2rc1.zip (41kB)
Collecting rekall-core<1.8,>=1.7.0rc1 (from rekall)
  Downloading https://files.pythonhosted.org/packages/fc/a5/57836669015c2846ae30b9ab61f67945ec8a426ffdb4b2d84c615417810c/rekall-core-1.7.2rc1.zip (1.3MB)
Collecting ipython<7.0,>=5.0.0 (from rekall)
  Downloading https://files.pythonhosted.org/packages/b0/88/d996ab8be22cea1eaa18baee3678a11265e18cf09974728d683c51102148/ipython-5.8.0-py2-none-any.whl (760kB)
Collecting readline (from rekall)
  Downloading https://files.pythonhosted.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz (2.3MB)
Collecting future (from rekall-agent<1.8,>=1.7.0rc1->rekall)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: The directory '/home/forensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/forensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not install packages due to an EnvironmentError: CRC check failed 0x884d694d != 0x83c28d66L
      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 246
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-virtualenv
      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 247
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall
      - ID: undefined
        SLS: sift.python-packages
        Run#: 285
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.server
        Run#: 448
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.config.user.rekall
        Run#: 478
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.config.user
        Run#: 495
        Comment: One or more requisite failed: sift.config.user.rekall.sift-config-user-rekall-rc
      - ID: undefined
        SLS: sift.config
        Run#: 552
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 553
        Comment: One or more requisite failed: sift.server.sift-server-version-file, sift.config.sift-config
```

Cause:
Rekall requires future==0.16.0 and pyaff4==0.26post6 (and pyblake2-0.9.3, but this gets installed with pyaff4==0.26post6) but future==0.17.1 and pyaff4==0.27 are installed. 

Interim solution:
sudo pip install future==0.16.0 pyaff4==0.26post6
sudo pip install rekall rekall-agent

Proposed solution:
Change versions of salt-installed requirements to the aforementioned versions.

Tested with NIST CFReDS Memory Images (same ones used in rekal git) https://www.cfreds.nist.gov/mem/Basic_Memory_Images.html

**Comment by ekristen** [comment]
Interesting, I don't think we've seen this in any testing and I just did a full install. I'll look into it again.

**Comment by Fetchered** [comment]
The only modifications made to the OS after initial install were:
disable automatic check/download for software updates (to prevent Ubuntu from locking apt during a normal sift update or to prevent it from pre-caching the suggested downloads)

sudo apt update -y && sudo apt upgrade -y
sudo apt install curl (not installed in a minimal install)
sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.7.1/sift-cli-linux
sudo chmod +x /usr/local/bin/sift
sudo sift install --pre-release

I happened to have only recently rebuilt the docker for rekall for 16.04/18.04 support (not yet uploaded), which is why I happened to have recognized the python errors.

Changing those requirements allowed rekall to properly install and function, however, due to the suggested Interim fix, when I try to re-run sudo sift install --pre-release, it fails now with new errors, primarily regarding the fact that the symlink created in /opt/rekall already exists and cannot be overwritten.

My end result is that the GUI is not completely configured (background, etc), but all packages seem to function (so far).

**Comment by Fetchered** [comment]
For reference on the second set of errors:
```
>> Incomplete due to Failures -- Success: 538, Failure: 7

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: rekall-symlink
        SLS: sift.python-packages.rekall
        Run#: 247
        Comment: File exists where the symlink /usr/local/bin/rekall should be
      - ID: undefined
        SLS: sift.python-packages
        Run#: 285
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.server
        Run#: 448
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.config.user.rekall
        Run#: 478
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.config.user
        Run#: 495
        Comment: One or more requisite failed: sift.config.user.rekall.sift-config-user-rekall-rc
      - ID: undefined
        SLS: sift.config
        Run#: 550
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 551
        Comment: One or more requisite failed: sift.server.sift-server-version-file, sift.config.sift-config

```

**Comment by ekristen** [comment]
I don't see rekall errors at this time. Can you confirm you are still seeing these issues?

**Comment by BadIdea6** [comment]
Testing now

**Comment by Fetchered** [comment]
Will test this afternoon on a fresh Ubuntu 18.04.

**Comment by Fetchered** [comment]
Can confirm, rekall issues still exist.
>> COMPLETED SUCCESSFULLY -- Success: 549, Failure: 0
xxxxx@testbed:~$ rekall -h
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 6, in <module>
    from rekall.rekal import main
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.17.1 (/opt/rekall/lib/python2.7/site-packages), Requirement.parse('future==0.16.0'), set(['rekall-efilter']))

**Comment by ekristen** [comment]
oh, it is not falling on the install but the run, I somehow missed that distinction. 

Can you try and install 0.16.0 directly in it's virtualenv and see if that fixes it?

**Comment by Fetchered** [comment]
Fix which worked is up top in the initial post for the issue. 
`sudo pip install future==0.16.0 pyaff4==0.26post6
sudo pip install rekall rekall-agent`
