### ISSUE TITLE
Docker - SIFT Install

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#377]
More than likely unrelated to the SIFT VM and installation, however I am having only one single issue from installing SIFT CLI within a docker, pdftk. Snap requires systemctl running as PID 1, which isn't done by default in a basic configuration/install of docker.

I would like to know if, since you've published Dockerfiles, you've come across a solution for this. In Ubuntu 18.04 there is no PDFTK installation, and the installation of this via apt comes only in 18.10. There is a workaround by using [https://gitlab.com/pdftk-java/pdftk](url) for 18.04. Would you consider using this version instead of 'snap' so the intended version in a VM **AND** Docker would work? I've never actually used pdftk, so I am unaware of the entire difference between the two installations and how they would differ.

**Comment by ekristen** [comment]
This sounds like an issue with snap and docker. systemd shouldn't be running in a docker container. We might have to remove pdftk if installing docker or stop using snap. Snap was a quick fix to get pdftk into the 18.04 update.

**Comment by Fetchered** [comment]
Do you think the pdftk I posted earlier would be a better option? That way
we can avoid snap and keep a working version of pdftk.

**Comment by ekristen** [comment]
Yes that's a possible work around. I'll look into it.
