### ISSUE TITLE
Sift Fails on Machinea

### ISSUE THREAD

**Issue by BadIdea6** [teamdfir/sift#378]
So Close. Using Ubuntu 16.04 

>> Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Failed to install packages: machinae. Error: Collecting machinae
  Using cached https://files.pythonhosted.org/packages/d1/13/785b96f03f68f752825468aa7bd67a5c11ade6721ef9060aff3d9e9ffab6/machinae-1.4.8.tar.gz
Collecting dnspython3 (from machinae)
  Using cached https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip
Collecting ipwhois<0.11 (from machinae)
  Using cached https://files.pythonhosted.org/packages/94/6f/198334bc914c0347415097848dc812d3515b4fb7e7c191a41b29250d5c09/ipwhois-0.10.3.zip
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from machinae)
Collecting stopit (from machinae)
  Using cached https://files.pythonhosted.org/packages/35/58/e8bb0b0fb05baf07bbac1450c447d753da65f9701f551dca79823ce15d50/stopit-1.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): html5lib in /usr/lib/python3/dist-packages (from machinae)
Collecting relatime (from machinae)
  Using cached https://files.pythonhosted.org/packages/5c/14/1a905d8a40af2a69b51a07897782c085ee03c3bd87ea3b2226687ea886e3/relatime-1.1.0.tar.gz
Collecting tzlocal (from machinae)
  Using cached https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting filemagic (from machinae)
  Using cached https://files.pythonhosted.org/packages/8f/67/a1aedccc143597eea90e79134d14c7364e90174d31443e14674919716d87/filemagic-1.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): feedparser in /usr/lib/python3/dist-packages (from machinae)
Collecting defang (from machinae)
  Using cached https://files.pythonhosted.org/packages/c2/d6/a43e61a63054a1cb6f6ba0490dd5079127d2cffafb6707b562497a91bd4e/defang-0.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-01mqpi3a/defang/setup.py", line 21, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-01mqpi3a/defang/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1079: ordinal not in range(128)
    
    ---------------------------------------- Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-01mqpi3a/defang/
You are using pip version 8.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

**Comment by ekristen** [comment]
Thanks for the heads up, I was just alerted to this as well, I'm looking into it now.

**Comment by BadIdea6** [comment]
Happens on clean install and using your latest release.

**Comment by ekristen** [comment]
Fixed. Machinae depends on defang which has a 0.5.3 release that has bunch of escaped unicode which is breaking the install. I pinned it to 0.5.2 for now. Should be working and just published a new pre release

**Comment by BadIdea6** [comment]
Testing now.

**Comment by BadIdea6** [comment]
Same errors

**Comment by BadIdea6** [comment]
Please reopen:

>> Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Failed to install packages: machinae. Error: Collecting machinae
  Downloading https://files.pythonhosted.org/packages/d1/13/785b96f03f68f752825468aa7bd67a5c11ade6721ef9060aff3d9e9ffab6/machinae-1.4.8.tar.gz
Collecting dnspython3 (from machinae)
  Downloading https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip
Collecting ipwhois<0.11 (from machinae)
  Downloading https://files.pythonhosted.org/packages/94/6f/198334bc914c0347415097848dc812d3515b4fb7e7c191a41b29250d5c09/ipwhois-0.10.3.zip
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from machinae)
Collecting stopit (from machinae)
  Downloading https://files.pythonhosted.org/packages/35/58/e8bb0b0fb05baf07bbac1450c447d753da65f9701f551dca79823ce15d50/stopit-1.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): html5lib in /usr/lib/python3/dist-packages (from machinae)
Collecting relatime (from machinae)
  Downloading https://files.pythonhosted.org/packages/5c/14/1a905d8a40af2a69b51a07897782c085ee03c3bd87ea3b2226687ea886e3/relatime-1.1.0.tar.gz
Collecting tzlocal (from machinae)
  Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting filemagic (from machinae)
  Downloading https://files.pythonhosted.org/packages/8f/67/a1aedccc143597eea90e79134d14c7364e90174d31443e14674919716d87/filemagic-1.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): feedparser in /usr/lib/python3/dist-packages (from machinae)
Collecting defang (from machinae)
  Downloading https://files.pythonhosted.org/packages/c2/d6/a43e61a63054a1cb6f6ba0490dd5079127d2cffafb6707b562497a91bd4e/defang-0.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ss3g2skn/defang/setup.py", line 21, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-ss3g2skn/defang/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1079: ordinal not in range(128)
    
    ---------------------------------------- The directory '/home/mike/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mike/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ss3g2skn/defang/
You are using pip version 8.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 550
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

**Comment by ekristen** [comment]
Make sure you run with the pre release flag

**Comment by BadIdea6** [comment]
Where is the pre release flag?

**Comment by ekristen** [comment]
In the sift cli .. should be on the help page. 

‘sift install —pre-release’
