### ISSUE TITLE
Reopen #378

### ISSUE THREAD

**Issue by BadIdea6** [teamdfir/sift#379]
Please reopen:

        Incomplete due to Failures -- Success: 539, Failure: 3

                List of Failures (first 10 only)

 NOTE: First failure is generally the root cause.

 IMPORTANT: If opening a ticket, please include this information.

  - ID: sift-python-packages-machinae
    SLS: sift.python-packages.machinae
    Run#: 264
    Comment: Failed to install packages: machinae. Error: Collecting machinae

Downloading https://files.pythonhosted.org/packages/d1/13/785b96f03f68f752825468aa7bd67a5c11ade6721ef9060aff3d9e9ffab6/machinae-1.4.8.tar.gz
Collecting dnspython3 (from machinae)
Downloading https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip
Collecting ipwhois<0.11 (from machinae)
Downloading https://files.pythonhosted.org/packages/94/6f/198334bc914c0347415097848dc812d3515b4fb7e7c191a41b29250d5c09/ipwhois-0.10.3.zip
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from machinae)
Collecting stopit (from machinae)
Downloading https://files.pythonhosted.org/packages/35/58/e8bb0b0fb05baf07bbac1450c447d753da65f9701f551dca79823ce15d50/stopit-1.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python3/dist-packages (from machinae)
Requirement already satisfied (use --upgrade to upgrade): html5lib in /usr/lib/python3/dist-packages (from machinae)
Collecting relatime (from machinae)
Downloading https://files.pythonhosted.org/packages/5c/14/1a905d8a40af2a69b51a07897782c085ee03c3bd87ea3b2226687ea886e3/relatime-1.1.0.tar.gz
Collecting tzlocal (from machinae)
Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting filemagic (from machinae)
Downloading https://files.pythonhosted.org/packages/8f/67/a1aedccc143597eea90e79134d14c7364e90174d31443e14674919716d87/filemagic-1.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): feedparser in /usr/lib/python3/dist-packages (from machinae)
Collecting defang (from machinae)
Downloading https://files.pythonhosted.org/packages/c2/d6/a43e61a63054a1cb6f6ba0490dd5079127d2cffafb6707b562497a91bd4e/defang-0.5.3.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-ss3g2skn/defang/setup.py", line 21, in
long_description=read('README.md'),
File "/tmp/pip-build-ss3g2skn/defang/setup.py", line 8, in read
return open(os.path.join(os.path.dirname(file), fname)).read()
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1079: ordinal not in range(128)

---------------------------------------- The directory '/home/mike/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

The directory '/home/mike/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ss3g2skn/defang/
You are using pip version 8.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
- ID: undefined
SLS: sift.python-packages
Run#: 283
Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
- ID: undefined
SLS: sift.vm
Run#: 550
Comment: One or more requisite failed: sift.python-packages.sift-python-packages
@BadIdea6

**Comment by ekristen** [comment]
We could have re opened the other.

Did you run with ‘—pre-release’ flag?

**Comment by BadIdea6** [comment]
no redoing now

**Comment by BadIdea6** [comment]
Now 8 fails:
>> Incomplete due to Failures -- Success: 550, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-file
        SLS: sift.config.user.terminal_xenial
        Run#: 489
        Comment: Source file salt://sift/config/user/files/terminal-profiles.txt not found
      - ID: undefined
        SLS: sift.config.user.terminal_xenial
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file
      - ID: undefined
        SLS: sift.config.user.terminal
        Run#: 491
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file, sift.config.user.terminal_xenial.sift-config-terminal-profiles-install
      - ID: sift-config-theme-set-unity-logo
        SLS: sift.config.user.theme_xenial
        Run#: 499
        Comment: Source file salt://sift/files/sift/images/login_logo.png not found
      - ID: undefined
        SLS: sift.config.user.theme
        Run#: 502
        Comment: One or more requisite failed: sift.config.user.theme_xenial.sift-config-theme-set-unity-logo
      - ID: undefined
        SLS: sift.config.user
        Run#: 508
        Comment: One or more requisite failed: sift.config.user.terminal.sift-config-user-terminal, sift.config.user.theme.sift-config-user-theme
      - ID: undefined
        SLS: sift.config
        Run#: 565
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 566
        Comment: One or more requisite failed: sift.config.sift-config

**Comment by ekristen** [comment]
How are you running the command? In a terminal in unity or something else?

**Comment by BadIdea6** [comment]
Sudo sift install --pre-release

**Comment by BadIdea6** [comment]
Terminal
