### ISSUE TITLE
NEW SIFT INSTALL ON 16.04

### ISSUE THREAD

**Issue by dwizel** [teamdfir/sift#381]
After going through the previous installation issues and being able to troubleshoot from other people's mistakes which were similar to mine, I've finally hit a roadblock. This is a new SIFT install on Ubuntu 16.04 and this is my latest error. PIP did give me a lot of pain but I think I got past that by downgrading to 9.03 and installing through the pre-release. please see the error below. 

IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages.machinae
        Run#: 238
        Comment: One or more requisite failed: sift.python-packages.defang.sift-python-packages-defang
      - ID: undefined
        SLS: sift.python-packages
        Run#: 291
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.server
        Run#: 453
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: sift-config-terminal-profiles-file
        SLS: sift.config.user.terminal_xenial
        Run#: 489
        Comment: Source file salt://sift/config/user/files/terminal-profiles.txt not found
      - ID: undefined
        SLS: sift.config.user.terminal_xenial
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file
      - ID: undefined
        SLS: sift.config.user.terminal
        Run#: 491
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file, sift.config.user.terminal_xenial.sift-config-terminal-profiles-install
      - ID: sift-config-theme-set-unity-logo
        SLS: sift.config.user.theme_xenial
        Run#: 499
        Comment: Source file salt://sift/files/sift/images/login_logo.png not found
      - ID: undefined
        SLS: sift.config.user.theme
        Run#: 502
        Comment: One or more requisite failed: sift.config.user.theme_xenial.sift-config-theme-set-unity-logo
      - ID: undefined
        SLS: sift.config.user
        Run#: 508
        Comment: One or more requisite failed: sift.config.user.terminal.sift-config-user-terminal, sift.config.user.theme.sift-config-user-theme

**Comment by ekristen** [comment]
Looks like there is python3 order install issue. I’ll take a look and get this fixed as soon as possible, for now you can try and install python3 and python3 pip manually and it should then work

**Comment by dwizel** [comment]
Thanks @ekristen. Please see below when I tried to install manually. 
# apt install python3 python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.5.1-3).
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libsodium18 libzmq5 python-cffi-backend python-cryptography python-enum34 python-ipaddress python-pyasn1 snapd-login-service
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@siftworkstation -> /h/sift

**Comment by ekristen** [comment]
Try rerunning the install, it could have just been an order thing and they got installed later on.
