### ISSUE TITLE
Error with sift upgrade

### ISSUE THREAD

**Issue by DonMVB** [teamdfir/sift#382]
Hi - Downloaded SIFT Wks a few days ago, then updated the SIFT cli per the github instructions, ran an 'upgrade', and got the error trace below.

>> Completed: sift-config (Took: 0.691 ms)

>> Incomplete due to Failures -- Success: 522, Failure: 20

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: plaso-tools
        SLS: sift.packages.plaso-tools
        Run#: 158
        Comment: An error was encountered while installing package(s): Problem encountered installing package(s). Additional info follows:

changes:
    ----------
    libewf-dev:
        ----------
        new:
        old:
            20140608-6
    libewf-python:
        ----------
        new:
        old:
            20140608-2ppa1~xenial
    libewf-tools:
        ----------
        new:
        old:
            20140608-2ppa1~xenial
    sleuthkit:
        ----------
        new:
        old:
            4.2.0-13sift1~xenial
    xmount:
        ----------
        new:
        old:
            0.7.3-1build1
errors:
    - Running scope as unit run-reccab3c0adb34f56967c8a2f4cc3b49f.scope.
      
      Extracting templates from packages: 27%
      Extracting templates from packages: 55%
      Extracting templates from packages: 82%
      Extracting templates from packages: 100%
      E: Sub-process /usr/bin/dpkg returned an error code (1)
      - ID: sleuthkit
        SLS: sift.packages.sleuthkit
        Run#: 222
        Comment: An error was encountered while installing package(s): Problem encountered installing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit run-r2f27efe11cbe42f2be2b52e8aea18e4b.scope.
      E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
      - ID: sift-wine-apt-update
        SLS: sift.packages.wine
        Run#: 250
        Comment: Failed to get upgrades: E: Unmet dependencies. Try using -f.
      - ID: undefined
        SLS: sift.packages.wine
        Run#: 251
        Comment: One or more requisite failed: sift.packages.wine.sift-wine-apt-update
      - ID: xmount
        SLS: sift.packages.xmount
        Run#: 255
        Comment: An error was encountered while installing package(s): Problem encountered installing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit run-r02ea4190a1e444d48cfbddca328aaab5.scope.
      E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
      - ID: undefined
        SLS: sift.packages
        Run#: 258
        Comment: One or more requisite failed: sift.packages.wine.sift-wine, sift.packages.sleuthkit.sleuthkit, sift.packages.wine.sift-wine-apt-update, sift.packages.xmount.xmount
      - ID: sift-scripts-regripper-git
        SLS: sift.scripts.regripper
        Run#: 401
        Comment: error: Your local changes to the following files would be overwritten by merge:
	plugins/sam
Please, commit your changes or stash them before you can merge.
Aborting

Changes already made: https://github.com/keydet89/RegRipper2.8.git was fetched, resulting in updated refs. Local changes were discarded.
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 402
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 403
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 404
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git, sift.scripts.regripper.sift-scripts-regripper-directory
sansforensics@siftworkstation -> /m/s/d/winpmem.win10 
$

**Comment by ekristen** [comment]
Confirmed. Working on an update.

**Comment by kaizeninfosec** [comment]
Ran into same issue this evening.  Was curious if there is an update to this matter.

**Comment by ekristen** [comment]
I'll be looking into the 16.04 issues shortly, but 18.04 is installing and building just fine. You can access that via the`--pre-release` flag on the SIFT cli tool.

**Comment by kaizeninfosec** [comment]
Got around to testing this tonight...seemed to install successfully on 18.04 using the SIFT cli.  Took a long time though to build all the packages.

Which brought up a question....Does the --pre-release switch install only the packages (and some desktop links, change hostname, etc.)?  The GUI menus didn't seem to show up so finding all the tools is at is a bit confusing right now (or PEBKAC).  They seem to be in various places (though mostly under /usr in various directories).

Thanks for your work on this project.  It's a fantastic suite of tools.

**Comment by ekristen** [comment]
Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`
