### ISSUE TITLE
RegRipper Tool

### ISSUE THREAD

**Issue by gurumt05** [teamdfir/sift#385]
Hi Team,

Is there a possibility to do registry analysis for .reg format files. If yes, please let me know how to do it.

Note: I am new to SIFT workstation.

Thanks,
Guru

**Comment by ekristen** [comment]
Hi @gurumt05 this isn't really the best forum for these sorts of questions/conversations, it just doesn't get much attention from individuals who can answer these. You are better off emailing the dfir email list with questions like this. Issues here are mainly reserved for installation and distro management. 

That being said, SIFT does come with a regripper.pl tool that can be used. You should be able to access it via CLI by typing `rip.pl`

**Comment by gurumt05** [comment]
Hi @ekristen 
thanks for the information, could you please let me know the email id of DFIR team as i was checking i couldn't get it. please help me

**Comment by ekristen** [comment]
https://lists.sans.org/mailman/listinfo/dfir
