### ISSUE TITLE
Failure install 16.04 ubuntu

### ISSUE THREAD

**Issue by KarlRollis** [teamdfir/sift#386]
Hey guys i keep on rerunning the install on ubuntu 16.04 lts and it keeps on failing with what it looks like Python issue. Could you guys take a look and maybe guide me in the direction of how to fix it??
[siftfail.txt](https://github.com/teamdfir/sift/files/3614109/siftfail.txt)

**Comment by ekristen** [comment]
Try install with the --pre-release flag on the cli tool.
