### ISSUE TITLE
sift update - regripper update failures

### ISSUE THREAD

**Issue by Fustzecutor** [teamdfir/sift#388]
Hello, 

I'm getting errors on updating a SIFT instance on regripper. Although it seems to work, regripper is important part of our usage so I'd like to be sure that everything's fine and the keys are being parsed correctly.

saltstack.log errors on it

# [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/heads/'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [DEBUG   ] stdout: master
# [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/tags/'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [INFO    ] Checking local revision for /usr/local/src/regripper
# [INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [DEBUG   ] stdout: 79e852a37636daf0d0842a78baa355d514e5c104
# [INFO    ] Checking local branch for /usr/local/src/regripper
# [INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [DEBUG   ] stdout: master
# [INFO    ] Executing command ['git', 'remote', '--verbose'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [DEBUG   ] stdout: origin     https://github.com/keydet89/RegRipper2.8.git (fetch)
origin  https://github.com/keydet89/RegRipper2.8.git (push)
# [INFO    ] Executing command ['git', 'diff', 'HEAD'] as user 'root' in directory '/usr/local/src/regripper'
mesg: ttyname failed: Inappropriate ioctl for device
# [DEBUG   ] stdout: diff --git a/plugins/all b/plugins/all

Install errors : 

>> Incomplete due to Failures -- Success: 522, Failure: 17

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-regripper-git
        SLS: sift.scripts.regripper
        Run#: 398
        Comment: error: Your local changes to the following files would be overwritten by merge:
        plugins/sam
Please, commit your changes or stash them before you can merge.
Aborting

Changes already made: https://github.com/keydet89/RegRipper2.8.git was fetched, resulting in updated refs. Local changes were discarded.
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 399
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 400
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 401
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git, sift.scripts.regripper.sift-scripts-regripper-directory
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 402
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-binary
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 403
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 404
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 405
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 406
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git
      - ID: undefined
        SLS: sift.scripts.regripper
        Run#: 407
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-git

**Comment by ekristen** [comment]
Try the latest release please. If you still have issues comment again on this issue, for now I’m closing it.
