### ISSUE TITLE
[cli] saltstack repo on bionic is wrong

### ISSUE THREAD

**Issue by launchramp** [teamdfir/sift#397]
echo "deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2018.3 xenial main" | sudo tee /etc/apt/sources.list.d/saltstack.list is incorrect. 

Should be bionic not xenial.

**Comment by ekristen** [comment]
Fixed in the latest CLI and pre-release.

Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`
