### ISSUE TITLE
[saltstack] update LSSG cheat sheet

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#398]
At least the LSSG cheat sheet is updated past what is on the Desktop.

Linux Shell Survival Guide is now v2.3.  I can provide link privately until it's updated on website.

**Comment by ekristen** [comment]
@philhagen I think this was updated recently as I had to update the sha256 on the install script? can you confirm?

**Comment by philhagen** [comment]
I'm not sure where to look for the hash - can you point me in the right direction?

**Comment by ekristen** [comment]
https://github.com/teamdfir/sift-saltstack/blob/master/sift/config/user/pdfs.sls#L123

**Comment by philhagen** [comment]
thank you!  yep, that's the new one.  all good.
