### ISSUE TITLE
[CLI] unable to fully install sift-cli ununtu 18.04 server

### ISSUE THREAD

**Issue by omrirefaeli** [teamdfir/sift#399]
I am trying to install the sift-cli tool to an Ununtu server 18.04 via putty as this is an aws instance.
I did as instructed and downloaded the tool with `cURL`, then `sudo sift install`. bunch of errors came up and when I ran `sudo sift version`, the output was uninstalled.
however, some of the changes did apply, for example, the hostname is now "siftworkstation".
am I doing something wrong? what can be done here?

**Comment by ekristen** [comment]
Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`
