### ISSUE TITLE
Install Fails on Fresh Ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by raedeus** [teamdfir/sift#400]
[saltstack.log](https://github.com/teamdfir/sift/files/3847423/saltstack.log)

I've tried both the straight install and with the --pre-release flag. 

Not behind a proxy. Attempted install both before doing any updates with APT and after doing a full update/upgrade with no luck.

Thanks for your time,

raedeus

**Comment by ekristen** [comment]
Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`

**Comment by crahan** [comment]
Fixed! Thanks @ekristen!

![Screen Shot 2019-11-28 at 00 51 25](https://user-images.githubusercontent.com/172588/69766656-39ffc580-1179-11ea-83e5-405e2e9803df.png)

**Comment by raedeus** [comment]
Works for me too. Thanks a bunch!
