### ISSUE TITLE
readthedocs goes to different SIFT project

### ISSUE THREAD

**Issue by wesinator** [teamdfir/sift#404]
Hi,

FYI - http://sift.readthedocs.org redirects to https://sift.readthedocs.io/en/latest/ which is for a different SIFT project
The link is still listed at https://digital-forensics.sans.org/community/downloads 

did the docs move ?

**Comment by ekristen** [comment]
We decided to stop with the docs because SIFT is more of a distro then a tool to be documented and was difficult to keep reliable up to date information on it. I’ll mention to the SANS team about taking the link down.
