### ISSUE TITLE
Sleuthkit installation error

### ISSUE THREAD

**Issue by anishkgt** [teamdfir/sift#405]
Hello,

I cannot run sleuthkit after installing the latest version 4.7.0. None of there plugins are available. So tried running apt-get install sleuthkit and it is stuck at 25%

> sudo apt-get install sleuthkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libtsk13
The following packages will be REMOVED:
  libtsk
The following NEW packages will be installed:
  libtsk13 sleuthkit
0 upgraded, 2 newly installed, 1 to remove and 277 not upgraded.
Need to get 3,617 kB/4,426 kB of archives.
After this operation, 45.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://ppa.launchpad.net/sift/stable/ubuntu xenial/main amd64 sleuthkit amd64 4.6.5-4sift1~xenial                                                    
  Connection failed [IP: 91.189.95.83 80]
E: Failed to fetch http://ppa.launchpad.net/sift/stable/ubuntu/pool/main/s/sleuthkit/sleuthkit_4.6.5-4sift1~xenial_amd64.deb  Connection failed [IP: 91.189.95.83 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by ekristen** [comment]
Your apt is broken. Trying running update and install again.
