### ISSUE TITLE
[CLI] 1.7.1 -> 1.8.0 upgrade issue

### ISSUE THREAD

**Issue by zappeee** [teamdfir/sift#406]
After downloading 1.8.0 and running a "sift upgrade" the Saltstack installation just hangs.

> $ sudo sift upgrade
> > sift-cli@1.8.0
> > sift-version: v2019.06.0
> 
> NOTICE: Fixing incorrect Saltstack version configuration.
> Installing and configuring Saltstack properly ...

Update gives me this

> $ sudo sift update
> > sift-cli@1.8.0
> > sift-version: v2019.06.0
> 
> > downloading v2019.06.0
> >> downloading sift-saltstack-v2019.06.0.tar.gz.asc
> >> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
> >> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
> >> downloading sift-saltstack-v2019.06.0.tar.gz
> > validating file sift-saltstack-v2019.06.0.tar.gz
> > validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> > extracting update sift-saltstack-v2019.06.0.tar.gz
> > performing update v2019.06.0
> >> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log
> 
> 
> >> Incomplete due to Failures -- Success: 0, Failure: 1
> 
> >>>> List of Failures (first 10 only)
> 
>      NOTE: First failure is generally the root cause.
> 
>      IMPORTANT: If opening a ticket, please include this information.
> 
>       - ID: undefined
>         SLS: undefined
>         Run#: undefined
>         Comment: undefined
>

**Comment by zappeee** [comment]
```
/usr/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: siftworkstation
# [DEBUG   ] Configuration file path: /etc/salt/minion
# [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
# [DEBUG   ] Grains refresh requested. Refreshing grains.
# [DEBUG   ] Missing configuration file: /etc/salt/minion
# [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
# [DEBUG   ] Loading static grains from /etc/salt/grains
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded state.apply
# [DEBUG   ] LazyLoaded saltutil.is_running
# [DEBUG   ] LazyLoaded grains.get
# [DEBUG   ] LazyLoaded config.get
# [DEBUG   ] Updating roots fileserver cache
# [DEBUG   ] Gathering pillar data for state run
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Finished gathering pillar data for state run
# [INFO    ] Loading fresh modules for state activity
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Could not find file 'salt://sift/desktop.sls' in saltenv 'base'
# [DEBUG   ] Could not find file 'salt://sift/desktop/init.sls' in saltenv 'base'
# [DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'sift.desktop' in env 'base'

```

**Comment by ekristen** [comment]
Please run `sift upgrade` or `sift update --mode=complete`. I'll do a release that sets the mode based on the version being run later today.

**Comment by ekristen** [comment]
@zappeee please install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.1-rc1

**Comment by zappeee** [comment]
The "sift upgrade" worked now.
Should I still upgrade to the latest CLI?

**Comment by ekristen** [comment]
I will eventually push 1.8.1, but it'll be the same. You are good to go for now.
