### ISSUE TITLE
SIFT update fails

### ISSUE THREAD

**Issue by zappeee** [teamdfir/sift#408]
Fails with this errors

```
- ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 238
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
```
Tried upgrading to v2019.11.1-rc2, didn't help.

**Comment by ekristen** [comment]
Sounds like bad permissions likely something unique about your setup. Is this a clean install of ubuntu?

**Comment by zappeee** [comment]
From the start it's a VM downloaded from SANS.
Last week I could update without issues.

I can try revert to a snapshot

**Comment by zappeee** [comment]
Reverted back to an older snapshot.
Did an upgrade from v2019.06.0 to v2019.11.0 without issues.
Did an update after that and got the same issues.

**Comment by zappeee** [comment]
Tried upgrade v2019.12.0 and the issue remains

**Comment by zappeee** [comment]
and with 

$ sift version
> sift-cli@1.8.1-rc1
> sift-version: v2019.12.0

**Comment by ekristen** [comment]
What OS? I cannot reproduce this.

**Comment by zappeee** [comment]
Ubuntu 16.04

**Comment by ekristen** [comment]
Can you upgrade to 18.04? I can try and look into 16.04 later this week.

**Comment by zappeee** [comment]
Sure, I was just waiting as it still seemed to be in beta.

**Comment by ekristen** [comment]
It hasn't been signed off for class use yet, but we are working on it.

**Comment by zappeee** [comment]
After upgrade and a "sift update" I get these issues

`>> Incomplete due to Failures -- Success: 537, Failure: 14

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: plaso-tools
        SLS: sift.packages.plaso-tools
        Run#: 158
        Comment: No information found for 'plaso-tools'.
      - ID: rekall-virtualenv
        SLS: sift.python-packages.rekall
        Run#: 249
        Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 283, in managed
    before = set(__salt__['pip.freeze'](bin_env=name, user=user, use_vt=use_vt))
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1087, in freeze
    cur_version = version(bin_env)
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1210, in version
    raise CommandNotFoundError('Could not find a `pip` binary')
CommandNotFoundError: Could not find a `pip` binary

      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 250
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-virtualenv
      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 251
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts, sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.config.user.rekall
        Run#: 484
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal_bionic
        Run#: 491
        Comment: Command "dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/share/sift/terminal-profiles.txt" run
`

**Comment by ekristen** [comment]
How are you installing?  I cannot reproduce. I just installed on fresh 18.04 installs 4 times last night without issue and once today.

**Comment by ekristen** [comment]
Is this 18.04 or 16.04?

**Comment by zappeee** [comment]
I just did an upgrade from 16.04 to 18.04

**Comment by ekristen** [comment]
To be honest, that path has not been tested. Seems like your pip issues persist. Can you try a clean install of 18.04?

**Comment by zappeee** [comment]
A clean installation of 18.04.3 worked.

But a "sift update" got these other errors

```
>> Incomplete due to Failures -- Success: 547, Failure: 4

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts
      - ID: undefined
        SLS: sift.desktop
        Run#: 557
        Comment: One or more requisite failed: sift.server.sift-server-version-file

```

**Comment by ekristen** [comment]
Nice catch. I’ll fix that and kick an update out.

**Comment by zappeee** [comment]
Same issue while trying to upgrade to v2019.12.1

**Comment by ekristen** [comment]
Try the latest v2020.1.0 -- I've double check this resolves the last error.

**Comment by zappeee** [comment]
Works perfect, thanks!
