### ISSUE TITLE
Failed to configure repo

### ISSUE THREAD

**Issue by teddy133** [teamdfir/sift#409]
Currently receiving an issue when running an install of san sift on an ubuntu docker image below. 

>> Incomplete due to Failures -- Success: 530, Failure: 26

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: openjdk-repo
        SLS: sift.repos.openjdk
        Run#: 11
        Comment: Failed to configure repo 'openjdk-repo': Error: key retrieval failed: Executing: /tmp/tmp.gfwGtczEcd/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--logger-fd
1
--recv-keys
DA1A4A13543B466853BAF164EB9B1D8886F44E2A
gpgkeys: key DA1A4A13543B466853BAF164EB9B1D8886F44E2A can't be retrieved
gpg: requesting key 86F44E2A from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.

It seems as if it Failed to configure repo openjdk-repo. I recently resolved an issue that stated it couldn't download a package called defang==0.5.2 I resolved this but using pip to install it first. How can I get past this most current issue? Thanks

**Comment by ekristen** [comment]
This looks like you are having networking issues.

**Comment by teddy133** [comment]
I am able to curl and wget to any location and all the other packages and repos have downloaded successfully. Im not sure this is the cause of network configuration seeing as I can get similar files off location

**Comment by teddy133** [comment]
I have checked my network configuration and determined its not the issue. Is there any other cause sift cannot locate the package.

**Comment by ekristen** [comment]
Please attach the saltstack.log.
