### ISSUE TITLE
SIFT install fails

### ISSUE THREAD

**Issue by leenaarora** [teamdfir/sift#410]
I am trying to install SIFT on windows 10. Here is the screenshot with the error

![image](https://user-images.githubusercontent.com/56274289/70354640-1b1ac680-183e-11ea-8a7c-41ab0c7d1ac0.png)

**Comment by ekristen** [comment]
You need to specific —mode=server on the install. Desktop mode is not supported for WSL.

**Comment by leenaarora** [comment]
Thank you

**Comment by ekristen** [comment]
You are welcome.
