### ISSUE TITLE
Status of SIFT using Ubuntu 18.04

### ISSUE THREAD

**Issue by joachimmetz** [teamdfir/sift#411]
What is the status of SIFT using Ubuntu 18.04. We have plaso users reaching out that SIFT is still on 16.04 ?

16.04 will be end of standard support next year https://wiki.ubuntu.com/Releases

**Comment by ekristen** [comment]
We have 18.04 now from a community perspective. Testing is currently going on for class update and usage.

**Comment by joachimmetz** [comment]
thx for that info. I'm updating the plaso documentation https://github.com/log2timeline/plaso/pull/2788 where can point people to that want to use the latest plaso on SIFT?

**Comment by ekristen** [comment]
We aren't pinning the version of plaso, so an install/update of SIFT will include whatever the latest version of plaso that's publish to the launchpad PPA for the bionic distro.

**Comment by joachimmetz** [comment]
That does not answer my question, we stopped supporting 16.04 largely due to python 2 deprecation end of month.

Where can I point people to on how to get / use SIFT based on Ubuntu 18.04?

**Comment by ekristen** [comment]
@joachimmetz The best place would be to point people at https://github.com/teamdfir/sift, it has instructions on how to install in a few different ways. 

I'm working on a strategy for hosting and publishing details for the Community version in a more efficient way.

**Comment by joachimmetz** [comment]
I was hoping for some 18.04 specific info but I'll point people to the github pages
