### ISSUE TITLE
Defang python package

### ISSUE THREAD

**Issue by teddy133** [teamdfir/sift#412]
I keep getting this error. 

>> Incomplete due to Failures -- Success: 537, Failure: 19

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

It claims it cannot properly install defang==0.5.2 so before the installation I run pip3 install defang==0.5.2 and I also verify that its installed. What might one the problem . I have git and pip3 installed

**Comment by teddy133** [comment]
Hello Admin, Very crucial installation needed on my team. I keep getting the same issue

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Traceback (most recent call

Even thought I've already run pip3 install defang==0.5.2 before to try to resolve the issue it doesn't seem to resolve the issue. I have tried 3 different versions of the sift cli version with the last being v1.7.1-rc2 because was running into machinae issue earlier. This is a consistent error I am receiving. How can I move past this defang issue in my sift installer

**Comment by ekristen** [comment]
The latest CLI version is not 1.7.1 -- https://github.com/teamdfir/sift-cli/releases/tag/v1.8.1-rc1

Please use this version along with the `--pre-release` flag.

If you still have issues, please attach the saltstack.log the CLI informs you about in it's output.

**Comment by ekristen** [comment]
I am unable to reproduce this. Please upgrade to the latest CLI and upgrade to the latest version, if you still see this issue please reach back out on this issue, please do not open another issue.

Also please make sure you are testing on 18.04.
