### ISSUE TITLE
Unable to Run installation in server mode. 

### ISSUE THREAD

**Issue by teddy133** [teamdfir/sift#413]
I am running into this error.

root@005a1b9e37b3:/# sudo sift install --user tom --mode=server
> sift-cli@1.7.1-master.f1177e4
Warning: You are running as root.

server is not a valid install mode. Valid Modes: complete, packages-only

Even thought I Know server mode is a valid option. I am running on a centos machine with a ubuntu docker image trying to run the sift download from source

**Comment by ekristen** [comment]
Please update to the latest version of the CLI tool. Then login as your user Tom omit the user parameter and run with sudo

**Comment by teddy133** [comment]
Same error. 
tom@621e89ff09ec:/$ sudo sift install --mode=server

> sift-cli@1.7.1-master.f1177e4
server is not a valid install mode. Valid Modes: complete, packages-only

Logged in as user ran into same issue.

**Comment by ekristen** [comment]
That is not the latest version of the CLI

**Comment by ekristen** [comment]
The latest release candidate is https://github.com/teamdfir/sift-cli/releases/tag/v1.8.1-rc1, I will be releasing it the latest soon. The latest is currently 1.8.0, not 1.7.1.

Closing for now. If you upgrade to 1.8.1 and still have issues please come back and comment on this issue.
