### ISSUE TITLE
[CLI] Incorrect command on sift-cli releases page

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#415]
It's likely a typing error, but command for curl has a couple of digits swapped. Currently reads:
`curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.8.2-rc1/sift-cli-linux`

Should read:
`curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.8.1-rc2/sift-cli-linux`

**Comment by ekristen** [comment]
Thanks for the catch. Fixed.
