### ISSUE TITLE
Is there a SIFT ova that is compatible with vSphere 6.7?

### ISSUE THREAD

**Issue by whiten1** [teamdfir/sift#420]
I downloaded the ova file and ran VMware's ovftool.exe to convert the ova into the four ovf-related files. When I try to deploy the template, I get this error:

Issues detected with selected template. Details: - -1:-1:VALUE_ILLEGAL: No supported hardware versions among [vmx-12]; supported: [vmx-04, vmx-07, vmx-08, vmx-09, vmx-10, vmx-11].

Any thoughts on how I can get around that?

**Comment by ekristen** [comment]
I’m not sure how you can work around it. The ova is generally pretty low hardware compatibility setting.

**Comment by johndball** [comment]
I'm getting this as well. This is a relatively new error for me.

Error message: "Issues detected with selected template. Details: - -1:-1:VALUE_ILLEGAL: No supported hardware versions among [vmx-14]; supported: [vmx-04, vmx-07, vmx-08, vmx-09, vmx-10, vmx-11, vmx-12, vmx-13]."

Hypervisor OS: 
1. VMware ESXi 6.5.0 15177306
2. VMware ESXi 6.5.0 9298788
3. VMware ESXi 6.5.0 15177306. 
I'm deploying with VMware vCenter 6.7.0 14368073

 SIFT image downloaded 01 March 2020

MD5 calculations are the same so the image is good.
WEB: MD5 (SIFT-Workstation.ova) = 6c26585149386b4a977c7777af84be7d
Powershell: PS C:\Users\[redacted]> Get-FileHash -Algorithm "md5" C:\users\[redacted]\Downloads\SIFT-Workstation.ova

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             6C26585149386B4A977C7777AF84BE7D                                       C:\users\[redacted]\Down...
