### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by skull-df** [teamdfir/sift#421]
Hello 
Just trying to get SIFT forensics running on my clean Ubuntu installation and got this error. Looks like the key isn't available anymore.

Thanks for taking a look at this.
ERROR AS FOLLOWS:

Installing and configuring SaltStack properly ...
(node:6251) UnhandledPromiseRejectionWarning: Error: Command failed: wget -O - https://repo.saltstack.com/apt/ubuntu/null/amd64/2018.3/SALTSTACK-GPG-KEY.pub | apt-key add -
--2020-01-03 10:06:57--  https://repo.saltstack.com/apt/ubuntu/null/amd64/2018.3/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 13.226.42.81, 13.226.42.96, 13.226.42.77, ...
Connecting to repo.saltstack.com (repo.saltstack.com)|13.226.42.81|:443... connected.
Warning: apt-key output should not be parsed (stdout is not a terminal)
HTTP request sent, awaiting response... 404 Not Found
2020-01-03 10:06:58 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
(node:6251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ekristen** [comment]
What version of Ubuntu?

**Comment by skull-df** [comment]
> What version of Ubuntu?

It's Ubuntu 19.10.

**Comment by ekristen** [comment]
18.04 is the only supported version right now.

**Comment by skull-df** [comment]
> 
> 
> 18.04 is the only supported version right now.

Thank you. I downgraded it and it is working atm.

**Comment by ekristen** [comment]
I’ll update the tool to better tell what is and isn’t supported. Glad it’s working for you now. The next  major iteration to be supported will be 20.04.
