### ISSUE TITLE
michealb401

### ISSUE THREAD

**Issue by michealb401** [teamdfir/sift#423]
Just a testing note: 

Fresh Ubuntu 18 install, with apt-update/upgrade/dist-upgrade ran.  

SIFT immediately installation failure due to inability to identify current user (several places the yaml did not correctly populate the user field)

Was running sift install as root.  

Dropped to a standard user, ran sudo sift install and it installed.

**Comment by ekristen** [comment]
Yes, need to run as standard user w/ sudo.
