### ISSUE TITLE
[CLI] Missing packages during Ubuntu 16.04 installation

### ISSUE THREAD

**Issue by daniel-pittman** [teamdfir/sift#424]
Hello there!

I have been trying to install SIFT on a clean installation of Ubuntu 16.04 running in VirtualBox, and have encountered missing package failures each time I try. I have tried using CLI versions v1.8.0, v1.8.1-rc1, v1.8.1-rc2, and v1.6.1. I have tried sift-saltstack versions v2020.1.0, v2019.12.1, v2019.12.0, and v2018.16.0. The errors I encounter each time are similar to these:

```
E: Unable to locate package libbde
E: Unable to locate package libbde-tools
E: Package 'libesedb' has no installation candidate
E: Unable to locate package libesedb-tools
E: Unable to locate package libevt
E: Unable to locate package libevt-tools
E: Unable to locate package libevtx
E: Unable to locate package libevtx-tools
E: Package 'libewf' has no installation candidate
E: Package 'libewf-python' has no installation candidate
E: Unable to locate package libewf-tools
E: Unable to locate package libfsapfs-tools
E: Unable to locate package libfvde
E: Unable to locate package libfvde-tools
E: Unable to locate package libmsiecf
E: Unable to locate package libolecf
E: Unable to locate package libregf
E: Package 'libregf-python' has no installation candidate
E: Unable to locate package libregf-tools
E: Package 'libvmdk' has no installation candidate
E: Unable to locate package libvshadow
E: Package 'libvshadow-python' has no installation candidate
E: Unable to locate package libvshadow-tools
E: Unable to correct problems, you have held broken packages.
E: Package 'python-pytsk3' has no installation candidate

  test_|-sift-packages_|-sift-packages_|-nop:
    __run_num__: 225
    __sls__: sift.packages
    changes: {}
    comment: 'One or more requisite failed: sift.packages.libvshadow-python.sift-package-libvshadow-python,
      sift.packages.libolecf.sift-package-libolecf, sift.packages.libevtx.libevtx,
      sift.packages.xmount.xmount, sift.packages.libregf-tools.sift-package-libregf-tools,
      sift.packages.libvshadow.sift-package-libvshadow, sift.packages.libevt.libevt,
      sift.packages.libvmdk.sift-package-libvmdk, sift.packages.libewf.libewf, sift.packages.libvshadow-tools.sift-package-libvshadow-tools,
      sift.packages.libevt-tools.libevt-tools, sift.packages.libesedb-tools.sift-package-libesedb-tools,
      sift.packages.libevtx-tools.libevtx-tools, sift.packages.libfvde-tools.libfvde-tools,
      sift.packages.libewf-tools.libewf-tools, sift.packages.libfsapfs-tools.sift-package-libfsapfs-tools,
      sift.packages.libmsiecf.libmsiecf, sift.packages.libbde-tools.libbde-tools,
      sift.packages.libewf-python.libewf-python, sift.packages.libfvde.libfvde, sift.packages.libregf-python.sift-package-libregf-python,
      sift.packages.libregf.sift-package-libregf, sift.packages.libesedb.sift-package-libesedb,
      sift.packages.libbde.libbde, sift.packages.python-dfvfs.sift-package-python-dfvfs,
      sift.packages.python-plaso.python-plaso, sift.packages.python-pytsk3.sift-package-python-pytsk3'
    duration: 0.034
    result: false
```

I have attached the complete saltstack.log file as well for review. 

Any help with what I might be doing wrong during the installation would be greatly appreciated. Thanks in advance for your help!

[saltstack.log](https://github.com/teamdfir/sift/files/4050237/saltstack.log)

**Comment by ekristen** [comment]
I’ll take a look, but suggest you try 18.04

**Comment by daniel-pittman** [comment]
Thanks for the quick response!

I tried 18.04 originally, but had directed my students to use 16.04 instead once I noticed that 18.04 support was still in testing.

When I run the installation on 18.04, the installer completes, but lists the following errors:

`>> Incomplete due to Failures -- Success: 552, Failure: 5

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal_bionic
        Run#: 497
        Comment: Command "dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: undefined
        SLS: sift.config.user.terminal
        Run#: 498
        Comment: One or more requisite failed: sift.config.user.terminal_bionic.sift-config-terminal-profiles-install
      - ID: undefined
        SLS: sift.config.user
        Run#: 507
        Comment: One or more requisite failed: sift.config.user.terminal.sift-config-user-terminal
      - ID: undefined
        SLS: sift.config
        Run#: 562
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 563
        Comment: One or more requisite failed: sift.config.sift-config`

I assumed, based on reading other tickets, that this might be related to 18.04 switching to Gnome from Unity. I tried installing Unity using the command `sudo apt install ubuntu-unity-desktop` and switching the display manager to lightdm, but I still receive the failures even after making this change. Can I ignore those failures, or is there something else I should be trying?

Thanks very much for your help!

**Comment by malliman** [comment]
I am having the exact same issue in 16.04 is there a repository that may be missing?

**Comment by malliman** [comment]
Daniel,

Have you tried just a basic install of ubuntu 18.04 and add repository sudo add-apt-repository ppa:gift/stable and this seems to of worked for me it shows that rekall is too new as the issue blow but that is just looking at the log file the display on the screen didnt show any failures

> ERROR: rekall-efilter 1.6.0 has requirement future==0.16.0, but you'll have future 0.18.2 which is incompatible.

**Comment by Fetchered** [comment]
@daniel-pittman Out of curiosity, once you have Ubuntu 16 running and before you start the install of SIFT, did you complete a `sudo apt update`? I had this error early on in Ubuntu 16 and it took an apt update to fix them (the 'no candidate'/'unable to locate' errors).
As for the config terminal errors, I'm experiencing those myself and am also trying to figure it out.

**Comment by ekristen** [comment]
Thanks for pitching in, apologies for being quiet lately, life’s been busy. 

16.04 is broken current due to the plaso maintainers removing support for 16.04, I’m trying to get people onto 18.04 but haven’t decided how to handle plaso and 16.04 for users just yet. 

The user config errors tend to happen when ran incorrectly or there are odd permissions at play. 

If you don’t care about theme and specific user enhancements for the GUI, you can install server mode using the CLI tool.

Erik

**Comment by ekristen** [comment]
Close in favor of catch-all issue https://github.com/teamdfir/sift/issues/433
