### ISSUE TITLE
sift-cli unable to locate package libapfs-tools 

### ISSUE THREAD

**Issue by jsolderitsch** [teamdfir/sift#425]
I am using the 1.8.0 version of sift-cli. Trying to update my existing sift instance (installed within ubuntu 16) to the Sift v2020.1.0 release.

I get a message:

Incomplete due to Failures -- Success: 558, Failure: 6

And then I see:

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-package-libfsapfs-tools
        SLS: sift.packages.libfsapfs-tools
        Run#: 96
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-rf9ebe6688c264de285307f69d0b9043b.scope.
      E: Unable to locate package libfsapfs-tools
      - ID: undefined
        SLS: sift.packages
        Run#: 225
        Comment: One or more requisite failed: sift.packages.libfsapfs-tools.sift-package-libfsapfs-tools
 
Appreciate any ideas or suggestions to work-around this.

My current sift version is v2018.38.0

Attaching the saltstack log.
[saltstack.log](https://github.com/teamdfir/sift/files/4104358/saltstack.log)

**Comment by ekristen** [comment]
Unfortunately until further notice 16.04 is broken due to plaso removing support.

If possible please use 18.04

Erik

**Comment by jsolderitsch** [comment]
OK, I will attempt to bootstrap Sift into the 18.04 release for now.

**Comment by TFIS2020** [comment]
I'm experiencing similar after upgrade of .ova to 18.04.3 LTS:
>> Incomplete due to Failures -- Success: 543, Failure: 14

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-package-libfsapfs-tools
        SLS: sift.packages.libfsapfs-tools
        Run#: 96
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r63b13679437049509db46fd5d2d4b0a4.scope
      E: Unable to locate package libfsapfs-tools
      - ID: sift-package-libguestfs
        SLS: sift.packages.libguestfs-tools
        Run#: 100
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r9914ada81a9a462d961c8589429f5ccc.scope
      No apport report written because the error message indicates its a followup error from a previous failure.
      No apport report written because the error message indicates its a followup error from a previous failure.
      No apport report written because MaxReports is reached already
      No apport report written because MaxReports is reached already
      No apport report written because MaxReports is reached already
      No apport report written because MaxReports is reached already
      E: Sub-process /usr/bin/dpkg returned an error code (1)
      - ID: undefined
        SLS: sift.packages
        Run#: 224
        Comment: One or more requisite failed: sift.packages.libfsapfs-tools.sift-package-libfsapfs-tools, sift.packages.libguestfs-tools.sift-package-libguestfs
      - ID: rekall-virtualenv
        SLS: sift.python-packages.rekall
        Run#: 249
        Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 283, in managed
    before = set(__salt__['pip.freeze'](bin_env=name, user=user, use_vt=use_vt))
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1087, in freeze
    cur_version = version(bin_env)
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1210, in version
    raise CommandNotFoundError('Could not find a `pip` binary')
CommandNotFoundError: Could not find a `pip` binary

      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 250
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-virtualenv
      - ID: undefined
        SLS: sift.python-packages.rekall
        Run#: 251
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.server
        Run#: 460
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages, sift.packages.sift-packages
      - ID: undefined
        SLS: sift.config.user.rekall
        Run#: 490
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall, sift.python-packages.rekall.rekall-virtualenv, sift.python-packages.rekall.rekall-symlink
      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal_bionic
        Run#: 497
        Comment: Command "dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/share/sift/terminal-profiles.txt" run

Any suggestions?
Thanks

**Comment by jsolderitsch** [comment]
No suggestions for the follow-on from @TFIS2020 

I can report that a clean install into a relatively clean VMware 18.04.3 VM worked without any failures reported.

**Comment by ekristen** [comment]
Close in favor of catch-all issue https://github.com/teamdfir/sift/issues/433
