### ISSUE TITLE
Add new EZ-Tools poster (first of 3)

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#426]
There is a new EZ-Tools poster, which is the first of what will be a series of three.  Could you please add that to the mix?  @mark-hallman has the details and PDF file.

**Comment by mark-hallman** [comment]
Here is a link to the new poster.  Let me know if you need anything else.

https://sansorg.egnyte.com/dl/2dvo86zqJ1/DFIR_Command_Line_Final_Web.pdf_
