### ISSUE TITLE
[CLI] Incorrect curl command on newest release of cli

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#428]
Release URL for curl under releases is incorrect for RC2. 
Current: `curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/**v1.8.1-rc1**/sift-cli-linux`

Correct: `curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/**v1.8.1-rc2**/sift-cli-linux`
Note the change from 1.8.1-rc1 to 1.8.1-rc2

**Comment by ekristen** [comment]
Fixed
