### ISSUE TITLE
Terminal Profile Errors -- DBUS Session Problem

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#429]
CLI version 1.8.1-rc2
sift-version v2020.1.0
Installation completes with errors:
`>> Incomplete due to Failures -- Success: 552, Failure: 5

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal_bionic
        Run#: 497
        Comment: Command "dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: undefined
        SLS: sift.config.user.terminal
        Run#: 498
        Comment: One or more requisite failed: sift.config.user.terminal_bionic.sift-config-terminal-profiles-install
      - ID: undefined
        SLS: sift.config.user
        Run#: 507
        Comment: One or more requisite failed: sift.config.user.terminal.sift-config-user-terminal
      - ID: undefined
        SLS: sift.config
        Run#: 562
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 563
        Comment: One or more requisite failed: sift.config.sift-config
`
[saltstack.log](https://github.com/teamdfir/sift/files/4143328/saltstack.log)
Ubuntu 18.04.4 LTS (physical, not VM).
`Linux siftworkstation 5.3.0-28-generic 30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Only customization of installation is a different username (red) vice the default username.
Command: `sudo sift update`

**Comment by ekristen** [comment]
Is your home directory `/home/red`? 

It seems like there's an error with it talking to the dbus for the GUI. It's not exactly clear why.

```
DBUS_SESSION_BUS_ADDRESS: "Unable to create /home/red/.dbus/session-bus
unix:abstract=/tmp/dbus-viMHvYXLxe,guid=5295691284dd2b9dddc04f115e35ff0c"
```

**Comment by Fetchered** [comment]
Yes, my home dir is 'red'. Think the issue could be because it expects the
default user of forensics? I essentially set up Ubuntu 18.04.3 LTS with
minimal components, username 'red', sudo apt update && sudo apt upgrade -y,
then run the sift cli install.

**Comment by ekristen** [comment]
Custom usernames are supported. You are logged into gnome and running this from a terminal correct?

**Comment by Fetchered** [comment]
Yes that is correct.

**Comment by Fetchered** [comment]
No longer getting this error, getting a new one. This issue can be closed, will open a new issue with current problem.

**Comment by Fetchered** [comment]
Figured out what the problem actually was for this. The .dbus directory at /home/red was owned by root:root. I did a `sudo chown red:red /home/red/.dbus` and re-ran `sudo sift update` and it completed without error.
Wanted to make sure it was documented in case this error pops up again.
