### ISSUE TITLE
sans sift install failure

### ISSUE THREAD

**Issue by alirayait** [teamdfir/sift#431]
Hello, this is the first time for me to work with  SIFT.
I tried to follow the installation using SIFT_CLI from here https://digital-forensics.sans.org/community/downloads
I tried with Ubuntu 19.01 but it didn't work with me so I installed Ubuntu TLS 16.04 and followed the instruction agian but I am having the following error message:
Completed with Failures -- Success: 523, Failure: 41
here is my log file 

[saltstack.log](https://github.com/teamdfir/sift/files/4155517/saltstack.log)

**Comment by ekristen** [comment]
16.04 is currently broken. 18.04 should be ok.

**Comment by ekristen** [comment]
See #433
