### ISSUE TITLE
Consider publishing updated *.OVA's with each upgrade to public DL page

### ISSUE THREAD

**Issue by Resistor52** [teamdfir/sift#437]
The SIFT Workstation OVA file listed on https://digital-forensics.sans.org/community/downloads is (`sift-version: v2018.16.0`)[https://digital-forensics.sans.org/community/download-sift-kit/3.0] and folks frequently have issues upgrading. 

Is it possible to push a new OVA with each major upgrade so folks can use the latest & greatest?
Perhaps this can be automated. Thanks for considering the request.

**Comment by ekristen** [comment]
We are working on making that more of a reality. I don't have a timeline, but ideally it will start getting updated at least quarterly to start and more frequently if possible.

**Comment by ekristen** [comment]
We've streamlined the process and OVA updates will be making it to the sans website a bit more regularly now.
