### ISSUE TITLE
SIFT upgrade - errors

### ISSUE THREAD

**Issue by siftuser** [teamdfir/sift#438]
When I perform   `sift list-upgrades`
```
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.22.0

> List of available releases
  - v2020.1.0
  - v2019.12.1
  - v2019.12.0
  - v2019.11.0
  - v2019.06.0
  - v2018.38.0
  - v2018.35.0
  - v2018.28.0
  - v2018.26.1
  - v2018.26.0
```
`sift update `
`Completed with Failures -- Success: 528, Failure: 11`

`sift upgrade`
`Completed with Failures -- Success: 551, Failure: 13`

 OS - Ubuntu 16.04

I landed here as plaso was broken.

Any help ? Thanks!

**Comment by ekristen** [comment]
Closing in favor of #433 

16.04 is currently broken. 

Also please update your CLI to the latest version https://github.com/teamdfir/sift-cli
