### ISSUE TITLE
Launch EC2 from SIFT AMI fails

### ISSUE THREAD

**Issue by jonanathan** [teamdfir/sift#440]
I have successfully installed the latest SIFT version on a brand new Ubuntu 18.04. Due to the install time of SIFT, I need to create an AMI from the instance. I can successfully create an AMI from the instance. All instances launched from the SIFT AMI fail instance health checks and unable to connect to the instance at all. I know there are SIFT AMIs existing already but need to create this internally from the AWS quickstart templates.

EC2 instance screenshot does not show any errors. I also do not see any errors in the system log.

**Comment by jonanathan** [comment]
I believe this is due to changes the sift install does, which doesn't allow a new instance to boot from an AMI. I did try installing --mode=packages-only but the same error occurred. I then tried to use https://github.com/teamdfir/sift-saltstack on Ubuntu 16.04. After extracting the https://github.com/teamdfir/sift-saltstack/archive/v2020.1.0.tar.gz to /tmp/salt and running either 
`sudo salt-call -l info --local --file-root=/tmp/salt state.apply sift.vm` or 
`sudo salt-call -l info --local --file-root=/tmp/salt state.apply sift.pkgs`

I get the following error.

local:
    Data failed to compile:
----------
    No matching sls found for 'sift.pkgs' in env 'base'

**Comment by joejegan** [comment]
@jonanathan Did you find the solution?

**Comment by jonanathan** [comment]
@joejegan Yes - the sift-cli install makes changes to cloud-init and some other files. The install works fine on the instance, but if you create an AMI and launch from that instance it will fail due to those changes. What you have to do is install the packages only and skip over any configurations the sift-cli does. 

There is a --mode=packages-only on the sift-cli but that actually does not work. In the sift-cli docs it does mention that it is legacy. What you have to do is use the saltstack https://github.com/teamdfir/sift-saltstack. I got it working for 16.04 but haven't tried 18.04 yet. The 16.04 does have a number of failures but that may be due to lack of support/updates since the sift-cli is the recommended and supported way to install.

@ekristen let me know if this is expected or if the sift-cli packages-only is supposed to allow us to create AMIs and launch instances from that.

**Comment by ekristen** [comment]
sift-cli makes no changes to cloud-init, the SIFT AMI built process does however, semantics but it's an important distinction.

The SIFT AMI is in testing and not documented, apologies for that. The AMI works just fine AFAIK.

The build process changes the default user to sansforensics to match what the VM does.

`packages-only` is a legacy mode, it's replaced by `server` mode. The AMI uses this mode to install all the package and configs but doesn't try and do anything with X11.

**Comment by jonanathan** [comment]
@ekristen do you know what we need to do or change to get 18.04 AMI to be able to launch healthy instances? I was trying to install packages only from the sift-saltstack, which is working fine for me with 16.04 but when creating the 18.04 ami, all instances launched fail health checks so are unusable.

**Comment by ekristen** [comment]
The AMI I've created works just fine, I just tested again now. Unless you change the user-data on instance creation, the instance will still be created with the ubuntu username, but sansforensics will still be there as well.

It sounds like some part of the AMI creation or host setup you are doing for your own AMI is not being successful? What instance type are you using? All I can tell you is that the AMI I create is done directly using packer, saltstack, and 18.04 base server image.

**Comment by jonanathan** [comment]
@ekristen

**Comment by ekristen** [comment]
You can just use the sift-cli with mode=server to install the latest, no need to use salt-stack directly. `sift.pkgs` is just an alias for `sift.server` so no problem there and yes that installs just  the packages.

This is honestly outside the scope of what I'm willing and able to support right now. My plate is very full.

The AMI I provided for testing is working, I've tested in 3 different accounts and 3 different instances.

**Comment by joejegan** [comment]
@jonanathan found the root cause of the issue. Starting from Ubuntu 18.04, ifupdown package is considered obsolete. instead netplan is used.  saltstack has dependency to  ifupdown and there by installs the package during sift installation. The workround that i have used is to remove the ifupdown package before building the AMI.

**Comment by ekristen** [comment]
Interesting. It’s not obsolete. Ubuntu 18.04 just has a newer method available. ifupdown is still completely valid.

I’ll check it out regardless.

**Comment by jonanathan** [comment]
FYI, I was able to get the full sift package working and launching healthy instances only if I installed using saltstack and packer. Installing through saltstack via cli never was able to launch healthy instances from the AMI.

**Comment by ekristen** [comment]
Interesting. I appreciate the information. I will definitely take a look at this as it pertains to the AMI builds!

**Comment by jonanathan** [comment]
@ekristen happy to help test - let me know
