### ISSUE TITLE
Ubuntu 18.04 Fresh Install Failures

### ISSUE THREAD

**Issue by beerMT** [teamdfir/sift#442]
I've done a fresh install of Ubuntu18.04 ISO in virtualbox twice now and have received the following errors consistently:

>>Incomplete due to Failures -- Success: 553, Failure: 4

>>>>List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: timesketch
        SLS: sift.python-packages.timesketch
        Run#: 255
        Comment: Failed to install packages: timesketch. Error: Collecting timesketch
  Downloading https://files.pythonhosted.org/packages/09/a9/e15e7cc734f87f6750875b1b884f90c6cd2f0765f7ef0064c8ce88f26d19/timesketch-20200226.tar.gz (8.9MB)
    Complete output from command python setup.py egg_info:
    Unsupported Python version: 2.7.17 (default, Nov  7 2019, 10:07:09)
    [GCC 7.4.0], version 3.5 or higher required.
    
    -------------Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LlUvTb/timesketch/
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.timesketch.timesketch
      - ID: undefined
        SLS: sift.server
        Run#: 460
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.desktop
        Run#: 563
        Comment: One or more requisite failed: sift.server.sift-server-version-file

Any help in remediating would be greatly appreciated! First time through I tried to resolve the issues by forcing alias for python3 and PIP, but no success.

**Comment by ekristen** [comment]
Working on a fix, please see already opened issue. #432
