### ISSUE TITLE
Sift Install Throws Error -- Fresh Ubuntu 18.0.4

### ISSUE THREAD

**Issue by mire3212** [teamdfir/sift#443]
I just installed 18.0.4 LTS Desktop and ran apt updates. I then downloaded the SIFT-CLI 1.8.1 release and ran `sift install --pre-release` (due to issue #432) and got the following error:

```
$ sudo sift install --pre-release
> sift-cli@1.8.1
> sift-version: notinstalled

(node:9750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Since this is a VM, I went ahead and re-did the fresh install (erasing the disk first) and got the same error.

**Comment by mire3212** [comment]
`sudo sift install --pre-release` is the error. If I just use `sudo sift install`, it works fine. 

Can you possibly have this report a more effective error such as 'no pre-release software availbable', or just install the current version if pre-release == release?

**Comment by ekristen** [comment]
Interesting, that sounds like a bug, it definitely should have that behavior. I appreciate you bringing that to my attention and that you were able to resolve it. 

I'll add it to my list to fix for the next CLI update.
