### ISSUE TITLE
CLI - sift cli upgrade fails on 18.04

### ISSUE THREAD

**Issue by ThugSiem** [teamdfir/sift#445]
System was desktop 16.04 LTS, sift upgrade failed, research suggested upgrading to ubuntu 18.04 and sift cli 1.8.2.

sudo sift --no-cache --verbose upgrade
> sift-cli@1.8.2
> sift-version: v2018.16.0

> downloading v2020.2.1
>> downloading sift-saltstack-v2020.2.1.tar.gz.asc
>> downloading sift-saltstack-v2020.2.1.tar.gz.sha256
>> downloading sift-saltstack-v2020.2.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.2.1.tar.gz
> validating file sift-saltstack-v2020.2.1.tar.gz
> validating signature for sift-saltstack-v2020.2.1.tar.gz.sha256
> extracting update sift-saltstack-v2020.2.1.tar.gz
> performing update v2020.2.1
>> Log file: /var/cache/sift/cli/v2020.2.1/saltstack.log

>> Incomplete due to Failures -- Success: 0, Failure: 1

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined

from the SaltStack.log:

[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: siftworkstation
# [DEBUG   ] Configuration file path: /etc/salt/minion
# [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
# [DEBUG   ] Grains refresh requested. Refreshing grains.
# [DEBUG   ] Reading configuration from /etc/salt/minion
# [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
# [DEBUG   ] Loading static grains from /etc/salt/grains
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded state.apply
# [DEBUG   ] LazyLoaded saltutil.is_running
# [DEBUG   ] LazyLoaded grains.get
# [DEBUG   ] LazyLoaded config.get
# [DEBUG   ] Updating roots fileserver cache
# [DEBUG   ] Gathering pillar data for state run
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Finished gathering pillar data for state run
# [INFO    ] Loading fresh modules for state activity
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Could not find file 'salt://undefined.sls' in saltenv 'base'
# [DEBUG   ] Could not find file 'salt://undefined/init.sls' in saltenv 'base'
# [DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'undefined' in env 'base'

**Comment by Fetchered** [comment]
Out of curiosity, did you upgrade 16.04 to 18.04, or was it a fresh install of 18.04? And did you happen to have a sift-cli already in the OS prior to 1.8.2? 

I'd had a similar situation once where I went from 1.7.1 to 1.8.1-rc2 and got the same issue. Downgraded the cli to 1.8.0, sift update and upgrade worked. Then after the update/upgrade, downloaded the latest cli and all was good.

Details here: #427

**Comment by ThugSiem** [comment]
correct, I was at 16.04, sift update/upgrade failed.  
I updated to sift-cli v1.8.2, failed
I upgraded to 18.04, sift-cli fails.  
I attempted the salt-stack beta upgrade however, that kept showing errors thus I canceled.
It seems to me that somehow I have a corrupted salt-stack.  Based on:     # [DEBUG ] Could not find file 'salt://undefined.sls' in saltenv 'base'    # [DEBUG ] Could not find file 'salt://undefined/init.sls' in saltenv 'base'

I am at the point, I'm ready to re-install SIFT from scratch.  I just don't want to have to reload the OS with all of the case data that I have.

    On Sunday, March 1, 2020, 08:16:41 PM CST, Fetchered <notifications@github.com> wrote:  
 
 
Out of curiosity, did you upgrade 16.04 to 18.04, or was it a fresh install of 18.04? And did you happen to have a sift-cli already in the OS prior to 1.8.2?

I'd had a similar situation once where I went from 1.7.1 to 1.8.1-rc2 and got the same issue. Downgraded the cli to 1.8.0, sift update and upgrade worked. Then after the update/upgrade, downloaded the latest cli and all was good.

Details here: #427

**Comment by ekristen** [comment]
Please attach the log from the CLI

**Comment by ThugSiem** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/4275976/saltstack.log)
attached log

**Comment by ekristen** [comment]
Can you provide the contents of /etc/sift-config

I just published v1.8.3 of the CLI to fix a bug about install modes being checked, please upgrade to this as well.

**Comment by ThugSiem** [comment]
Interesting.  I do not have an /etc/sift-config file.
    On Monday, March 2, 2020, 09:00:17 AM CST, Erik Kristensen <notifications@github.com> wrote:  
 
 
Can you provide the contents of /etc/sift-config

I just published v1.8.3 of the CLI to fix a bug about install modes being checked, please upgrade to this as well.

**Comment by ThugSiem** [comment]
sansforensics@siftworkstation: ~
$ ll /etc/sift*
-rw-r--r-- 1 root root 29 Apr 18  2018 /etc/sift_build_date
-rw-r--r-- 1 root root 11 May 31  2018 /etc/sift-version
sansforensics@siftworkstation: ~
$ cat /etc/sift_build_date 
Wed Apr 18 16:12:14 MDT 2018
sansforensics@siftworkstation: ~
$ cat /etc/sift-version 
v2018.16.0


    On Monday, March 2, 2020, 09:00:17 AM CST, Erik Kristensen <notifications@github.com> wrote:  
 
 
Can you provide the contents of /etc/sift-config

I just published v1.8.3 of the CLI to fix a bug about install modes being checked, please upgrade to this as well.

**Comment by ThugSiem** [comment]
I renamed the sift_build_date and sift-version files in /etc and now running install
    On Monday, March 2, 2020, 06:32:31 PM CST, Nathan King <nking@yahoo.com> wrote:  
 
  

sansforensics@siftworkstation: ~
$ ll /etc/sift*
-rw-r--r-- 1 root root 29 Apr 18  2018 /etc/sift_build_date
-rw-r--r-- 1 root root 11 May 31  2018 /etc/sift-version
sansforensics@siftworkstation: ~
$ cat /etc/sift_build_date 
Wed Apr 18 16:12:14 MDT 2018
sansforensics@siftworkstation: ~
$ cat /etc/sift-version 
v2018.16.0


    On Monday, March 2, 2020, 09:00:17 AM CST, Erik Kristensen <notifications@github.com> wrote:  
 
 
Can you provide the contents of /etc/sift-config

I just published v1.8.3 of the CLI to fix a bug about install modes being checked, please upgrade to this as well.

**Comment by ThugSiem** [comment]
I renamed the /etc/sift-version and /etc/sift_build_data and re-installed and after fixing the recall issues it is now installed.
