### ISSUE TITLE
[SALTSTACK] RegRipper requires update due to timestamp issues

### ISSUE THREAD

**Issue by Fetchered** [teamdfir/sift#447]
Based on testing with several registry hives, and the Github issue here [https://github.com/keydet89/RegRipper2.8/issues/60](url), Regripper requires an update.

When running multiple plugins against multiple hives, almost all of the timestamps revert to Jan 1 1970.
`rip.pl -r SAM -p regtime`
`Thu Jan  1 00:00:00 1970Z 	SAM\SAM\Domains\Builtin\Groups `
`Thu Jan  1 00:00:00 1970Z 	SAM\SAM\Domains\Builtin\Groups\Names `
`Thu Jan  1 00:00:00 1970Z 	SAM\SAM\Domains\Builtin\Users `
`Thu Jan  1 00:00:00 1970Z 	SAM\SAM\Domains\Builtin\Users\Names `
`Thu Jan  1 00:00:00 1970Z 	SAM\SAM\RXACT `

`rip.pl -r system -f system`
`Launching termserv v.20190527`
`ControlSet001\Control\Terminal Server`
`LastWrite Time Thu Jan  1 00:00:00 1970 (UTC)`
`Launching eventlog v.20090112`
`eventlog v.20090112`
`(System) Get EventLog configuration info`

`Application \ Thu Jan  1 00:00:00 1970Z`
`  File               = %SystemRoot%\system32\config\AppEvent.Evt`
`  DisplayNameFile    = %SystemRoot%\system32\els.dll`
`  MaxSize            = 512.00KB`
`  Retention          = 7.00 days`

`Security \ Thu Jan  1 00:00:00 1970Z`
`  File               = %SystemRoot%\System32\config\SecEvent.Evt`
`  DisplayNameFile    = %SystemRoot%\System32\els.dll`
`  MaxSize            = 512.00KB`
`  Retention          = 7.00 days`

 $ sudo sift version
 sift-cli@1.8.3
 sift-version: v2020.2.1

**Comment by Fetchered** [comment]
Actual fix is to place the new Base.pm in /usr/share/perl5/Parse/Win32Registry folder (rename the existing to old for backup if desired), and place the new File.pm and Key.pm into /usr/share/perl5/Parse/Win32Registry/WinNT.

Remainder of files can be updated from the /usr/share/regripper dir.

**Comment by ekristen** [comment]
Thanks @Fetchered I'll get it updated as soon as I can.

**Comment by chootbl** [comment]
@Fetchered Thanks. I spend hours to solve this issue. Glad to stumbled over this thread. I am new to Linux. Where do I get a "new" Base.pm, File.pm and Key.pm file than I can place in the folders as described above? Thank you for your help

**Comment by digitalsleuth** [comment]
@chootbl You can find the files [here.](https://github.com/keydet89/RegRipper2.8) This is Harlan Carvey's GitHub, developer of the tool. 

Cheers! (digitalsleuth, formerly Fetchered)

**Comment by chootbl** [comment]
@digitalsleuth Thanks DS... you saved me a nightshift! Thank you so much. I really spend hours trying to fix it. With your help, RegRipper now parses the timestamp correct.

**Comment by digitalsleuth** [comment]
Anytime. Cheers!

**Comment by ekristen** [comment]
2020.7.1 is out with regripper3.0
