### ISSUE TITLE
Sift installation issues - Ubuntu 16.04

### ISSUE THREAD

**Issue by ragalasiva91** [teamdfir/sift#448]
While running the command: gpg --verify sift-cli-linux.sha256.asc I am getting below error
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
Can you please help me on how to resolve this issue.

**Comment by ekristen** [comment]
You don't have to validate the CLI unless you want to. The instructions are here https://github.com/teamdfir/sift-cli.

Alternatively you can simply just install the latest https://github.com/teamdfir/sift-cli/releases/tag/v1.8.3
