### ISSUE TITLE
SIFT

### ISSUE THREAD

**Issue by tamisuraca** [teamdfir/sift#451]
I downloaded and installed the SIFT Workstation from your website at  https://digital-forensics.sans.org/community/downloads.  When I launched it, it doesn't contain the open-source incident response and tools.  Please advise.  Thank you.

**Comment by brendancarey33** [comment]
Can you expand on what is missing?
Please do a 'sudo sift version'

**Comment by tamisuraca** [comment]
I tried sudo sift version and not found.

I chose option #1 SIFT VM Appliance Download at https://digital-forensics.sans.org/community/downloads.  I did not install Ubuntu in option #2. 

I've attached a screenshot of what it looks like, sudo sift version not found, and empty cases folder.  The other file is a screenshot of the SIFT workstation from the SANS course I took.  As you can see, there is a difference between the two screenshots...unless I'm missing something.
Thank you.
![missing items in SIFT](https://user-images.githubusercontent.com/62427710/77365412-778ded00-6d2c-11ea-8b7f-13634a112e6d.JPG)
![SIFT for FOR500](https://user-images.githubusercontent.com/62427710/77365428-7e1c6480-6d2c-11ea-9336-455554065188.jpg)

**Comment by ekristen** [comment]
The SIFT Workstation from the website is just a VM with all the core tools installed. It does not come with any case data as that's course provided data. 

Many course authors opt to take the "community" edition, which is what you download from the website, and modify for their specific course by adding in additional tooling, or changing the desktop icons like you have shown in the second screenshot.

Currently there are not community editions of the course specific modified VMs.
