### ISSUE TITLE
during install /usr/local/bin/sift: ELF : not found

### ISSUE THREAD

**Issue by dwmetz** [teamdfir/sift#452]
I'm working on a new SIFT project and wondered if you ever saw the issue of :

/usr/local/bin/sift: 1: /usr/local/bin/sift: ELF : not found
/usr/local/bin/sift: 2: /usr/local/bin/sift: Syntax error: "(" unexpected

when running the installer.

OS = Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1019-raspi2 aarch64)

results in the following in /usr/local/bin

''$'\001'','$'\353\216''@S'$'\226\002''@8'   sift

**Comment by ekristen** [comment]
amd64 is the only architecture supported at this time.
