### ISSUE TITLE
SIFT Not Installing

### ISSUE THREAD

**Issue by klscomputing** [teamdfir/sift#453]
I'm having similar issues on two laptops. Both windows 10 and both just had the linux subsystem and ubuntu 18.04 installed.  Let's start with one.
 ......

> > Running: /mnt/shadow_mount/vss26
> >> Running: /mnt/shadow_mount/vss27
> >> Running: /mnt/shadow_mount/vss28
> >> Running: /mnt/shadow_mount/vss29
> >> Running: /mnt/shadow_mount/vss30
> >> Running: salt-minion
> >> Running: /etc/samba/smb.conf
> >> Running: smbd
> >> Running: nmbd
> >> Running: /etc/foremost.conf
> >> Running: /usr/local/etc/foremost.conf
> >> Running: sift-config-tools
> Update returned exit code not zero
> Error: Update returned exit code not zero
>     at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
>     at ChildProcess.emit (events.js:196:13)
>     at maybeClose (internal/child_process.js:1011:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
> 
> 
> ----- PLEASE READ ----------------------
> 
> A lot of failures are caused by the apt system being locked
> or unhealthy.
> 
> Before opening an issue in GitHub, please check to see if
> your apt system is healthy.
> 
> Try running 'apt-get update' then remove any packages that
> aren't used by running 'apt-get autoremove'
> 
> __________________________________________

I've tried the apt-get update and apt-get autoremove and there was nothing to do.
Also rebooted, redownloaded and tried again.

Any other help?
[saltstack.log](https://github.com/teamdfir/sift/files/4421874/saltstack.log)

**Comment by ekristen** [comment]
How are you installing? 
If using the cli, what's the command you are running? 
If using the cli, what version of the cli are you using?

**Comment by klscomputing** [comment]
the command is  sift install

at least that was the first one, which failed and then after doing the apt-get etc., etc., I tried sift install and sift update

The version was downloaded from github today  ... is 

> sift-cli@1.8.5
> sift-version: v2020.2.1

> mode: desktop

Thank you for your assistance

**Comment by ekristen** [comment]
run with `--mode=server` -- desktop won't work with windows subsystem, it's not actually a desktop.

**Comment by klscomputing** [comment]
OK... it says sift is already installed and won't install. I don't see an uninstall option? how do you switch to server?

**Comment by ekristen** [comment]
Try `sift upgrade --mode=server`

**Comment by klscomputing** [comment]
sift upgrade --mode=server
> sift-cli@1.8.5
> sift-version: v2020.2.1

> mode: server
No upgrades available

**Comment by Kojuda** [comment]
I have exactly the same problem. I'm under a fresh Ubuntu 18.04 with Vbox. I have used the latest release 1.8.5 with the curl command and install sift.

The bug has happened exactly at the same moment as the author (sift-config-tools). So I've tried with --mode=server and the bug has appeared at another time : 

`
>> Running: /usr/local/bin/vshot
>> Running: sift-scripts
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

`

All the Virtual Box was clean (Updated, upgraded, autoremoved) and I'm running it with Windows 10 too.

**Comment by klscomputing** [comment]
On a different system, I also had just installed the windows subsystem for linux, and then install ubuntu 18.04

after downloading sift and running
sift install --mode=server 
it gets to 

______________________
>> Running: /usr/local/bin/sqlparser.py
>> Running: /usr/local/bin/sqlparser.py
>> Running: /usr/local/bin/usbdeviceforensics.py
>> Running: /usr/local/bin/usbdeviceforensics.py
>> Running: /usr/local/src/virustotal-search-v0.1.4
>> Running: /usr/local/bin/virustotal-search.py
>> Running: /usr/local/src/virustotal-submit-v0.0.3
>> Running: /usr/local/bin/virustotal-submit.py
>> Running: /usr/local/bin/vshot
>> Running: sift-scripts
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'
_____________________________
and errors out.
[saltstack.log](https://github.com/teamdfir/sift/files/4422681/saltstack.log)

**Comment by ekristen** [comment]
Windows 10 Linux Subsystem is not the same as VirtualBox.

Windows 10 Linux Subsystem installs Ubuntu 18.04 Server (not desktop)

VirtualBox you can install any version you want.

---

@klscomputing `/etc/sift-version` can be removed and then just run the install command again but with `--mode=server`

@Kojuda I would need the saltstack.log file to be able to troubleshoot.

---

@klscomputing your saltstack log seems to indicate that there's a problem resolving dns for the archive.ubuntu.com so several packages fail to install. You should be able to simply run the install command to try again. The tool is smart it is idempotent, it will only install or change things it needs to, if the job is already done it skips it and moves on.

**Comment by klscomputing** [comment]
for computer 1 ... (original issue) removing /etc/sift-version and reinstalling worked.

>> COMPLETED SUCCESSFULLY -- Success: 455, Failure: 0
root@siftworkstation:/# 

for computer 2 .... trying again worked.... 

Thank you very much for all your help! Stay safe and have a great day.

**Comment by Kojuda** [comment]
At the base, I've always installed with desktop mode, so the problem is not here.

I am not used to produce this log, if you can give me a link saying how I can produce it for you, it would be nice !
