### ISSUE TITLE
SIFT not installing

### ISSUE THREAD

**Issue by Kojuda** [teamdfir/sift#454]
I have tried to install sift with the latest release 1.8.5 through the curl command on a fresh Ubuntu 18.04 VM. 

So I run : 

`
sudo sift install --mode=desktop
`

I got 

`
>> Running: sift-config-tools
>> Running: sift-config
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
`

Then I have run faulty with the server mode and got similar error. 

This is the log : 
[saltstack.log](https://github.com/teamdfir/sift/files/4423208/saltstack.log)

Thank you in advance

**Comment by ekristen** [comment]
Looks like requests to get certain files are getting blocked and resulting in failure

```
    comment: "Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - Running scope as unit: run-re40283004bf2461089b5510c8257873f.scope\n      E:
      Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/e/ettercap/ettercap-common_0.8.2-10build4_amd64.deb
      \ 499  Request has been forbidden by antivirus [IP: 91.189.91.38 80]\n      E:
      Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"
```

**Comment by Kojuda** [comment]
Thank you, so it's really my antivirus ? I'll try to run without it

**Comment by Kojuda** [comment]
Hit by the most common error. Next, my first will be [Ctrl F] + "antivirus" in the log file.

Thank you very much for troubleshooting !
