### ISSUE TITLE
WSL Ubuntu 18.04 install

### ISSUE THREAD

**Issue by McFlip** [teamdfir/sift#455]
I tried installing the latest release in a fresh instance of Ubuntu 18.04 in Windows Subsystem for Linux. I initially tried installing in server mode but I also tried desktop mode and the pre-release.
```
 sudo sift install --mode=server
>> Running: sift-scripts
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
```
[saltstack.log](https://github.com/teamdfir/sift/files/4440429/saltstack.log)

**Comment by ekristen** [comment]
desktop mode won't work, pre-release is only going to work if there's a pre-release to install.

server mode is the only mode that'll work with WSL2.

It looks like there was a problem installing the powershell deb?

```
comment: "Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - dpkg: error processing archive /var/cache/sift/archives/powershell_6.2.0-1.ubuntu.18.04_amd64.deb
      (--install):\n       unable to stat './opt/microsoft/powershell/6/System.Management.Automation.dll'
      (which I was about to install): Permission denied\n      dpkg-deb (subprocess):
      decompressing archive member: internal gzip write error: Broken pipe\n      dpkg-deb
      (subprocess): cannot copy archive member from '/var/cache/sift/archives/powershell_6.2.0-1.ubuntu.18.04_amd64.deb'
      to decompressor pipe: failed to write (Broken pipe)\n      dpkg-deb: error:
      <decompress> subprocess returned error exit status 2\n      Errors were encountered
      while processing:\n       /var/cache/sift/archives/powershell_6.2.0-1.ubuntu.18.04_amd64.deb"
    duration: 8382.785
    name: sift-powershell
    result: false
    start_time: '14:49:40.878467'
  pkg_|-sift-python-m2crypto_|-pytho
```

**Comment by McFlip** [comment]
Thanks for the reply. McAfee host intrusion prevention tripped on the powershell dll and blocked dpkg. I didn't think that HIPS on the Windows Host would block something in the Linux machine, but I'm on an enterprise system that only has WSL1. So it's not using virtualization. 

For anyone else in the same boat here was my workaround:

1. On a machine without McAfee, installed WSL and set up an Ubuntu instance on an external drive using the manual unzip method [shown here](https://superuser.com/questions/1271682/is-there-a-way-of-installing-ubuntu-windows-subsystem-for-linux-on-win10-v170)
2. Installed SIFT in the external, drilled down the root filesystem `rootfs\opt\microsoft\powershell\6`, and deleted `System.Management.Automation.dll`.
3. Transfered the external back to the original machine and robocopied binarys over the original root file system (/xd is exclude dir) `robocopy /s $src $dst /xd boot cases dev etc home media mnt proc root run srv sys tmp`
4. Probably not necessary but I ran `sudo sift install --mode=server`

Powershell doesn't work but hopefully I won't need it. Hopefully it becomes a non issue for me when I enventually am able to use WSL2.
