### ISSUE TITLE
[CLI] Initial installation fails with "getaddrinfo ENOTFOUND api.github.com"

### ISSUE THREAD

**Issue by tobiashahn** [teamdfir/sift#457]
I'm trying to install sift on a freshly installed ubuntu 16.04 system. I am behind a proxy, and have set the proxy in the following places:
- Environment variables: http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY
- proxy_host & proxy_port in /etc/salt/minion as mentioned in [issue #236](https://github.com/teamdfir/sift/issues/236).

The installation fails with `getaddrinfo ENOTFOUND api.github.com`. However, `wget api.github.com` from the same console session does work. 

Are there any additional places where I need to configure the proxy?

```forensics@ubuntu:~$ sudo -E /usr/local/bin/sift install --mode=server --verbose
> sift-cli@1.8.5
> sift-version: notinstalled

> mode: server

getaddrinfo ENOTFOUND api.github.com
Error: getaddrinfo ENOTFOUND api.github.com
    at Object.sendError (/snapshot/sift-cli/node_modules/github/lib/index.js:798:13)
    at /snapshot/sift-cli/node_modules/github/lib/index.js:809:21
    at callCallback (/snapshot/sift-cli/node_modules/github/lib/index.js:685:9)
    at ClientRequest.<anonymous> (/snapshot/sift-cli/node_modules/github/lib/index.js:765:9)
    at ClientRequest.emit (events.js:196:13)
    at TLSSocket.socketErrorListener (_http_client.js:409:9)
    at TLSSocket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'

forensics@ubuntu:~$ sudo -E wget http://api.github.com
URL transformed to HTTPS due to an HSTS policy
--2020-04-08 02:41:02--  https://api.github.com/
Connecting to 57.20.4.150:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 2178 (2.1K) [application/json]
Saving to: ‘index.html.1’

index.html.1                          100%[=======================================================================>]   2.13K  --.-KB/s    in 0s

2020-04-08 02:41:02 (5.54 MB/s) - ‘index.html.1’ saved [2178/2178]
```

**Comment by tobiashahn** [comment]
Same issue is present on a freshly installed ubuntu 18.04 system.

**Comment by ekristen** [comment]
Unfortunately that's a DNS error. I assume you tried multiple times? ENOTFOUND means it was unable to do a DNS lookup on that hostname.

**Comment by tobiashahn** [comment]
I tried multiple times, the error is persistent. Resolving the same URL over wget/curl immediately after the failed installation does work. 

Since I'm behind a proxy, I assume that the proxy settings are not being passed to node?

**Comment by tobiashahn** [comment]
Any ideas what could be the cause here? Any pointers for additional debugging from my side?

**Comment by ekristen** [comment]
Unfortunately this indicates a networking problem on the VM, host, or network. Proxy settings are passed through to node, but that error generally means DNS, but something else could be going on.

How are the proxy settings being passed?

**Comment by tobiashahn** [comment]
I put the proxy information in the following places:

- Environment variables: http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY
- proxy_host & proxy_port in /etc/salt/minion as mentioned in issue #236.

`wget api.github.com` from the same console where the error is shown works, immediately after the error from node. Proxy does not need a user, the source network is white listed on the proxy for connetions without user credentials.

**Comment by ekristen** [comment]
That error specifically points to DNS. Proxy isn't specifically designed for or tested but many have had success. I understand other tooling works, but they also operate in a much different fashion. 

Is there any specific restrictions on DNS? Are you IPV6 only? IPv4? etc ..
