### ISSUE TITLE
[CLI] can't install SIFT 1.8.4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by PhV-80** [teamdfir/sift#458]
Hy there,
i'm trying to install SIFT, since yesterday.

 sift install
> sift-cli@1.8.4
> sift-version: notinstalled

> downloading v2020.2.1
>> downloading sift-saltstack-v2020.2.1.tar.gz.asc
>> downloading sift-saltstack-v2020.2.1.tar.gz.sha256
>> downloading sift-saltstack-v2020.2.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.2.1.tar.gz
> validating file sift-saltstack-v2020.2.1.tar.gz
> validating signature for sift-saltstack-v2020.2.1.tar.gz.sha256
> extracting update sift-saltstack-v2020.2.1.tar.gz
> performing update v2020.2.1
>> Log file: /var/cache/sift/cli/v2020.2.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

i tried, 'apt update' and 'apt autoremove' to solve this error

**Comment by PhV-80** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/4454702/saltstack.log)

**Comment by davidep** [comment]
I got the same issue by upgrading from saltstack sift-saltstack-v2020.2.1 to v2020.6.1-rc2 and I fixed it by running the following 
`pip install pyaff4==0.26.post6`
