### ISSUE TITLE
Unable to import the SIFT-Workstation.ovf

### ISSUE THREAD

**Issue by jeff-in-RTP** [teamdfir/sift#462]
I've been trying to import the ovf file all weekend with multiple downloads and with both VM Fusion and Virtual Box. I've verified the md5 and it is correct. I am running the latest version of both applications and version 10.14.6 of macOS.

From Fusion

![screenshot_174](https://user-images.githubusercontent.com/10101192/80931989-3f49e780-8d8b-11ea-87c6-54f48e8479d6.jpg)

From Virtual Box

![screenshot_175](https://user-images.githubusercontent.com/10101192/80932042-82a45600-8d8b-11ea-8613-dfcdec29ffb1.jpg)

I also tried manually installing on Ubuntu but the download is Ubuntu 20.04 LTS and it doesn't seem to be supported on it, for now.

**Comment by digitalsleuth** [comment]
@jeff-in-RTP There's a good chance that the OVF you're using is likely out of date anyways. However, if you're interested in quickly building your own VM, just spin up a basic, minimal Ubuntu 18.04.4 Desktop VM, run:
 `sudo apt update && sudo apt upgrade -y && sudo apt install open-vm-tools-desktop git curl`

After that, follow the steps at [https://github.com/teamdfir/sift-cli/releases/tag/v1.8.5](url) to install the cli and go from there. The cli install may take upwards of 30 minutes, but once installed, it's easy to maintain.

As a follow-up question, was the OVF the one you downloaded from the SIFT site [here](https://digital-forensics.sans.org/community/downloads)?

**Comment by itripc** [comment]
I download the ova file from the SIFT site you linked, it will not boot either says OS not found.

**Comment by digitalsleuth** [comment]
Can you provide more details? What virtualization software are you using, and what OS?

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by itripc** [comment]
Sure Im using Vmware 15 and Windows 10 Pro 64 bit, im just going install
the Ubuntu 16 and install with CLI because in hurry but just wanted to pass
the info along

**Comment by digitalsleuth** [comment]
You're actually better off installing Ubuntu 18 over 16, because plaso no long supports or builds their tools for 16.
If you do install with 16, you can likely expect a number of errors.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by itripc** [comment]
That is good to know, can I upgrade to 18 and plaso will work or I need to
do fresh 18 install?

**Comment by digitalsleuth** [comment]
Well, if you upgrade from 16 to 18 without installing the SIFT CLI, you should be fine. However, if you upgrade from 16 (with the CLI already installed) and upgrade to 18, you may have issues.

It’s not the option I’d recommend, however, if you were to do it, these are the steps I’d suggest:

First: In 16, sudo sift update and sudo sift upgrade
Second: Upgrade to Ubuntu 18
Third: Run ‘sudo cpan install HTML::QuickTable’ (only until the next release package drops)
Fourth: Download the newest sift cli and do a sudo sift update and sudo sift upgrade --pre-release

That should work for you. But again, I’d recommend doing a brand new Ubuntu 18.04 LTS installation, fully updated, then run sift install.

Cheers

**Comment by itripc** [comment]
Good to know I will have to do the 18 route later when I have time thanks.
