### ISSUE TITLE
Install Error - Win 10 WSL

### ISSUE THREAD

**Issue by haloforensics** [teamdfir/sift#463]
I'm trying to install SIFT on Win 10 WSL Ubuntu 18.04, but am receiving the following error in during the installation:

  virtualenv_|-rekall-virtualenv_|-/opt/rekall_|-managed:
    __run_num__: 249
    __sls__: sift.python-packages.rekall
    changes: {}
    comment: 'One or more requisite failed: sift.packages.python-virtualenv.python-virtualenv'
    duration: 0.388
    result: false
    start_time: '08:42:29.975827'

My system/sift specs are as follows:

Windows 10 (10.0.18363.778)
sift-cli v1.8.5
sift 2020.2.1 (attempting to install)

I've also attached the full saltstack log

Any assistance resolving this issue would be greatly appreciated.

Thanks!

[saltstack.log](https://github.com/teamdfir/sift/files/4580883/saltstack.log)

**Comment by ekristen** [comment]
Looks like we might be back to having rekall issues again. I'll look into it.

**Comment by ekristen** [comment]
Rekall installed fine in isolation, I'll have to do a larger set of testing later.

**Comment by digitalsleuth** [comment]
The log shows several failures in the installation. However, usually (from what I've seen) the 'rekall symlink' fails only because rekall already exists on the system. One temporary way around this is to do the following: `pip uninstall rekall -y && rm /usr/local/bin/rek*`
This will remove your existing rekall installation and should allow you to continue.

That being said, the remainder of the issues may or may not still exist. If you're willing, can you remove any existing rekall installation (using the commands above, with appropriate permissions as necessary), and try running the cli install again?

**Comment by digitalsleuth** [comment]
@haloforensics Are you still having this issue?

**Comment by haloforensics** [comment]
Thanks @digitalsleuth.  I have not had much time to play around with it, but will give your recommendations a shot as soon as possible.

**Comment by digitalsleuth** [comment]
@haloforensics Please let us know if you're still experiencing this issue. Also, you can now try updating to the new CLI and using the --pre-release argument to ensure you have the latest packages.

**Comment by Bostek** [comment]
Hello, I have also issue with installing SIFT-CLI on WSL2, tried on following version:
_Linux  4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux_

Having following error:

>sudo sift install
> sift-cli@1.8.5
> sift-version: notinstalled
>
> mode: desktop
> downloading v2020.7.1
>> downloading sift-saltstack-v2020.7.1.tar.gz.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz
> validating file sift-saltstack-v2020.7.1.tar.gz
> validating signature for sift-saltstack-v2020.7.1.tar.gz.sha256
> extracting update sift-saltstack-v2020.7.1.tar.gz
> performing update v2020.7.1
>> Log file: /var/cache/sift/cli/v2020.7.1/saltstack.log
>
>Update returned exit code not zero
>Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
>
>
 >----- PLEASE READ ----------------------
>
>A lot of failures are caused by the apt system being locked
>or unhealthy.
>
>Before opening an issue in GitHub, please check to see if
>your apt system is healthy.
>
>Try running 'apt-get update' then remove any packages that
>aren't used by running 'apt-get autoremove'

**Comment by ekristen** [comment]
With WSL you need to run in server mode to skip all UI related changes.

**Comment by Bostek** [comment]
> With WSL you need to run in server mode to skip all UI related changes.
> […](#)
> Sent from my iPhone
> On Sep 21, 2020, at 06:56, Bostek ***@***.***> wrote: ﻿ Hello, I have also issue with installing SIFT-CLI on WSL2, tried on following version: Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux Having following error: sudo sift install ***@***.*** sift-version: notinstalled mode: desktop downloading v2020.7.1 downloading sift-saltstack-v2020.7.1.tar.gz.asc downloading sift-saltstack-v2020.7.1.tar.gz.sha256 downloading sift-saltstack-v2020.7.1.tar.gz.sha256.asc downloading sift-saltstack-v2020.7.1.tar.gz validating file sift-saltstack-v2020.7.1.tar.gz validating signature for sift-saltstack-v2020.7.1.tar.gz.sha256 extracting update sift-saltstack-v2020.7.1.tar.gz performing update v2020.7.1 Log file: /var/cache/sift/cli/v2020.7.1/saltstack.log Update returned exit code not zero Error: Update returned exit code not zero at ChildProcess. (/snapshot/sift-cli/sift-cli.js:529:23) at ChildProcess.emit (events.js:196:13) at maybeClose (internal/child_process.js:1011:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5) ----- PLEASE READ ---------------------- A lot of failures are caused by the apt system being locked or unhealthy. Before opening an issue in GitHub, please check to see if your apt system is healthy. Try running 'apt-get update' then remove any packages that aren't used by running 'apt-get autoremove' — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, it worked. I didnt know that, back then I was installing it without any mode :)

**Comment by ekristen** [comment]
Great, glad it worked for you.
