### ISSUE TITLE
sift install stops - AWS ubuntu 18.04

### ISSUE THREAD

**Issue by fredski-github** [teamdfir/sift#464]
It is stopping during sift-config-tool. the log stops at the rekall package.

`apt-get update` and `apt-get upgrade` are both clean.

***AMI***
ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20200408 (ami-085925f297f89fce1)

***LOG FILE***
ubuntu@siftworkstation: ~
$ tail /var/cache/sift/cli/v2020.2.1/saltstack.log
  virtualenv_|-rekall-virtualenv_|-/opt/rekall_|-managed:
    __id__: rekall-virtualenv
    __run_num__: 248
    __sls__: sift.python-packages.rekall
    changes: {}
    comment: virtualenv exists
    duration: 4738.542
    name: /opt/rekall
    result: true
    start_time: '00:38:41.530461'

***ERROR***
>> Running: /usr/local/etc/foremost.conf
>> Running: sift-config-tools
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

**Comment by digitalsleuth** [comment]
@fredski-github Any chance you could post or upload your full saltstack.log? Unfortunately sometimes the errors are not at the bottom of the log, but further up. You can find the sections which have caused errors by searching for 'result: false' as well.

**Comment by fredski-github** [comment]
sure. i searched for you the entries matching 'result: false' and found four (4):

file_|-sift-server-version-file_|-/etc/sift-version_|-managed:
    __run_num__: 461
    __sls__: sift.server
    changes: {}
    comment: 'One or more requisite failed: sift.packages.sift-packages'
    duration: 0.015
    result: false
    start_time: '14:24:46.581580'

  pkg_|-sift-package-pdftk_|-pdftk_|-installed:
    __id__: sift-package-pdftk
    __run_num__: 144
    __sls__: sift.packages.pdftk_bionic
    changes: {}
    comment: "Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - Running scope as unit: run-r01bdb3c463ca4639b20c7f50ce0e4707.scope\n      E:
      Package 'pdftk' has no installation candidate"
    duration: 6845.796
    name: pdftk
    result: false

  test_|-sift-package-pdftk-distro_|-sift-package-pdftk-distro_|-nop:
    __run_num__: 145
    __sls__: sift.packages.pdftk
    changes: {}
    comment: 'One or more requisite failed: sift.packages.pdftk_bionic.sift-package-pdftk'
    duration: 0.016
    result: false
    start_time: '14:21:43.767229'

  test_|-sift-packages_|-sift-packages_|-nop:
    __run_num__: 224
    __sls__: sift.packages
    changes: {}
    comment: 'One or more requisite failed: sift.packages.pdftk.sift-package-pdftk-distro'
    duration: 0.034
    result: false
    start_time: '14:22:09.610901'


This is the last entry in the log:
  virtualenv_|-rekall-virtualenv_|-/opt/rekall_|-managed:
    __id__: rekall-virtualenv
    __run_num__: 248
    __sls__: sift.python-packages.rekall
    changes: {}
    comment: virtualenv exists
    duration: 5232.866
    name: /opt/rekall
    result: true
    start_time: '14:23:04.629179'


if you need anything else let me know.

**Comment by digitalsleuth** [comment]
@fredski-github Unfortunately this issue indicated in your saltstack.log is a result of pdftk now missing from the malteworld repo. You can try the following to remedy pdftk, then try the install again:
`wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/p/pdftk-java/pdftk-java_3.0.2-2_all.deb && sudo dpkg -i pdftk-java_3.0.2-2_all.deb`
Then, you should be able to do your sift install without issue.

I am aware that there are two newer versions of pdftk-java there (3.0.9 and 3.1.1) however they have not been tested at this time. Please let us know how this works out for you.

**Comment by fredski-github** [comment]
I did not try a clean install, but just installing pdftk did not resolve the issue. 

Is there a way to figure out what functionality is not available? It looks like most of the packages have installed correctly.

**Comment by digitalsleuth** [comment]
The only functionality that wouldn't be available would be those items that popped up with 'result: false' in your saltstack.log 
pdftk should be fixed soon, but in the meantime your install is likely complete (only missing the sift install of pdftk).

**Comment by reidaw** [comment]
I fixed the PDFTK issue after quite a bit of googling found this which seemed to install the required packages and result in a successful install.

wget http://launchpadlibrarian.net/340410966/libgcj17_6.4.0-8ubuntu1_amd64.deb \
 http://launchpadlibrarian.net/337429932/libgcj-common_6.4-3ubuntu1_all.deb \
 https://launchpad.net/ubuntu/+source/pdftk/2.02-4build1/+build/10581759/+files/pdftk_2.02-4build1_amd64.deb \
 https://launchpad.net/ubuntu/+source/pdftk/2.02-4build1/+build/10581759/+files/pdftk-dbg_2.02-4build1_amd64.deb
 sudo apt-get install ./libgcj17_6.4.0-8ubuntu1_amd64.deb \
    ./libgcj-common_6.4-3ubuntu1_all.deb \
    ./pdftk_2.02-4build1_amd64.deb \
    ./pdftk-dbg_2.02-4build1_amd64.deb -y

**Comment by digitalsleuth** [comment]
While that version of PDFTK does work, it is rather out of date. It is likely possible that the next time you do an update, you may have to remove that version prior. The next release should have the fixed pdftk in it and the errors you saw in the past should go away.

**Comment by ekristen** [comment]
Anything further here?

**Comment by digitalsleuth** [comment]
Not from me.

**Comment by fredski-github** [comment]
seemed to have worked.

ubuntu@siftworkstation: ~
$ sudo sift install
> sift-cli@1.8.5
> sift-version: v2020.2.1

> mode: desktop

**Comment by ekristen** [comment]
Nice @fredski-github thanks for the patience. We've been hitting a lot of weird scenarios lately.
