### ISSUE TITLE
OVA import issues on AWS

### ISSUE THREAD

**Issue by fredski-github** [teamdfir/sift#465]
the current OVA from https://digital-forensics.sans.org/community/download-sift-kit/3.0 imports fine on Mac OS X Fusion (it is Ubuntu 18.04.4) but fails on AWS. Tried us-east-1 and us-east-2.

{
    "ImportImageTasks": [
        {
            "Description": "SIFT Workstation OVA - Mon May 11 21:27:49 EDT 2020",
            "ImportTaskId": "import-ami-0000000000000",
            "SnapshotDetails": [
                {
                    "DiskImageSize": 5098160640.0,
                    "Format": "VMDK",
                    "Status": "completed",
                    "UserBucket": {
                        "S3Bucket": "-----------",
                        "S3Key": "SIFT-Workstation.ova"
                    }
                }
            ],
            "Status": "deleting",
            "StatusMessage": "ClientError: Unsupported kernel version 4.18.0-15-generic",
            "Tags": []
        }
    ]
}

**Comment by ekristen** [comment]
This is not a scenario we test or support. We are working on official AMI builds, they are not officially launched, but if you'd like to test the latest build `ami-0e18b3270d2ce667d` (us-west-2)
