### ISSUE TITLE
[SALTSTACK] - Unhealthy Instance Launch from AMI

### ISSUE THREAD

**Issue by jonanathan** [teamdfir/sift#469]
I was previously able to install SIFT, create an AMI via packer, and launch healthy instances. I have not made changes to my packer file but now the AMI is unable to launch healthy instances and fails the "Instance Status Checks".

Here are the contents of the sift.sh file that packer references:
```
sudo -- sh -c "apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y; apt-get autoclean -y
wget -O - https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
sudo echo "deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2018.3 bionic main" | sudo tee /etc/apt/sources.list.d/saltstack.list
sudo apt-get install salt-minion -y
sudo service salt-minion stop'
sudo git clone https://github.com/teamdfir/sift-saltstack.git /srv/salt
sudo salt-call -l info --local --file-root=/tmp/salt state.apply sift.pkgs
```
Has anything changed in the last ~2 months that might affect this? I cannot use the sift-cli because I was unable to create an AMI from the instance that would launch healthy instances. Packer solved this issue for me in the past but now it seems to have resurfaced.

**Comment by digitalsleuth** [comment]
@jonanathan The version of saltstack has changed to 2019.2, which may have affected some of the states. Try replacing 2018.3 in your sift.sh to 2019.2

**Comment by jonanathan** [comment]
Updating the version fixed the issue and I am able to do the install and launch healthy instances from the AMI.
