### ISSUE TITLE
Validate the signature for sift-cli-linux.sha256.asc

### ISSUE THREAD

**Issue by vanamaria** [teamdfir/sift#470]
I am trying to install sift in the Linux subsystem on Windows 10.
After I downloaded 
sift-cli-linux 
sift-cli-linux.sha256.asc 
and imported the PG P Key using the command
gpg --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 22598A94 
I can't validate the signature using the command 
gpg --verify sift-cli-linux.sha256.asc.
I have checked that all the files have been downloaded and I am running the command from the same directory.

Thanks in advance!

**Comment by ekristen** [comment]
What error are you getting? This is not 100% necessary, this is for those who want to verify the file hasn't been tampered with.
