### ISSUE TITLE
Error during Manual Install

### ISSUE THREAD

**Issue by sahoo8920** [teamdfir/sift#471]
Using an updated Ubuntu 16.04.06 VM.
Getting the following error during installation:
"Update Returned Exit code Not Zero"

See the attached image for the error. Please suggest.  
<img width="599" alt="Capture" src="https://user-images.githubusercontent.com/39708025/85380619-7ca74600-b580-11ea-9043-200d55593082.PNG">

**Comment by ekristen** [comment]
There is a log file that was referenced at the start of the run that will have further info.

**Comment by ekristen** [comment]
@sahoo8920 if you'd like help, please attach the log file.

**Comment by tompolth** [comment]
am having the same issue exactly but using ubuntu 18.14. I've also tried with the 16.04 before and same results.

Attached you'll find the log file.
[saltstack.log](https://github.com/teamdfir/sift/files/4993674/saltstack.log)

**Comment by ekristen** [comment]
Looks like unicode issues.

```
- "Rendering SLS 'base:sift.config.user.terminal_bionic' failed: while parsing a block
  mapping\n  in \"<unicode string>\", line 17, column 9\ndid not find expected key\n
  \ in \"<unicode string>\", line 17, column 112"
- "Rendering SLS 'base:sift.config.user.theme_bionic' failed: while parsing a block
  mapping\n  in \"<unicode string>\", line 24, column 9\ndid not find expected key\n
  \ in \"<unicode string>\", line 24, column 112"
```

What are your language settings?

**Comment by Asaph208** [comment]
I'm running into an install problem as well.. seems to fail at the same point in terminal but my log says it can't use pip. pip is installed and available, not sure what to do... I've been trying to troubleshoot this for two days now. Ubuntu 18.04.4, saltstack.log attached. 
[saltstack.log](https://github.com/teamdfir/sift/files/4997372/saltstack.log)

**Comment by ekristen** [comment]
@Asaph208 looks like your python might be broken. 18.04? Can you please provide `dpkg -l | grep python` output.

**Comment by Asaph208** [comment]
> @Asaph208 looks like your python might be broken. 18.04? Can you please provide `dpkg -l | grep python` output.

[python.txt](https://github.com/teamdfir/sift/files/4997403/python.txt)

**Comment by ekristen** [comment]
@Asaph208 when you run `python --version` what's the default?

**Comment by Asaph208** [comment]
> @Asaph208 when you run `python --version` what's the default?

2.7.17

**Comment by ekristen** [comment]
@Asaph208 it also looks like you are having apt problems. If you run `apt-get update` does it run successfully? Can you provide `ls of /etc/apt/sources.list.d` and then run `apt-cache showpkg libesedb`

**Comment by Asaph208** [comment]
> @Asaph208 it also looks like you are having apt problems. If you run `apt-get update` does it run successfully? Can you provide `ls of /etc/apt/sources.list.d` and then run `apt-cache showpkg libesedb`

$ ls /etc/apt/sources.list.d
docker.list
docker.list.distUpgrade
docker.list.save
gift-ubuntu-stable-xenial.list
gift-ubuntu-stable-xenial.list.distUpgrade
gift-ubuntu-stable-xenial.list.save
noobslab-ubuntu-icons-xenial.list
noobslab-ubuntu-icons-xenial.list.distUpgrade
noobslab-ubuntu-icons-xenial.list.save
noobslab-ubuntu-themes-xenial.list
noobslab-ubuntu-themes-xenial.list.distUpgrade
noobslab-ubuntu-themes-xenial.list.save
openjdk-r-ubuntu-ppa-xenial.list
openjdk-r-ubuntu-ppa-xenial.list.distUpgrade
saltstack.list
saltstack.list.distUpgrade
saltstack.list.save
sift-ubuntu-stable-xenial.list
sift-ubuntu-stable-xenial.list.distUpgrade
sift-ubuntu-stable-xenial.list.save

_____________________________

$ apt-cache showpkg libesedb
N: Unable to locate package libesedb

**Comment by ekristen** [comment]
`cat /etc/os-release`

**Comment by Asaph208** [comment]
> `cat /etc/os-release`

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by ekristen** [comment]
ok so this was an upgrade from 16.04, can you show me the contents of ` gift-ubuntu-stable-xenial.list` and ` sift-ubuntu-stable-xenial.list`

**Comment by Asaph208** [comment]
gift is empty

sift:
# deb http://ppa.launchpad.net/sift/stable/ubuntu bionic main # disabled on upgrade to bionic
# deb-src http://ppa.launchpad.net/sift/stable/ubuntu xenial main

**Comment by ekristen** [comment]
Remove 

```
gift-ubuntu-stable-xenial.list
gift-ubuntu-stable-xenial.list.distUpgrade
gift-ubuntu-stable-xenial.list.save
gift-ubuntu-stable-xenial.list
gift-ubuntu-stable-xenial.list.distUpgrade
gift-ubuntu-stable-xenial.list.save
```

Then try again.

**Comment by Asaph208** [comment]
Failed again in the same spot with the same reason (i think). Since this is an upgrade from 16, maybe I should just do a totally fresh 18 install and try again.

[secondsaltstack.log](https://github.com/teamdfir/sift/files/4997576/secondsaltstack.log)

**Comment by Asaph208** [comment]
I'm at a loss. I re-installed fresh from an Ubuntu 18 DVD I made, erased the whole hard drive and installed. I did the update/upgrade/autoremove trio, followed the directions for the CLI process and it still fails. There is a spot in the middle of the installation asking for a github username and password, am I correct in typing in my credentials here? Could that be the issue?

The failure this time is different, but is still obviously a failure. Attached are the saltstack logs.
[saltstack2.log](https://github.com/teamdfir/sift/files/4998009/saltstack2.log)

**Comment by ekristen** [comment]
use the `--pre-release` flag, we had to fix an issue with regripper and hadn't officially released the change.

does the gift and sift apt repo files now have the right data in them at least?

**Comment by tompolth** [comment]
am having the same issue exactly but using ubuntu 18.14. I've also tried with the 16.04 before and same results.

Attached you'll find the log file.

> Looks like unicode issues for you @tompolth
> 
> ```
> - "Rendering SLS 'base:sift.config.user.terminal_bionic' failed: while parsing a block
>   mapping\n  in \"<unicode string>\", line 17, column 9\ndid not find expected key\n
>   \ in \"<unicode string>\", line 17, column 112"
> - "Rendering SLS 'base:sift.config.user.theme_bionic' failed: while parsing a block
>   mapping\n  in \"<unicode string>\", line 24, column 9\ndid not find expected key\n
>   \ in \"<unicode string>\", line 24, column 112"
> ```
> 
> What are your language settings?

I am using spanish keyboard layout. In any case, I have changed it again to the english *US* again -layout and format- and then tried again. I get the same results.

**Comment by ekristen** [comment]
Does your username or home directory path use any utf-8 characters?

**Comment by Asaph208** [comment]
>sudo sift install  --pre-release

Was successful! Thank you very much for taking the time to troubleshoot this with me. Whatever change there was with the --pre-release option made the difference.

**Comment by tompolth** [comment]
> Does your username or home directory path use any utf-8 characters?

No, my username and home directory are siftforensics@siftWS

I used the same that the OVA virtual machine in order to avoid issues. But, obviously, I didnt manage , he, he

**Comment by digitalsleuth** [comment]
@tompolth Can you provide the output of the `locale` command and `salt-minion -V` ? The error you've provided regarding the unicode string is an error that previously popped up in 2018.3 and early versions of salt-minion 2019. 

Thanks

**Comment by tompolth** [comment]
Hi, 

The complete output is this:
![image](https://user-images.githubusercontent.com/11537311/89729142-19d81400-da33-11ea-8be1-dd1967365894.png)
I've seen that there is some complains about the installed Python's vesion (2.7) I don't if this has something to do with those errors.

Best

**Comment by digitalsleuth** [comment]
The Python 2.7 message is just informative, and doesn't actually generate an error in the saltstack process. Can you also send the output of the `locale` command?
One potential way to work around this is to install the 1.9.0-rc1cli, which uses salt-minion 3001. This is a python3-based salt installation which will get rid of the python2.7 warnings. However, I'd like to see the `locale` output before you try this. 

Cheers

**Comment by tompolth** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/11537311/89731642-e30cf880-da48-11ea-8240-633fbe17f4d2.png)

Thanks for your help

**Comment by digitalsleuth** [comment]
Can you try running `export LANGUAGE=en_US.UTF-8` and try running the cli installer again? It's possible the Unicode error is due to the language variable being empty. 

If that doesn't work, then we can try the sift RC1 cli.

**Comment by tompolth** [comment]
I've tried and I've got the same errors. 
I've also realize that during the apt update command I get this other warning related with salt:

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2 bionic InRelease' doesn't support architecture 'i386'

**Comment by digitalsleuth** [comment]
That apt warning doesn't actually have an effect on the installation, as it's just a warning. If you have already done the `export LANGUAGE` command, and the environment variable still shows as empty, then try preceding your sift cli command with it, like this: `LANGUAGE=en_US.UTF-8 sudo sift install --pre-release`

Even with your LANGUAGE env blank, this will force the command to run under this context. 

What version of the cli are you currently using? Perhaps the move to 1.9.0-rc1 might be better for you and should resolve this issue.

**Comment by tompolth** [comment]
I am using the 1.8.5 version. The same errors. I will try it with the 1.9.0-rc1

**Comment by digitalsleuth** [comment]
Could you provide a copy of your last saltstack.log? I'd like to see if there are any other indicators which may be causing the error. 

Thanks!

**Comment by tompolth** [comment]
Now, with the 1.9.0 version I have other errors :-(

_root@siftWS:/home/siftforensics# sift install --pre-release
> sift-cli@1.9.0-rc1
> sift-version: notinstalled

> mode: desktop
Installing and configuring SaltStack properly ...

Command failed: apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --allow-change-held-packages salt-minion
debconf: delaying package configuration, since apt-utils is not installed
E: Sub-process /usr/bin/dpkg returned an error code (2)

Error: Command failed: apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --allow-change-held-packages salt-minion
debconf: delaying package configuration, since apt-utils is not installed
E: Sub-process /usr/bin/dpkg returned an error code (2)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'_

**Comment by digitalsleuth** [comment]
That one's actually easy to fix. Try the following:
` sudo apt search salt-minion` and make note of the version. Should be 3001. If it is, then run:
`sudo apt install salt-minion salt-common -y`
Once that finishes, run the sift cli again, using the --pre-release option.

**Comment by tompolth** [comment]
Installed salt-minion. 
This is the saltstack.log in the last execution. Same issues

[saltstack.txt](https://github.com/teamdfir/sift/files/5047602/saltstack.txt)

**Comment by digitalsleuth** [comment]
Can you confirm that your `/home/siftforensics/` directory is owned by siftforensics:siftforensics recursively? Including the .dbus directory. 
I see this error just prior to the Unicode error, when it's trying to setup your terminal preferences:

`[DEBUG   ] env command: ('su', '-s', '/bin/bash', '-', 'siftforensics', '-c', '/usr/bin/python3')`
`# [DEBUG   ] stdout: dbus[19128]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/run/user/0" is owned by uid 0, not our uid 1000
unix:abstract=/tmp/dbus-LIrXEKq4NK,guid=428acc25931324ee47f640995f2ff940`
`# [DEBUG   ] output: dbus[19128]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/run/user/0" is owned by uid 0, not our uid 1000`

**Comment by digitalsleuth** [comment]
Looks like the cause of the Unicode error is due to an error message being returned in place of the expected DBUS_SESSION_BUS_ADDRESS and salt is trying to parse the error message. The message contains invalid/unexpected characters, and as such is throwing the Unicode error. Let me know if the permissions in your home directory are out of whack.

**Comment by tompolth** [comment]
mmm, yes probably is that. I don't know why but the .dbus directory is root owned

drwxr-xr-x 17 siftforensics siftforensics 4096 Aug  9 14:19 .
drwxr-xr-x  3 root          root          4096 Jul 29 09:33 ..
-rw-------  1 siftforensics siftforensics  271 Aug  9 13:58 .bash_history
-rw-r--r--  1 siftforensics siftforensics  220 Jul 29 09:33 .bash_logout
-rw-r--r--  1 siftforensics siftforensics 3771 Jul 29 09:33 .bashrc
drwx------ 14 siftforensics siftforensics 4096 Jul 30 19:55 .cache
drwx------ 13 siftforensics siftforensics 4096 Jul 29 10:37 .config
**drwx------  3 siftforensics root          4096 Jul 29 10:09 .dbus**
drwxr-xr-x  2 siftforensics siftforensics 4096 Aug  9 15:37 Desktop
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Documents
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 30 20:16 Downloads
-rw-r--r--  1 siftforensics siftforensics 8980 Jul 29 09:33 examples.desktop
drwx------  3 siftforensics siftforensics 4096 Jul 29 09:46 .gnupg
-rw-------  1 siftforensics siftforensics 3180 Aug  9 14:19 .ICEauthority
drwx------  3 siftforensics siftforensics 4096 Jul 29 09:46 .local
drwx------  5 siftforensics siftforensics 4096 Jul 29 10:05 .mozilla
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Music
-rw-r--r--  1 siftforensics siftforensics  310 Jul 30 08:36 .pam_environment
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Pictures
-rw-r--r--  1 siftforensics siftforensics  807 Jul 29 09:33 .profile
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Public
drwx------  2 siftforensics siftforensics 4096 Jul 29 09:46 .ssh
-rw-r--r--  1 siftforensics siftforensics    0 Jul 29 10:06 .sudo_as_admin_successful
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Templates
drwxr-xr-x  2 siftforensics siftforensics 4096 Jul 29 09:46 Videos

**Comment by tompolth** [comment]
Bingo!! That was!!

Now the sift install is working. Let's hope that is enough. Thanks a lot. 

In any case, I don't know why the .dbus directory was owned by root. 

Thank you very much.

**Comment by digitalsleuth** [comment]
This can happen for any number of reasons, but I have a few (unvalidated) reasons as to why it happened. 
Glad everything worked out for you!
