### ISSUE TITLE
RegRipper 2.8 Repository Not Found

### ISSUE THREAD

**Issue by modmagus** [teamdfir/sift#473]
During installation via "sift install", the user is prompted for github.com username/password for the RegRipper2.8 repository.

Screenshot of prompt as displayed during attempted installation on Ubuntu 18.04:
<img width="398" alt="Github Prompt 2020-07-23 102226" src="https://user-images.githubusercontent.com/29063156/88298298-fc831600-ccce-11ea-9f18-a86332875c49.png">

Screenshot of the section of the log file showing the underlying error condition.
<img width="396" alt="Log Error 2020-07-23 102321" src="https://user-images.githubusercontent.com/29063156/88298340-07d64180-cccf-11ea-98ee-a3bff9f5a0cd.png">

The repository appears to have been removed or marked as private by the maintainers. The current repository is https://github.com/keydet89/RegRipper3.0.git

**Comment by jasonalv** [comment]
Experiencing this problem as will

**Comment by ekristen** [comment]
Looks like there a new one. Will update and test ASAP

**Comment by ekristen** [comment]
2020.7.1-rc1 is out. You can install with `sift install --pre-release` or upgrade with `sift upgrade --pre-release`

**Comment by modmagus** [comment]
> 2020.7.1-rc1 is out. You can install with `sift install --pre-release` or upgrade with `sift upgrade --pre-release`

The pre-release installed with the updated repository without additional issue. Much appreciated
