### ISSUE TITLE
error on install ubunto 18.04 windows 10 creator(help)

### ISSUE THREAD

**Issue by WEELDBER** [teamdfir/sift#474]
![sift log file that creates error](https://user-images.githubusercontent.com/57105642/88478502-7d7c2080-cf0e-11ea-9e9e-84ab979168a4.jpg)
![sift error](https://user-images.githubusercontent.com/57105642/88478508-8b31a600-cf0e-11ea-919e-4143bb2f3a19.jpg)
![image](https://user-images.githubusercontent.com/57105642/88478527-b7e5bd80-cf0e-11ea-985c-5bbcb39e4f2d.png)

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'
log file

sansforensics@DESKTOP-1JE9BFE:~$ sudo sift install
> sift-cli@1.8.5
> sift-version: notinstalled

> mode: desktop
> downloading v2020.7.0
>> downloading sift-saltstack-v2020.7.0.tar.gz.asc
>> downloading sift-saltstack-v2020.7.0.tar.gz.sha256
>> downloading sift-saltstack-v2020.7.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.7.0.tar.gz
> validating file sift-saltstack-v2020.7.0.tar.gz
> validating signature for sift-saltstack-v2020.7.0.tar.gz.sha256
> extracting update sift-saltstack-v2020.7.0.tar.gz
> performing update v2020.7.0
>> Log file: /var/cache/sift/cli/v2020.7.0/saltstack.log

>> Running: software-properties-common
>> Running: apt-transport-https
>> Running: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
>> Running: sift-gift-dev

**Comment by ekristen** [comment]
Please attach the referenced saltstack.log
