### ISSUE TITLE
[SALTSTACK] - upgrading to release v2020.7.0 fails with multiple package requisite fails

### ISSUE THREAD

**Issue by tvfischer** [teamdfir/sift#475]
I've been trying to upgrade my SIFT vm by running the cli command `sift upgrade`

I am getting multiple package fails during the installation including
```
errors:
    - Running scope as unit run-r8f78f474745f455bb66cf9353944fc20.scope.
      E: Unable to locate package libfsapfs-tools
...
errors:
    - Running scope as unit run-r9bf47fa6b24b4775a4d5e1eb742a2a1f.scope.
      dpkg: regarding .../pdftk-java_3.1.1-1_all.deb containing pdftk-java:
       pdftk-java breaks pdftk (<< 2.02-5~)
        pdftk (version 2.02-4) is present and installed.
...
errors:
    - Running scope as unit run-rc2a02122d60b4719bab37b2326bf41c8.scope.
      E: Unable to locate package python3-plaso
...
# [ERROR   ] Command '[u'git', u'ls-remote', u'https://github.com/keydet89/RegRipper2.8.git']' failed with return code: 128
# [ERROR   ] stderr: remote: Repository not found.
```
I've tried the pre-release while that fixes the regripper issue, I am still getting the other package fails

Log  file
[saltstack.zip](https://github.com/teamdfir/sift/files/4995390/saltstack.zip)

**Comment by ekristen** [comment]
What version of ubuntu?

**Comment by ekristen** [comment]
This looks like for whatever reason the gift repo apt file is empty.

**Comment by tvfischer** [comment]
> What version of ubuntu?
16.04.6. LTS xenial

GIFT repo is not empty
![image](https://user-images.githubusercontent.com/439019/89018369-b30c7980-d313-11ea-9370-a63e9ff72a46.png)

Cheers

**Comment by ekristen** [comment]
GIFT not longer supports 16.04. You’ll need to upgrade to 18.04

We are working on 20.04 support right now

**Comment by tvfischer** [comment]
Hi @ekristen 
So I upgrade (started with a brand new VM image) to ubuntu 18.04 using the latest SIFT Workstation VM. This is a clean SIFT install as far as I can tell; no mods on my side.

When I run the sift upgrade command i am still getting errors; attaching the log file again.
[saltstack.zip](https://github.com/teamdfir/sift/files/5012010/saltstack.zip)
I can't make heads or tails of what the problems are. If I can make a suggestion is to maybe write out a specific error log or message at the end.

The report tells me to do the following:
```
----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'
```
Running the apt commands tells me everything is ok and nothing needs to be removed.

I noticed an additional things:
The script change the /etc/apt/sources.list.d/saltstack.list and removes the tag [arch=amd64]. Note sure why you are removing the arch tag in the script and how it affects a x64 based install.
```
NOTICE: Fixing incorrect Saltstack version configuration.
Installing and configuring Saltstack properly ...
```
This makes apt-get update/upgrade fail with the following error.

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2 bionic InRelease' doesn't support architecture 'i386'
```

**Comment by ekristen** [comment]
v2020.7.1 fixes this.

**Comment by tvfischer** [comment]
That was the test using v2020.7.1

**Comment by digitalsleuth** [comment]
@tvfischer In your most recent saltstack.log file, I noticed the only real error causing your final problem is a dbus error when configuring the terminal. This error can occur if the ~/.dbus directory is not owned by the user running the installer. Take a look at the permissions and ownership of the ~/.dbus directory for the intended user (in the log it identifies you're running this for the `sansforensics` user) and make sure it is recursively owned by that user with `chown -R <user>:<user> /home/<user>/.dbus`

Other than that, your recent SIFT installation did complete all of the remaining packages, so it should be a complete install. Please report back your results on this when you get the chance.

Cheers

**Comment by tvfischer** [comment]
Still failing on a stock SIFT Workstation VM.
Now I'm getting different errors but still unable to complete a proper clean update. Log file attached

This time it is complaining about not being able to find `pip` but this is installed by default in the SIFT VM.

[saltstack.zip](https://github.com/teamdfir/sift/files/5078483/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @tvfischer , I'm looking in the saltstack log and am not really seeing any errors. There was a problem with pydasm/libdasm, but that's the only apparent issue. Can you tell me what the final on-screen output was of this last attempt?
Also, it would be helpful if you could provide the output of `salt-minion -V` and `sudo sift version`, and the sift cli command you used (--pre-release or --user etc).

Thanks

**Comment by tvfischer** [comment]
Hi @digitalsleuth 

Command used: `sudo sift update`

**output for `sudo sift version`**: 
```
> sift-cli@1.8.5
> sift-version: v2020.7.1

> mode: desktop
```


**output for `salt-minion -V`**:
```
/usr/lib/python2.7/dist-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Jul 20 2020, 15:37:01)
   python-gnupg: 0.4.1
         PyYAML: 4.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

More on the errors:
```
>> Incomplete due to Failures -- Success: 561, Failure: 10

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: analyzemft
        SLS: sift.python-packages.analyzemft
        Run#: 227
        Comment: Error installing 'git+https://github.com/dkovar/analyzeMFT.git@64c71d7c8905a119b7abdf9813e6ef5f11d3ccf1': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: appcompatprocessor
        SLS: sift.python-packages.appcompatprocessor
        Run#: 228
        Comment: Error installing 'git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: argparse
        SLS: sift.python-packages.argparse
        Run#: 229
        Comment: Error installing 'argparse': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: bitstring
        SLS: sift.python-packages.bitstring
        Run#: 230
        Comment: Error installing 'bitstring': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 238
        Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 239
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: timesketch
        SLS: sift.python-packages.timesketch
        Run#: 259
        Comment: Error installing 'timesketch': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: dpapick
        SLS: sift.python-packages.dpapick
        Run#: 266
        Comment: Error installing 'dpapick': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: simplejson
        SLS: sift.python-packages.simplejson
        Run#: 269
        Comment: Error installing 'simplejson': Access denied to /usr/bin/pip, could not find a pip binary
      - ID: sift-python-volatility
        SLS: sift.python-packages.volatility_bionic
        Run#: 271
        Comment: Error installing 'git+https://github.com/volatilityfoundation/volatility.git@2.6.1': Access denied to /usr/bin/pip, could not find a pip binary
```

Yes pip is installed
```
sansforensics@siftworkstation: ~
$ pip2 -V
pip 20.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
sansforensics@siftworkstation: ~
$ pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
sansforensics@siftworkstation: ~
$ 
```

**Comment by digitalsleuth** [comment]
I figured it was installed, or you would have had a lot more than 10 errors :) 
Can you try running `sudo sift upgrade --pre-release` and see if you get the same errors?
Also, could you provide the output of the `which pip` and `which pip3` commands?

**Comment by tvfischer** [comment]
Ok these are the `which pip?`:
```
$ which pip
/usr/local/bin/pip
sansforensics@siftworkstation: ~
$ which pip3
/usr/bin/pip3
sansforensics@siftworkstation: ~
```
trying to upgrade to pre-release tells me there are none
```
$ sudo sift upgrade --pre-release
> sift-cli@1.8.5
> sift-version: v2020.7.1

> mode: desktop
No upgrades available
```

**Comment by ekristen** [comment]
https://github.com/teamdfir/sift-saltstack/releases/tag/v2020.10.2-rc1 has been released as pre-release, upgrade may or may not owkr. Unfortunately the deprecation of python2 has brought some challenge to everything. 

```
sudo sift upgrade --pre-release
```
