### ISSUE TITLE
sudo mv sift-cli-linux /usr/local/bin/sift error

### ISSUE THREAD

**Issue by chelch-cyber** [teamdfir/sift#476]
I am following the instructions for installing sift and attempting to install on the newest version of Unbuntu. When I get to the step....**sudo mv sift-cli-linux /usr/local/bin/sift** i get an error stating **mv: cannot stat 'sift-cli-linux': No such file or directory** . Curious if anyone else has run into this issue. Thanks.

**Comment by ekristen** [comment]
If you cannot move it, the file doesn't exist. Are you sure you downloaded it and are in the right path?

**Comment by chelch-cyber** [comment]
Think my issue was I was doing everything from the desktop. I made it to the install step but when I run sift-install i get a message stating "invalid OS, unable to determine ubuntu version".

**Comment by ekristen** [comment]
What version of Ubuntu?

**Comment by chelch-cyber** [comment]
20.04

**Comment by ekristen** [comment]
Not quite supported yet. Sorry.

**Comment by chelch-cyber** [comment]
No worries. Thanks for the assistance.

-Marcello
