### ISSUE TITLE
sift-cli not included in Sift Workstation appliance

### ISSUE THREAD

**Issue by angry-bender** [teamdfir/sift#477]
I have noticed that the sift-cli to update sift, is not presently included in the appliance.

Additionally, when running the update at present it throws the following error

sansforensics@siftworkstation: ~
$ sudo sift update
> sift-cli@1.9.0-rc1 **(Note, Also tried the same with the current stable release, v1.8.5)**
> sift-version: v2020.2.0

> mode: desktop
> downloading v2020.2.0
>> downloading sift-saltstack-v2020.2.0.tar.gz.asc
>> downloading sift-saltstack-v2020.2.0.tar.gz.sha256
>> downloading sift-saltstack-v2020.2.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.2.0.tar.gz
> validating file sift-saltstack-v2020.2.0.tar.gz

Hashes for sift-saltstack-v2020.2.0.tar.gz do not match. Expected: , Actual: b6c7fa985070fa6c7749893913de6319490ecd02c90479171f4162d0d716a650  /tmp/sift-saltstack-v2020.2.0.tar.gz

Error: Hashes for sift-saltstack-v2020.2.0.tar.gz do not match. Expected: , Actual: b6c7fa985070fa6c7749893913de6319490ecd02c90479171f4162d0d716a650  /tmp/sift-saltstack-v2020.2.0.tar.gz

    at validateFile (/snapshot/sift-cli/sift-cli.js:400:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:467:3)
    at async run (/snapshot/sift-cli/sift-cli.js:706:5)
    at async main (/snapshot/sift-cli/sift-cli.js:761:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**I managed to get it working by using the pre-release update**

$ sudo sift upgrade --pre-release
> sift-cli@1.9.0-rc1
> sift-version: v2020.2.0

> mode: desktop
> downloading v2020.7.1
>> downloading sift-saltstack-v2020.7.1.tar.gz.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz
> validating file sift-saltstack-v2020.7.1.tar.gz
> validating signature for sift-saltstack-v2020.7.1.tar.gz.sha256
> extracting update sift-saltstack-v2020.7.1.tar.gz

**Comment by ekristen** [comment]
Thanks for pointing this out, will verify for the next build we publish.
