### ISSUE TITLE
Feature Request - ZSH with autosuggestions

### ISSUE THREAD

**Issue by angry-bender** [teamdfir/sift#478]
Is it possible to request ZSH with autosuggestions & Syntax highlighting (Something like .oh-my-zsh) into SIFT? making the terminal a little easier for newbie analysts?

https://github.com/zsh-users/zsh-autosuggestions 
https://github.com/zsh-users/zsh-syntax-highlighting.git

I'd be happy to give it a go and push to salt stack, once I can see how it works if its a good suggestion.

**Comment by ekristen** [comment]
Shells are extremely personal preference. We've gone down this road before and we are unlikely to change the default shell.

**Comment by angry-bender** [comment]
No worries, thank you.
