### ISSUE TITLE
Invalid credentials downloading VM appliance

### ISSUE THREAD

**Issue by artimis36d** [teamdfir/sift#479]
I wish to download the VM appliance from your official website, but using the credentials posted on the download page, I got an error "Please fix the following problem(s) - Invalid credentials" on the login page.  Is there an update on the credentials?  Thanks.
![image](https://user-images.githubusercontent.com/5388398/89985043-f9b38980-dcac-11ea-8847-f2aa4188fe3c.png)

**Comment by kkttc** [comment]
Hi, the credentials being requested are your SANS account, which can be created at sans.org.

The credentials listed on the page are to login to the VM once you boot it up

Ken Kleiner
Pr. Security Engineer
UMass Lowell
(978) 934 3645


________________________________

**Comment by ekristen** [comment]
Thanks @kkttc
