### ISSUE TITLE
SIFT detailed package listing link is broken

### ISSUE THREAD

**Issue by honorthecode** [teamdfir/sift#480]
I'm trying to get a listing of software installed on the SIFT but the detailed package listing link is broken.
![image](https://user-images.githubusercontent.com/69635449/90139861-e81ec000-dd46-11ea-8d9e-9a07ac2c4e86.png)

Does anyone know where I can find that information?

**Comment by digitalsleuth** [comment]
The documentation hasn't been updated yet, but if you're in a pinch to find this information, you can find it in the [sift-saltstack](https://github.com/teamdfir/sift-saltstack) repo. All of the state files there are used to create the SIFT environment, and instantiated using the sift-cli. 
Currently, the quickest and easiest way to get a list like the one above is to clone the repo, cd into it, and run the following:

`find . -iname '*.sls' | egrep -v 'init|server.sls|vm.sls|\/repos|pkgs.sls|desktop.sls|\/config|\/tests|xenial|bionic|absent' | awk -F/ '{print $4}' | sed 's/.sls//g' | sort`

That will provide you with an alphabetical list of all of the tools, packages, and scripts installed using the cli. Keep in mind, though, that other packages may be installed as requirements from the subsequent repos from which some of these tools are installed. That means this list is not necessarily 100% complete.

To save you a little trouble, I've done this already and am attaching the current list (as of right now). This is subject to change when new software is added, or if some is removed. Hope this helps.

[sift_cli_installed_tools.txt](https://github.com/teamdfir/sift/files/5078861/sift_cli_installed_tools.txt)

**Comment by honorthecode** [comment]
This is excellent. Thank you for the list @digitalsleuth !
