### ISSUE TITLE
SIFT-VM Workaround for Clean Install Issues

### ISSUE THREAD

**Issue by digitalsleuth** [teamdfir/sift#481]
As of late, there have been a few users utilizing the VM provided on the SANS website to create their SIFT workstation. Running the steps below immediately after launching the VM should mitigate those issues until such time as the VM is updated.

**NOTE: These are only for a brand-new fresh SIFT VM, not for a VM which has already been modified:**

```
mkdir .cpan
mkdir .dbus
sudo sed 's/2018.3/2019.2/g' -i /etc/apt/sources.list.d/saltstack.list
sudo apt update && sudo apt upgrade -y
sudo apt upgrade -y salt-minion salt-common --allow-change-held-packages
sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/releases/download/v1.8.5/sift-cli-linux
sudo chmod +x /usr/local/bin/sift
sudo sift upgrade --pre-release
```
The saltstack.list bundled with the VM is for 2018.3, which no longer exists as a saltstack repo, and will cause an apt update error preventing an upgrade. Additionally, the sift-cli v1.8.5 uses 2019.2 as a base for the installer. Additionally, during the sift-cli install, the .cpan and .dbus directories unintentionally become improperly owned by root, which will cause future sift-cli updates.
Since the .cpan and .dbus directories don't exist at this time in the fresh VM, creating them doesn't cause any conflicts.

Finally, the `sudo apt upgrade -y salt-minion salt-common --allow-change-held-package` must be run separately, because the salt-common and salt-minion do not get upgraded with the `sudo apt upgrade -y` command/

This should mitigate any future errors with the VM until updates are made to the VM and corrections are made to the salt-states to fix the permissions. I'll be working on a pull request for the permissions later today/tomorrow.

Cheers

**Comment by ekristen** [comment]
I think we probably just need to loosen the reigns and just allow latest to be set at all times, it would prevent this in the future, but could become problematic. 

We are trying to get better about updating the VM on the website to.

**Comment by crowface28** [comment]
change the curl to https://github.com/teamdfir/sift-cli/releases/download/v1.8.5/sift-cli-linux

**Comment by ekristen** [comment]
There's a newer version available now https://github.com/teamdfir/sift-cli/releases/tag/v1.9.0-rc4
