### ISSUE TITLE
[CLI] Saltstack ENV variable not applying correctly

### ISSUE THREAD

**Issue by angry-bender** [teamdfir/sift#482]
sift-cli@1.9.0-rc1
    sift-version: v2020.2.0

    Command failed: apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --allow-change-held-packages salt-minion
    debconf: delaying package configuration since apt-utils is not installed
    E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by angry-bender** [comment]
Made fix on sift-cli, Pull Request https://github.com/teamdfir/sift-cli/pull/47

**Comment by ekristen** [comment]
> debconf: delaying package configuration since apt-utils is not installed

IIRC This can be ignored

There is likely something wrong with the underlying dpkg system ... try `sudo dpkg --configure -a`

**Comment by angry-bender** [comment]
Not quite, the main reason its occuring is because it's trying to do it through the apt-utils, however, you can see under the env codes below, the intent is to run this through dpkg, which avoids having to use the apt-utils, which can case more output. By using the env var at run time, it appears to fix this issue, and the salt-minion installs correctly.

Additionally, setting as an ENV variable, might cause unexpected behavior later on

**Comment by angry-bender** [comment]
Re-opened with correct .js code correction

**Comment by dsmackie** [comment]
I believe the associated pull request will fix https://github.com/teamdfir/sift/issues/481 also.
