### ISSUE TITLE
Cannot access SIFT VM appliance over network with RDP and xRDP

### ISSUE THREAD

**Issue by Katrina-Prescott** [teamdfir/sift#484]
The company I work for has installed a SIFT workstation on our network via the .ova file.  I have the computer name and IP address for it.  I am trying to figure out how to access it from my windows vm workstation.  I installed putty and was able to get to the command line and install xrdp using sudo apt install xrdp.  I can get to the xrdp login page using rdp.  But I cannot get to the sift workstation desktop.  Any suggestions?

**Comment by ekristen** [comment]
@Katrina-Prescott I'm sorry this is probably not the best forum for this sort of question. Unfortunately I'm not familiar with xrdp. If you are able to access via SSH, then you should be able to access with other protocols. Feel free to response back, but for now I'm going to close this out.
