### ISSUE TITLE
Non-interactive install of 1.9.0-rc1 fails on salt-minion

### ISSUE THREAD

**Issue by dominikborkowski** [teamdfir/sift#485]
Hello,

We're installing SIFT via a non-interactive method using Hashicorp's Packer on Ubuntu 18.04. Version 1.8.5 doesn't have any problems at this particular stage, while 1.9.0-rc1 fails with the following: 

```
     amazon-ebs: > sift-cli@1.9.0-rc1
     amazon-ebs: > sift-version: notinstalled
     amazon-ebs:
     amazon-ebs: > mode: desktop
     amazon-ebs: Installing and configuring SaltStack properly ...
     amazon-ebs:
     amazon-ebs: Command failed: apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --allow-change-held-packages salt-minion
     amazon-ebs: debconf: delaying package configuration, since apt-utils is not installed
     amazon-ebs: E: Sub-process /usr/bin/dpkg returned an error code (2)
     amazon-ebs:
     amazon-ebs: Error: Command failed: apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --allow-change-held-packages salt-minion
     amazon-ebs: debconf: delaying package configuration, since apt-utils is not installed
     amazon-ebs: E: Sub-process /usr/bin/dpkg returned an error code (2)
     amazon-ebs:
     amazon-ebs:     at ChildProcess.exithandler (child_process.js:303:12)
     amazon-ebs:     at ChildProcess.emit (events.js:315:20)
     amazon-ebs:     at maybeClose (internal/child_process.js:1021:16)
     amazon-ebs:     at Socket.<anonymous> (internal/child_process.js:443:11)
     amazon-ebs:     at Socket.emit (events.js:315:20)
     amazon-ebs:     at Pipe.<anonymous> (net.js:674:12)
     amazon-ebs:
     amazon-ebs:
     amazon-ebs: ----- PLEASE READ ----------------------
     amazon-ebs:
     amazon-ebs: A lot of failures are caused by the apt system being locked
     amazon-ebs: or unhealthy.
     amazon-ebs:
     amazon-ebs: Before opening an issue in GitHub, please check to see if
     amazon-ebs: your apt system is healthy.
     amazon-ebs:
     amazon-ebs: Try running 'apt-get update' then remove any packages that
     amazon-ebs: aren't used by running 'apt-get autoremove'
     amazon-ebs:
```

`apt-utils` is installed, and installing salt repository along with salt-minion outside of `sift` installer allows the installer to proceed. 

Cheers!

**Comment by ekristen** [comment]
We build an AMI but haven’t published it widely. I can supply those to you.

I’m also getting ready to publish all my packer scripts in the next week or two.

With packer I use salt stack directly and skip using sift CLI.

**Comment by dominikborkowski** [comment]
Holy smokes, that would help us tremendously. I've been fighting with sift CLI all day, and that doesn't account for half of the effort our team spent on it. One of our biggest challenges is that the build environment is behind a web proxy, and that SIFT CLI just does not appear to support that at all. 

Of course, our hope is to remain close to the upstream, so I'm interested in how you solved it on with your salt stack. 

Thank you!

**Comment by ekristen** [comment]
Well if you are in AWS you can just use the prebuilt AMI. No need to build yourself, 

I can get you the AMIs in a bit.

**Comment by ekristen** [comment]
@dominikborkowski check out https://github.com/teamdfir/sift-packer

**Comment by ekristen** [comment]
New version of the CLI -- https://github.com/teamdfir/sift-cli/releases/tag/v1.9.0-rc4 -- but the packer scripts is the best option.
