### ISSUE TITLE
Installer fails without gnome components

### ISSUE THREAD

**Issue by dominikborkowski** [teamdfir/sift#486]
The sift-config-tools portion of the install process will fail if certain GNOME components are not present. This has been tested on Ubuntu 16.04. The packages required include 'gnome-shell' and 'gnome-shell-extension-dashtodock'. Ideally if they're required, they may need to be pulled by salt. Otherwise, is there a document showing required core components?

Thanks!

Here's relevant output:

```
     amazon-ebs: >> Running: /usr/local/etc/foremost.conf
     amazon-ebs: >> Running: sift-config-tools
     amazon-ebs: Update returned exit code not zero
     amazon-ebs: Error: Update returned exit code not zero
     amazon-ebs:     at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:545:23)
     amazon-ebs:     at ChildProcess.emit (events.js:315:20)
     amazon-ebs:     at maybeClose (internal/child_process.js:1021:16)
     amazon-ebs:     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
     amazon-ebs:
     amazon-ebs:
     amazon-ebs: ----- PLEASE READ ----------------------
     amazon-ebs:
     amazon-ebs: A lot of failures are caused by the apt system being locked
     amazon-ebs: or unhealthy.
     amazon-ebs:
     amazon-ebs: Before opening an issue in GitHub, please check to see if
     amazon-ebs: your apt system is healthy.
     amazon-ebs:
     amazon-ebs: Try running 'apt-get update' then remove any packages that
     amazon-ebs: aren't used by running 'apt-get autoremove'
     amazon-ebs:
```

```
# [ERROR   ] Command 'gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop']"' failed with return code: 1
# [ERROR   ] stderr: No such schema ?org.gnome.shell?
# [ERROR   ] retcode: 1
```

**Comment by ekristen** [comment]
16.04 support is being dropped, 18.04 is supported and 20.04 is in the works

**Comment by dominikborkowski** [comment]
Sorry, it was a typo. The system in question is vanilla 18.04 with all the relevant updates.

**Comment by ekristen** [comment]
Interesting. I have not seen this behavior.

**Comment by dominikborkowski** [comment]
Our default approach is to use XFCE with ubuntu, and remove gnome components. That's likely why we've ran into these issues. Removing those two packages in question should reproduce the problem.

**Comment by ekristen** [comment]
Ah. Yeah gnome is the only official supported option. There are just too many variations to support otherwise.

If you don’t care about user and ui preferences you can simple install if using server mode. This just installs all tools and packages and the like with no user customizations. 

Erik

**Comment by ekristen** [comment]
If you'd like to continue talking about this let me know, but for now I'm going to close this.
