### ISSUE TITLE
Workstation is not installed with net-tools

### ISSUE THREAD

**Issue by TrustZero** [teamdfir/sift#488]
As seen in the screen shot the ifconfig command is not available. After going through the steps to install net-tools the command is available but shouldn't this be a part of the default settings? 

![2020-09-04 10_44_56-Window](https://user-images.githubusercontent.com/64290382/92258003-c58e4b80-ee9b-11ea-9c48-6e82659a4bd0.png)

**Comment by ekristen** [comment]
How did you come by this VM? OVA? Self Install?

**Comment by Zan0101** [comment]
Hi i get the same issue as well. How did you resolve it?

**Comment by ekristen** [comment]
You can install net tools via apt, but we’ve added it to the build process the next version will have it
