### ISSUE TITLE
SIFT OVA Apt-Get Update Not working

### ISSUE THREAD

**Issue by NAngryPole** [teamdfir/sift#489]
Cannot update the OVA of the SIFT workstation 18.04.5

I turned off Ubuntu auto update from ticket #467 

I came across this when trying to install iptables-persistent and it was not able to resolve the archive site. I statically set the DNS servers to Google DNS and still same result. Removed the NIC from vm in workstation and readded. Set NIC to DHCP. Reconfigured static IP in Network manager and set DNS there as well and still cannot use apt-get update.

Ran apt-get clean and it runs but same issue.

Any help would be appreciated,

**Comment by ekristen** [comment]
What error are you getting?

**Comment by NAngryPole** [comment]
sits at 0% when connecting to the archive.ubuntu , security. 


Then errors on could not resolve;
security.ubuntu.com
archive.ubuntu.com
ppa.launchpad.net
us.archive.ubuntu.com
repo.saltstack.com

Some index files failed to download, They have been ignored, or old ones used instead.

**Comment by ekristen** [comment]
What virtualization platform and version are you using? Seems like a bad configuration of some sort.

**Comment by NAngryPole** [comment]
Workstation pro 15. It must be, I believe setting a static IP via ifconfig screwed things up. I spun up a new OVA and all is seems fine. Sorry to waste your time.

**Comment by ekristen** [comment]
@NAngryPole no worries. Glad it's all working now.
