### ISSUE TITLE
error in upgrading 

### ISSUE THREAD

**Issue by naderhabbbab** [teamdfir/sift#492]
[saltstack.log](https://github.com/teamdfir/sift/files/5358652/saltstack.log)
i'v attached the log it regenerated

**Comment by ekristen** [comment]
`cat /etc/os-version` and what command did you run to upgrade?

**Comment by naderhabbbab** [comment]
this is the output 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$ sift -v
Version: 1.9.2 

i ran sudo sift upgrade 


please note that i upgrade my ubuntu on windows  from 16.4 to 18.04 the remove sift and add the new one sift 1.9.2

**Comment by ekristen** [comment]
A new version has been released since you opened this, please try it, if you still have issues please comment back on this issue.

**Comment by naderhabbbab** [comment]
thank you it s worked
