### ISSUE TITLE
log2timeline missing/broken in Ubuntu 18.04 

### ISSUE THREAD

**Issue by Darth-Leshioius** [teamdfir/sift#493]
Log2timeline wrapper for Plaso seems either non-existent or broken when building with Ubuntu 18.04 LTS 

This means that instructions/syntax in SIFT cheatsheet don't work as advertised.

Please advise.

**Comment by ekristen** [comment]
How are you making this asserting? Please share commands run.

**Comment by ekristen** [comment]
@Darth-Leshioius a lot of time it's hard to reproduce this sorta thing without more info, in this case I was able to verify.  It looks like somewhere along the line the requirement to install the CLI tool was removed or refactored away. 

For now you can add it by running `sudo apt-get install plaso-tools` I've already fixed our builds scripts going forward.
