### ISSUE TITLE
SIFT Workstation VM based on Ubuntu 18.04 on SIFT VM Download Page. 

### ISSUE THREAD

**Issue by sahoo8920** [teamdfir/sift#495]
Will the SANS Sift Workstation VM Download page make available a SIFT VM based on Ubuntu 18.04 once the Ubuntu 16.04 is no longer supported ?
I know we can manually install it on Ubuntu 18.04, just wanted to know about it. 

Thanks.

**Comment by ekristen** [comment]
Actually 20.04 will be the next. We are vetting it now.

**Comment by sahoo8920** [comment]
https://digital-forensics.sans.org/community/downloads
The link never updated with the 18.04 VM, it still linked the 16.04, that is why asked. Thanks for the update.
