### ISSUE TITLE
[SALTSTACK] - step 4 errors out

### ISSUE THREAD

**Issue by jklipsch** [teamdfir/sift#496]
Hi All,

Noob here and for the life of me I can't get Rekall to work on Ubuntu 18.04 due to SaltStack errors. In following the install directions of the latest release, step 4 gives the following errors. If anyone can make me smart or share a fix, that would be greatly appreciated.

sansforensics@siftworkstation: ~/Desktop
$ sudo apt-get install salt-minion
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 3000.3+ds-1) but 2018.3.4+ds-1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

Thanks in advance

**Comment by ekristen** [comment]
Rekall is being removed and no longer supported in SIFT. The project isn’t really maintained anymore.

**Comment by jklipsch** [comment]
Thank, Erik for the quick response. What's trending right now? Volatility?

**Comment by ekristen** [comment]
Volatility I believe is the only other viable option right now.
