### ISSUE TITLE
SIFT Workstation has limited tools after installation from .ova

### ISSUE THREAD

**Issue by ae61195p** [teamdfir/sift#497]
- Installation went okay, no issues. Looking at the applications available, there are only a handful installed. There are 54 installed apps including the normal system apps and programs.

**Comment by ekristen** [comment]
How are you reaching this assertion? List? What tool are looking for that isn't there?

**Comment by dralbundy** [comment]
By clicking 'Show Applications' in the bottom left in the VM. The ones that should be there based on the SIFT workstation download page aren't there. None of the tools listed below are there.

Software Includes:

log2timeline (Timeline Generation Tool)
Rekall Framework (Memory Analysis)
Volatility Framework (Memory Analysis)
3rd Party Volatility Plugins
bulk_extractor
autopsy
afflib
afflib-tools
ClamAV
dc3dd
imagemounter
libbde
libesedb
libevt
libevtx
libewf
libewf-tools
libewf-python
libfvde
libvshadow
lightgrep
log2timeline
Plaso
Qemu
regripper and plugins
SleuthKit
100s more tools -> See Detailed Package Listing

**Comment by ekristen** [comment]
They won’t show there. Most tools are CLI based.
