### ISSUE TITLE
sift-cli install fail on fresh Ubuntu 18.04.5 LTS install

### ISSUE THREAD

**Issue by rib0u** [teamdfir/sift#498]
Hi,

Trying to install SIFT on a fresh Ubuntu 18.04.5 LTS install, and it fail with error bellow :

--------------------------
sift install
> sift-cli@1.9.2
> sift-version: notinstalled

> mode: desktop
> downloading v2020.7.1
>> downloading sift-saltstack-v2020.7.1.tar.gz.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256
>> downloading sift-saltstack-v2020.7.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.7.1.tar.gz
> validating file sift-saltstack-v2020.7.1.tar.gz
> validating signature for sift-saltstack-v2020.7.1.tar.gz.sha256
> extracting update sift-saltstack-v2020.7.1.tar.gz
> performing update v2020.7.1
>> Log file: /var/cache/sift/cli/v2020.7.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

--------------------------

Obviously, apt-get update and apt-get remove didn't help.

Here is log file : [saltstack.log](https://github.com/teamdfir/sift/files/5520513/saltstack.log)

Thank you !

**Comment by ekristen** [comment]
Looks like a unicode error. Anything special about your install?

**Comment by rib0u** [comment]
Hi,

Not that i could think of accept my language settings. i did again a fresh install using US based locale, and i ran into same issue.
---
root@SIFT:/home/fifou/Downloads# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
------
[saltstack.log](https://github.com/teamdfir/sift/files/5522588/saltstack.log)

Thank you.

**Comment by rib0u** [comment]
Hi,
I was reviewing saltstack.log, and something caught my attention :
      - DBUS_SESSION_BUS_ADDRESS: "dbus[4810]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/run/user/0" **is owned by uid 0, not our uid 1000**
unix:abstract=/tmp/dbus-Cb8g9OrHOb,guid=49eb6c0a5e9de7905b1086515fab9460"

Instead of running "sift install" as root, i ran it as my normal user using "sudo sift install", and actually works, at least install seems to be running right now :-|

I'll confirm once done, and try to reproduce.

**Comment by rib0u** [comment]
Hi,

Confirmed solved. sift install should be ran with sudo, not as root itself.

Thanks you.
