### ISSUE TITLE
Error: Update returned exit code not zero

### ISSUE THREAD

**Issue by gra55h0pp3r** [teamdfir/sift#499]
I have attempted to install sift on version 18.04.04 LTS and 18.04.05 LTS and both get the following error message. I even tried installing sift in server mode 'sift install --mode:server'.

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Below is the Ubuntu release that I am currently trying to install sift on.

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

I have tried multiple times to run the 'sift install' with no luck in getting it to fully complete. I understand each package is separate and installed, so curious as to why I keep getting the error message. I searched the saltstack.log for 'result: false' and attached is the output for the 5 lines before and after.

[results_false.txt](https://github.com/teamdfir/sift/files/5649754/results_false.txt)

**Comment by GuardianCosmos** [comment]
@gra55h0pp3r see issue #498 
Sounds like the same problem and is the result of running as root instead of running as the user with sudo

**Comment by gra55h0pp3r** [comment]
I initially ran the install as root, but then rebuilt the VM and ran everything as sudo. The results and error are from running the install as sudo and not root. I will build a new VM and will try install SIFT again.

**Comment by digitalsleuth** [comment]
@gra55h0pp3r Are you still having this issue? If so, can you attach your full saltstack log as well?

**Comment by gra55h0pp3r** [comment]
@digitalsleuth 

You can close this ticket. I re-installed Ubuntu 18.04.5 and ran the install command without any errors this time.

Thanks.
