### ISSUE TITLE
Add accessibility tools to base SIFT VM

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#500]
To support upcoming accessibility requirements, please ensure the following are installed on the base public SIFT VM.  I've verified the commands below on the 18.04 VM.

- Magnus: On-screen magnification tool
  - https://snapcraft.io/magnus
  - `sudo snap install magnus`
- Onboard: Alternative input option for motor accessibility
  - `sudo apt-get install onboard`
- Orca: Text-to-speech tool for audible system navigation
  - This was already installed via apt-get on the 18.04 version

**Comment by ekristen** [comment]
So snaps are terrible. I suggest we avoid as long as possible. I’ll see if we can install it another way.

**Comment by philhagen** [comment]
No worries at all!  I didn't mean to specify that as a solution, just something that WFM.

**Comment by ekristen** [comment]
No worries! Just sharing knowledge. I’ll get it installed however we can.

**Comment by gnittala** [comment]
Trying to understand how this is going to be done; will these get added as salt packages so that they are pulled and installed as part of `sift install`.

Thank You

**Comment by ekristen** [comment]
Correct. Look for them in the next couple of weeks.
