### ISSUE TITLE
Volatilty

### ISSUE THREAD

**Issue by gunner4361** [teamdfir/sift#502]
Lots of errors on a fresh install of sift

Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.community.JeffBryner.twitter (ImportError: No module named lxml.html)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
You need to install pycoin for this plugin to run [pip install pycoin]
*** Failed to import volatility.plugins.community.itayk.antianalysis (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.community.DimaPshoul.callstacks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.community.FrancescoPicasso.mimikatz (ImportError: No module named construct)
*** Failed to import volatility.plugins.community.TranVienHa.osint (ImportError: No module named socks)
*** Failed to import volatility.plugins.community.TakahiroHaruyama.openioc_scan (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.community.itayk.apifinder (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.community.DaveLasalle.apihooksdeep (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.community.JeffBryner.facebook (ImportError: No module named lxml.html)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.community.DimaPshoul.malthfind (NameError: name 'distorm3' is not defined)

**Comment by digitalsleuth** [comment]
@gunner4361 Is this from the download of the SIFT VM, or is it after installing SIFT using the CLI?
If you used the CLI, try running it again using the `--pre-release` argument as well.

**Comment by digitalsleuth** [comment]
Hi @gunner4361 , any word on this?

**Comment by ekristen** [comment]
@gunner4361 if you can follow up in the future, please do an I will re-open.
