### ISSUE TITLE
listed un/pw pair for sift .ova download not accepted

### ISSUE THREAD

**Issue by puku-777** [teamdfir/sift#503]
to reproduce:
click link for the sift .ova from [downloads page](https://digital-forensics.sans.org/community/downloads) and get directed to [login page](https://digital-forensics.sans.org/login/)
un `sansforensics` pw `forensics` is apparently wrong?

**Comment by ekristen** [comment]
Login with sans account to download.

Listed creds are for the VM.

**Comment by puku-777** [comment]
oops! thanks
