### ISSUE TITLE
XUbuntu 18.04 SIFT install failure and fix

### ISSUE THREAD

**Issue by gnittala** [teamdfir/sift#506]
Hello,
I was installing SIFT via the CLI on Xubuntu 18.04 and SIFT installation fails. The saltstack.log file is attached and there are 5 failures - all related to gnome dock.

### OS version details

> NAME="Ubuntu"
> VERSION="18.04.5 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

### Error details
```shell
$ grep "result: false" saltstack.log 2>/dev/null | wc -l
5
```

```shell
gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop','firefox.desktop', 'org.gnome.Nautilus.desktop']"
```
On the XUbuntu machine this fails. And the root cause of this is because of two missing packages. 
- gnome-shell-extensions
- gnome-shell-extension-dashtodock

I found this by running the `gsettings` and noticing that on xubuntu these are not available
```shell
$ gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop','firefox.desktop', 'org.gnome.Nautilus.desktop']"
No such schema “org.gnome.shell”
```

### Fix
`sudo apt-get install gnome-shell-extensions gnome-shell-extension-dashtodock`

I understand that the supported distro mentions _18.04 Ubuntu Desktop (only default Gnome Desktop)_ but it might be useful to add this a dependency so that this can work on lightweight Ubuntu distributions too. The specific failures are detailed in the siftlog-failures-20210117.txt file.

[saltstack.log](https://github.com/teamdfir/sift/files/5826302/saltstack.log)
[siftlog-failures-20210117.txt](https://github.com/teamdfir/sift/files/5826308/siftlog-failures-20210117.txt)

**Comment by ekristen** [comment]
I'll take a look at adding these two dependencies.

Regards,
-Erik

**Comment by digitalsleuth** [comment]
After looking into this, it seems that the gnome-shell-extension-dashtodock is only available on Bionic, Hirsute and above, but not on Focal.

Technically, the [deb package under Hirsute](https://launchpad.net/ubuntu/+source/gnome-shell-extension-dashtodock) available on the Ubuntu PPA does install and appears to work on Focal, so it "could" be a viable option. However, any changes that might occur with this package which only function in Hirsute could then break future compatibility in Focal.

@ekristen , if you're interested in giving it a go for Bionic and Focal, I can do up a state which will run on both, but the Focal one will need a direct download of the deb package from the PPA for install.

**Comment by ekristen** [comment]
We are dropping 18.04 and only supporting 20.04 and 22.04 as soon as https://github.com/teamdfir/sift-saltstack/pull/80 is merged.

Side Note: SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)
