### ISSUE TITLE
sit-config-tools: Update returned exit code not zero

### ISSUE THREAD

**Issue by jackdyson1399** [teamdfir/sift#507]
I am having issues installing SIFT through SIFT-cli on Ubuntu 18.04.5 LTS.
I am using a brand new VM and I am running the following commands on it to initiate the install:
- `sudo apt update`
- `sudo apt install curl`
- `sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.9.2/sift-cli-linux`
- `sudo chmod +x /usr/local/bin/sift`
- `sudo sift install`

Upon running this, I receive the below error:
![image](https://user-images.githubusercontent.com/46749580/105528177-8f335a80-5cdc-11eb-8ff1-872f5abf56e5.png)

Interestingly, when I run `sudo sift install` again, it will not let me, it says: 
![image](https://user-images.githubusercontent.com/46749580/105528290-b427cd80-5cdc-11eb-8981-35c4d5a75547.png)
And running `sudo sift update` returns the same error as before, I get it is now apparently installed but I am concerned about the using the VM in this state when there was an error during the installation.
I have tried this at least 5 times now and the same error persists. I originally thought it could be to do with it installing SIFT v2021.1.0 as I do have a working SIFT v2020.6.1 VM, but I have tried to install both versions and each time it gets stuck on the same error.
I have attached my saltstack.log file for you to view.

[saltstack.log](https://github.com/teamdfir/sift/files/5857750/saltstack.log)

**Comment by ekristen** [comment]
It should be trying to install v2021.1.0 which is the latest, odd that you'd be getting an older version.

It appears that 99% of things installed, it was just some minor user config items that were missed.

**Comment by ekristen** [comment]
You can run `sift upgrade` to get the latest.

**Comment by jackdyson1399** [comment]
Hi thanks for the advice. I did attempt to install the newest version first. Same error. 
I was attempting this version as it is the same as the one I have that works. So wanted to see if it was the version or not. Which I ruled out as latest version and the older version creates same error. 

I ran sift upgrade and it created the same error.

**Comment by digitalsleuth** [comment]
Hi @jackdyson1399 , when you created this VM, was it a brand new SIFT VM downloaded from the SANS website, or was this one you created manually?

If manually, can you run salt-common -V or salt-minion -V and post the results?

Additionally, after looking at your saltstack.log, it appears that you only have one actual error during the installation, and that's the configuration of the theme. It appears that the error revolves around the cli not being able to create an entry in the `/home/test/.dbus` folder. This is typical when the user (in this case `test`) does not have proper permissions on the folder. You can remedy this by running `sudo chown -R test:test /home/test/.dbus`.

Please try this out and let us know the result!

**Comment by jackdyson1399** [comment]
Hi, thank you for the detailed help.
My set up was a clean Ubuntu 18 minimal install VM set up via Virtual Box. I was then running a bash shell script which included the install of SIFT to create the SIFT workstation but with a few extra features that my team needs.

I have now managed to get it to install successfully by changing my custom script to install Virtual Box Guest Editions and disable automatic updates **after** installing SIFT. I concluded the VBox Guest Editions and the fact I disabled automatic updates created the error as once I moved them to after SIFT had been installed, the install worked every time.

Thank you for your help in understanding the saltstack.log, I'm relatively new to its use. But your description will certainly help in the future if I get the same error again. I don't know what exactly caused it, but for the time being I now have a working install process, however that may be.

**Comment by digitalsleuth** [comment]
@jackdyson1399 Glad to help anytime. I'd be curious to know your step-by-step was for your install, and what your bash script contained, so I could potentially try to duplicate this error and determine what caused it, if you have the time of course.

Cheers!

**Comment by jackdyson1399** [comment]
I'll get this write up for you tomorrow. I would be interested too if you could replicate and provide a more formal reasoning than mine. 
Thanks again.

**Comment by jackdyson1399** [comment]
Okay so I have modified the script to make it more simple (removing comments and console output etc). The script is designed to log the console output of the commands in files, they will be saved to script execution directory for the purpose of testing. I had to change extension to txt from sh.

Unsuccessful script is here: [SIFTvm_Installer (Test).txt](https://github.com/teamdfir/sift/files/5893567/SIFTvm_Installer.Test.txt)

My process is as follows:
> 1.  Install a minimal install of Ubuntu 18.04.5
> 2. Create snapshot of clean install to revert to if necessary
> 3. Boot up the VM and log into account
> 4. Accept default options on the welcome pages
> 5. Wait a few minutes until the automatic software recommendations appear
> 6. Decline the Ubuntu 20 Upgrade
> 7. Decline the Security Update
> 8. Open terminal and run `sudo ./SIFTvm_Installer (Test)` (or equivalent path)
> 9. Follow script instructions (there are a few input prompts before SIFT install)

I tried this process this morning and I received the same errors as before. So I have attached the [saltstack.log](https://github.com/teamdfir/sift/files/5893534/saltstack.log), the requested [saltMinion.txt](https://github.com/teamdfir/sift/files/5893537/saltMinion.txt) output and the script's console outputs 
[Initial_Updates.log](https://github.com/teamdfir/sift/files/5893538/Initial_Updates.log), [SIFT_Install.log](https://github.com/teamdfir/sift/files/5893540/SIFT_Install.log) for you to look at.

The shortened working script is here: [SIFTvm_Installer (Working Test).txt](https://github.com/teamdfir/sift/files/5893569/SIFTvm_Installer.Working.Test.txt)

**Comment by digitalsleuth** [comment]
@jackdyson1399 I noticed that you said 'minimal install', then referenced 'default options on the welcome pages'. Did you install this VM with a Desktop Environment? If so, which one? Either that, or I'm guessing you might have used the 18.04.5 Desktop ISO instead of the minimal?

**Comment by jackdyson1399** [comment]
Hi yes I used the Desktop ISO but when in the GUI for the installation I chose the minimal option.

**Comment by jackdyson1399** [comment]
Hi,
has there been any update on this? My fix does not always seem to work. The error seems a bit unpredictable.

**Comment by ekristen** [comment]
I am in the process of doing test builds now on several changes. Look for
an update soon.

**Comment by jackdyson1399** [comment]
Great thank you.
sorry for being hasty.

**Comment by ekristen** [comment]
Latest builds on the latest version seem to be doing ok. Try doing an update pulling the latest version.

**Comment by jackdyson1399** [comment]
I will look into this tomorrow. 
I did attempt to install SIFT v2021.2.0 on Tuesday but it created the error again. But this time it did not show that it had been installed, where as last time it showed it was installed. 

I will upload more results tomorrow when I get them.

**Comment by jackdyson1399** [comment]
Good morning. 
So I have attempted to run the my script today trying to install `v2021.2.0`.
Again, it did not succeed. But this time, SIFT-cli does not even recognise that SIFT is installed. Whereas last time when it created the error, it still recognised that SIFT had been installed so the other commands like `sift upgrade`, `sift list-upgrades` etc worked, now they do not. Here is the information you requested about my attempt before:
- [os_release.txt](https://github.com/teamdfir/sift/files/5964735/os_release.txt)
- [SIFT_Install.log](https://github.com/teamdfir/sift/files/5964738/SIFT_Install.log)
- [saltstack.log](https://github.com/teamdfir/sift/files/5964743/saltstack.log)
- [salt-call.txt](https://github.com/teamdfir/sift/files/5964750/salt-call.txt)
- [sift_list-upgrades.txt](https://github.com/teamdfir/sift/files/5964755/sift_list-upgrades.txt)
- [sift_debug.txt](https://github.com/teamdfir/sift/files/5964754/sift_debug.txt)

Let me know if you need anything else from this install.

**Comment by ekristen** [comment]
@jackdyson1399 if it never gets a 100% successful install, it will not recognize a partial install. It's a design decision. However in the face of error it does not roll back, everything that was installed is still installed.

Looks like some errors around pyhindsight not being installed properly. We've had quite the number of problems getting all the python stuff to work correctly with the deprecation of python2 and a lot of tools not supporting it.

**Comment by jackdyson1399** [comment]
Okay thank you for looking into this.
I will keep trying to see if I can get it to fully install as any errors could cause issues when validating our lab, even if we can justify them.

**Comment by eddocode** [comment]
Possible work around while pyhindsight issue (https://github.com/teamdfir/sift-saltstack/pull/48) gets resolved. This is what I had to do on fresh Ubuntu 18.04.5 to install sift (v2021.2.0). Also, puremagic is required by latest pyhindsight; you can install pyhindsight without the module but hindsight.py fails to start without puremagic module.

```
sudo apt update
sudo apt upgrade
sudo apt install build-essential python3-pip libssl-dev rustc curl
sudo pip3 install puremagic
sudo pip3 install pyhindsight
sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.9.2/sift-cli-linux
sudo chmod +x /usr/local/bin/sift
sudo sift install
```

**Comment by robertnixon2003** [comment]
That didn't work for me:
```
>> Running: sift-config
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by digitalsleuth** [comment]
@robertnixon2003 Can you upload your saltstack.log file so we can take a look?
We are in the midst of testing a fix, so a full resolution should be available soon. However while your install may say it failed, reviewing the logs will allow us to see just where it failed, and if it's only as a result of one or two tools, which we can rectify and get it to 100%.

**Comment by jackdyson1399** [comment]
@eddocode thank you for your response. 
I have tried your recommend installation process and it has allowed me to successfully install SIFT five times today, with no failed attempts.
I will update my scripts to include the 'pre-installation' of pyhindsight while a more "permanent" fix is issued in a newer version.

**Comment by pyrodie18** [comment]
Looks like I'm having the same problem as everyone else as well (log included).  I may give @eddocode idea a try
[saltstack.log](https://github.com/teamdfir/sift/files/6004794/saltstack.log)

**Comment by blebeIGeonAT** [comment]
> Possible work around while pyhindsight issue ([teamdfir/sift-saltstack#48](https://github.com/teamdfir/sift-saltstack/pull/48)) gets resolved. This is what I had to do on fresh Ubuntu 18.04.5 to install sift (v2021.2.0). Also, puremagic is required by latest pyhindsight; you can install pyhindsight without the module but hindsight.py fails to start without puremagic module.
> 
> ```
> sudo apt update
> sudo apt upgrade
> sudo apt install build-essential python3-pip libssl-dev rustc curl
> sudo pip3 install puremagic
> sudo pip3 install pyhindsight
> sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.9.2/sift-cli-linux
> sudo chmod +x /usr/local/bin/sift
> sudo sift install
> ```

This worked for me. Well, it fixed my first problem: SIFT error installing on a clean Ubuntu 18.04 VM. Thank you eddocode for this post!

But now I have a new problem: I get the same type of error message when attempting to add REMnux (addon mode) to my new SIFT machine. Any suggestions for how to fix? 

My salfstack log file is attached. 
[saltstack.log](https://github.com/teamdfir/sift/files/6010612/saltstack.log)

**Comment by jackdyson1399** [comment]
It seems the fix by @eddocode does not work every time. I have tried it about 15-20 times via the same method and its probably failed on half of them. 
Does anybody know whether the newer releases come with a more permanent fix? 
I am unsure how to find out.

**Comment by digitalsleuth** [comment]
Good morning @jackdyson1399, if you're looking to upgrade the existing installation, yes the latest release comes with the fix for that. If however you're about to start a new install, there is a minor issue with the python2 pip installation on focal. A fix has been submitted, but there is a workaround by installing python2 first, then the pip binary, then installing sift.

**Comment by jackdyson1399** [comment]
Great thank you for the help. I will close this issue as I presume there is another one open for the other minor issue.
