### ISSUE TITLE
Can't import OVF into VMware

### ISSUE THREAD

**Issue by Shirofune-Security** [teamdfir/sift#512]
I cannot import the OVF file into VMware fusion 12 with the error "Failed to open OVF descriptor".
I think I tried a year ago and seems to still be broken.
<img width="637" alt="SIFT-failed-to-open-OVF-descriptor" src="https://user-images.githubusercontent.com/43838376/111236608-9caef600-8636-11eb-9a22-271ca52794fa.png">

**Comment by digitalsleuth** [comment]
@Shirofune-Security I'll take a look at this today and see if I can get you a workaround. However, it would actually be just as easy to create a brand-new Ubuntu 20.04 VM with the desktop environment installed, then install sift using the sift-cli.

If you create the new VM, vice importing the old one, you should install python2 first from APT (`sudo apt install python2`) then install the python2 pip binary using `curl -o /tmp/get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py && python2 /tmp/get-pip.py`.

After this, install SIFT using the CLI tool and you should be good to go.

**Comment by ekristen** [comment]
We are looking to release an updated version of the OVA soon as well.

**Comment by digitalsleuth** [comment]
Hi @Shirofune-Security I've checked this using the SANS OVA from sans.org and VMware Fusion 12 without issue. Is there perhaps another OVA/OVF you were using for this? If you're still having the issues, I would follow what @ekristen mentioned and keep your eyes peeled for an updated OVA. This will likely address your issues as well.

**Comment by ekristen** [comment]
I'm going to close this issue out, it's been over a month. If you would like to revisit this, please comment and I will re-open.

**Comment by YamatoSecurity** [comment]
I just downloaded and tried with VMware Fusion 13.0.0 and still I get the Failed to OVF descriptor error when trying to import.
