### ISSUE TITLE
SIFT Workstation Documentation on SANS.org Out-of-Date

### ISSUE THREAD

**Issue by graememeyer** [teamdfir/sift#515]
The documentation on SANS.org appears to be out of date, compared to the README in this repo. Specifically, this page contains numerous references and directs users to Ubuntu version 16.04 which is listed as no-longer-supported/deprecated by this repo: https://digital-forensics.sans.org/community/downloads

> Option 2: SIFT Easy Installation:
> Download Ubuntu 16.04 ISO file and install Ubuntu 16.04 on any system

There's seven references to 16.04, and even one to 14.04 (in the context of REMnux). Presumably these should be all updated to 18.04 at least

**Comment by ekristen** [comment]
Thanks for the heads up, I'll work with the team to figure out where those are at and how to get it all up-to-date.

**Comment by graememeyer** [comment]
The link to "SIFT Workstation YouTube Series" on that same page is also broken. Near as I can tell, that playlist doesn't exist any more
