### ISSUE TITLE
VMware tools not working on 20210331 internal build

### ISSUE THREAD

**Issue by mpilking** [teamdfir/sift#516]
After booting the OVA created on 2021-03-31, VMware tools do not seem to function. I am running it in VMware Workstation 15.5.7. I cannot resize it through VMware, such as View > Fit Guest Now. I cannot copy and paste between the host and VM. I'm also unable to mount shared folders--the option is greyed out in the VM's settings.

**Comment by ekristen** [comment]
Confirmed, it seems open-vm-tools is not being installed properly for some reasons.

**Comment by ekristen** [comment]
This has been fixed.
