### ISSUE TITLE
File sift-cli-linux.sha256.asc appears to be empty

### ISSUE THREAD

**Issue by Sylver-Dragon** [teamdfir/sift#519]
I am attempting to install the sift-cli on a new system following the guide at:  
https://github.com/teamdfir/sift-cli

During the download and verify process, I attempted to download the file:  
https://github.com/teamdfir/sift-cli/releases/download/v1.10.0-rc3/sift-cli-linux.sha256.asc

This file appears to to be empty, which means that the following step fails:  
`Validate the signature gpg --verify sift-cli-linux.sha256.asc`

**Comment by ekristen** [comment]
Thanks for the report. Fixed in rc4.

**Comment by canadianmuppet** [comment]
I am currently trying to install on a HyperV Ubuntu 18.04, and when I try to gpg verify "sift-cli-linux.sha256.asc" I get
"gpg: verify signatures failed: Unexpected error"
Is this the correct SHA256 for "sift-cli-linux.sha256.asc" ?
"ad66011043442c34d13ccd1df5553c89e9373da6ae15f73993f69457b596f6e4"
Many thanks for any help.

**Comment by ekristen** [comment]
We have a known issue with the signing at the moment, working to resolve. You are still safe to download from the GitHub releases, this is just extra verification.

**Comment by ekristen** [comment]
1.10.0-rc5 is now fixed.

**Comment by canadianmuppet** [comment]
Cheers for the quick response, just tried it and it works.
Many thanks.
