### ISSUE TITLE
 SIFT CLI - {{ user }}

### ISSUE THREAD

**Issue by salty4n6** [teamdfir/sift#521]
Hi,
While running the desktop mode install, I'm getting a home directory called {{ user }}.  Most of the desktop changes of the SIFT install aren't working.  The wallpaper appears to be the only one that was successful. I attempted to follow the salt.log to see what all is going on but I'm failing miserably.  This issue happens on both Ubuntu 18.04 and 20.04.  I've run through the with various accounts already being created, sift_user, sansforensics, and random accounts and they all behave the same way.
Thanks,
Salty
[saltstack.log](https://github.com/teamdfir/sift/files/6337317/saltstack.log)

![image](https://user-images.githubusercontent.com/81833785/115264469-da1b0d80-a125-11eb-9e68-158902d84936.png)

**Comment by esentner** [comment]
I installed on 18.04 yesterday and got the same thing.  I'm trying again on 20.04 but expect since you got this, I'll see the same.

**Comment by ekristen** [comment]
I think this was an accidental bug introduced in the 2021.4.2 update, the 2021.4.3 is out and I don't see it happening there.

**Comment by ekristen** [comment]
Finally duplicated this. Attempting to track it down.
