### ISSUE TITLE
invalid OS, unable to determine ubuntu version

### ISSUE THREAD

**Issue by beedjbite** [teamdfir/sift#523]
I have follow to the install instructions (https://github.com/teamdfir/sift-cli#installation) serval times, tested to install sift in the supported ubuntu.desktop 16&18 but keep getting following error:

sudo sift install
> sift-cli@1.10.0-rc5+0-ga2e1d5f

invalid OS, unable to determine ubuntu version
Error: invalid OS, unable to determine ubuntu version
    at validOS (/snapshot/sift-cli/sift-cli.js:162:11)
    at run (/snapshot/sift-cli/sift-cli.js:655:9)
    at async main (/snapshot/sift-cli/sift-cli.js:758:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'**_

-----------------------------------------------

running apt-get update & autoremove also tested.

**Comment by ekristen** [comment]
We support 20.04 LTS

**Comment by D4ziel** [comment]
hi,
following up on the error above which I also experienced.

I am using Linux on my chromebook (I guess it is called Crostini) and the OS seems invalid. Do I need to install ubuntu if I am to get SIFT working?

cheers,

**Comment by ekristen** [comment]
We only support Ubuntu 20.04 at this time.
