### ISSUE TITLE
[CLI] New Releases of SIFT CLI does not include 'Latest' tag

### ISSUE THREAD

**Issue by hunttom** [teamdfir/sift#524]
Recommendation: Is this possible to tag SIFT CLI with 'Latest' Tag in order to keep commands simplified for automated build processes?

Example:
Use the following to install SIFT CLI: `curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/latest/sift-cli-linux` 

Or if requiring a specified version:
`curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.9.2/sift-cli-linux`

**Comment by ekristen** [comment]
I'm going to close this issue for now. I'm not sure that I'll add a latest tag and the SIFT CLI is getting replaced by a new tool soon.
