### ISSUE TITLE
Bad ASC file on the SIFT-CLI repository

### ISSUE THREAD

**Issue by fbourla** [teamdfir/sift#525]
There is a small issue on the [SIFT-CLI repository](https://github.com/teamdfir/sift-cli). The ASC file is not healthy, which prevents users from validating the SHA256 signature with "shasum -a 256 -c sift-cli-linux.sha256.asc" or "sha256sum -c sift-cli-linux.sha256.asc".
 
The problem seems to have been introduced with v1.10 in April last year. The ASC file in v1.9.2 seems to be fine.

**Comment by ekristen** [comment]
There was an ASC issue for a short while, it's been remedied on the latest RC release and the 1.10.0 that was just released.

**Comment by ekristen** [comment]
I'm going to close, if you think there is still a problem, please comment back on the issue.

**Comment by fbourla** [comment]
Unfortunately not. The ASC should indeed be a SIG file, and it should contain the hash of the sift-cli-linux executable instead of the relative path "release/sift-cli-linux.sha256".

At the moment, the SHA256 signature verification as defined at [https://github.com/teamdfir/sift-cli#installation](https://github.com/teamdfir/sift-cli#installation) (see step 5) cannot work.

**Comment by ekristen** [comment]
@fbourla I've verified what you are seeing now. I'm looking into it.

**Comment by ekristen** [comment]
Please see the updated README. The signing and validation of the binary has changed to use [cosign](https://github.com/sigstore/cosign)
