### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by 8ear** [teamdfir/sift#526]
Hi,
in #523 you say that you support only Ubuntu 20.04 at the moment. But your readme file say:

Supported Distros
18.04 Ubuntu Desktop (only default Gnome Desktop)
18.04 Ubuntu Server (use --mode=server with the CLI tool)

Upcoming Support
20.04 Ubuntu Desktop
20.04 Ubuntu Server

Deprecated / No Longer Supported
14.04 Ubuntu
16.04 Ubuntu

____
So I think it should be changed to:

Supported Distros
20.04 Ubuntu Desktop
20.04 Ubuntu Server

Upcoming Support
\-

Deprecated / No Longer Supported
14.04 Ubuntu
16.04 Ubuntu
18.04 Ubuntu Desktop (only default Gnome Desktop)
18.04 Ubuntu Server (use --mode=server with the CLI tool)

or?

**Comment by ekristen** [comment]
Complete.
