### ISSUE TITLE
[CLI] sift install => permission denied, mkdir '/var/cache/sift'

### ISSUE THREAD

**Issue by D4ziel** [teamdfir/sift#527]
Hi,
Very noob with linux so apologies for missing the basics (UBUNTU 20.04 LTS on Windows).

I am trying to install sift after having followed the previous steps and I get the following issue: 
Can you please guide me on what I can do? thanks

"_> sift-cli@1.10.0-rc5+0-ga2e1d5f

EACCES: permission denied, mkdir '/var/cache/sift'
Error: EACCES: permission denied, mkdir '/var/cache/sift'

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'_ "

**Comment by D4ziel** [comment]
Hi,

I tried again, now using "sudo sift install" but with no lack and the following new error. Any tip?

"_> sift-cli@1.10.0-rc5+0-ga2e1d5f
> sift-version: notinstalled

> mode: desktop
Installing and configuring SaltStack properly ...
> downloading v2021.4.4
>> downloading sift-saltstack-v2021.4.4.tar.gz.asc
>> downloading sift-saltstack-v2021.4.4.tar.gz.sha256
>> downloading sift-saltstack-v2021.4.4.tar.gz.sha256.asc
>> downloading sift-saltstack-v2021.4.4.tar.gz
> validating file sift-saltstack-v2021.4.4.tar.gz
> validating signature for sift-saltstack-v2021.4.4.tar.gz.sha256
> extracting update sift-saltstack-v2021.4.4.tar.gz
> performing update v2021.4.4
>> Log file: /var/cache/sift/cli/v2021.4.4/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:542:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove_'"

**Comment by ekristen** [comment]
Add `--mode=server`, WSL does not support the desktop install of SIFT, no X11 env.

**Comment by D4ziel** [comment]
thanks ekristen! it worked very nicely
