### ISSUE TITLE
Error - Update returned exit code not zero - snapshot/sift-cli

### ISSUE THREAD

**Issue by TechButton** [teamdfir/sift#528]
Same error on WSL 20.04 and 20.04 Desktop with /snapshot/sift-cli/shift-cli.js:542:23 events.js:315:20 internal/child_process.js:1051:16 and internal/child_process.js:287:5

errors out on the same part when I run the --mode=server and without it on the 20.04 desktop version.

**Comment by digitalsleuth** [comment]
Hi @TechButton Any chance you can provide the saltstack.log file from your installation? This will help us narrow down the error.

**Comment by TechButton** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/6535354/saltstack.log)

**Comment by TechButton** [comment]
There is the file from one of the machines, I just tried it again, and same error. I am getting to the same spot on another machine. I am thinking it is a URL block somewhere that it is not able to download something.

**Comment by TechButton** [comment]
I saw the checksums failed on the desktop. I deleted those files from the folder and ran it again and I got a success message. But now I don't have any cheatsheets on the desktop.

> sift-cli@1.10.0+0-g48a701b
> sift-version: v2021.4.4

> mode: desktop
SIFT already installed, please use the update or upgrade command

**Comment by digitalsleuth** [comment]
Hi @TechButton , apologies for the delay in getting back to you. The issue you received in the saltstack.log file above is from a hash mismatch between some of the PDF's which get downloaded. The remainder of the software has installed fine, and once the new hashes and URL source for the PDF are updated, your install should run error free.

**Comment by DanFelton** [comment]
> Hi @TechButton , apologies for the delay in getting back to you. The issue you received in the saltstack.log file above is from a hash mismatch between some of the PDF's which get downloaded. The remainder of the software has installed fine, and once the new hashes and URL source for the PDF are updated, your install should run error free.

How do you update the hashes and URLs?

**Comment by digitalsleuth** [comment]
Hi @DanFelton , These should be updated now. Have you tried recently? If so, and it failed, please upload your saltstack.log file so we can take a look.

**Comment by DanFelton** [comment]
Just did it today and the pdfs are missing, and that seems to be where it's failing

[saltstack.log](https://github.com/teamdfir/sift/files/6755869/saltstack.log)

**Comment by digitalsleuth** [comment]
That's correct, it is the PDF's. It's not so much the hashes that are the issue, it's the origin of the PDF's that's changed. Due to the SANS recent upgrade of their website and resources, some of the PDF's require login for download, and some of them have a new URL.

Besides this, everything else seems to be installed properly, so you should have a fully functioning SIFT environment, with the exception of the PDF's. 

@ekristen, would it be easier/better to download and source the PDF's from the github repo vice the original source, given the requirement for login and new download locations (ie: sansorg.egnyte.com URL's) for these?

**Comment by ekristen** [comment]
The PDFs were valid as of this last Monday, I'll check them again.

**Comment by ekristen** [comment]
Closing this. PDFs are working, this issue should be resolved.
