### ISSUE TITLE
[Question] Why use libbde-utils over dislocker?

### ISSUE THREAD

**Issue by TheAlienDrew** [teamdfir/sift#529]
I'm not saying one or the other is better, but I've been using dislocker for a while (until it recently started not working), and wondering what advantages libbde-utils has.

**Comment by ekristen** [comment]
I'm not aware of any conscious decision between one vs the other, there have been talks of adding dislocker previously, however lib bde is already apart of the GIFT/Libyal suite so we install it.

**Comment by TheAlienDrew** [comment]
> I'm not aware of any conscious decision between one vs the other, there have been talks of adding dislocker previously, however lib bde is already apart of the GIFT/Libyal suite so we install it.  

In that case, had any unlocking issues with 1909 or newer Windows BDE drives?

**Comment by joachimmetz** [comment]
FYI `libbde-utils` is Debian maintained and seriously out of date https://packages.ubuntu.com/bionic/libbde-utils, https://packages.ubuntu.com/focal/libbde-utils

`libbde-tools` is the name of the package in the GIFT PPA which is up to date https://launchpad.net/~gift/+archive/ubuntu/stable/+packages?field.name_filter=libbde&field.status_filter=published&field.series_filter=

@TheAlienDrew first of all I recommend to make sure you are using the latest version, second I recommend to reach out to authoritative project if you run into issues

**Comment by TheAlienDrew** [comment]
That's pretty useful information, thanks this is helpful. I'll close this now.
