### ISSUE TITLE
Won't boot in Virtualbox on Linux

### ISSUE THREAD

**Issue by KDPryor** [teamdfir/sift#530]
I imported the OVA in Virtualbox and then started the VM. When starting the VM, all I get is the Vbox BIOS screen and then the grub menu. After that, I just get a black screen with the cursor flashing. Probably something I'm missing, but wondered if anyone had a suggestion

**Comment by KDPryor** [comment]
Please disregard. I just installed SIFT manually in a new Ubuntu VM instead.

**Comment by passuf** [comment]
I have the same problem, on both Ubuntu 21.04 and Windows 10 machines where the previous version of SIFT worked without problems.

Could we re-open the issue please?

**Comment by f6484563** [comment]
For anyon still having the same issues, I've fixed just changing the OS to Ubuntu. By default the OVA uses "Other OS" that may cause this blank screen issue.

**Comment by ekristen** [comment]
Great feedback! We just caught this problem elsewhere and fixed for the next release!
