### ISSUE TITLE
[CLI] Release v1.10.0 has incorrectly signed sha256 file

### ISSUE THREAD

**Issue by rsharo** [teamdfir/sift#532]
Hello,

Releases **v1.10.0** and **v1.10.0-rc5** have no hash in the file `sift-cli-linux.sha256.asc`, and the `asc` file is _not_ a detached signature.

This means `gpg` makes no attempt to verify `sift-cli-linux.sha256` and the end-user is unable to verify that the hash is unaltered.

Recommend removing `sift-cli-linux.sha256` and placing the hash in `sift-cli-linux.sha256.asc`, as was done for **v1.9.2**.

**Comment by ekristen** [comment]
@rsharo this has been resolved. Please see the updated README. The signing and validation of the binary has changed to use [cosign](https://github.com/sigstore/cosign)
