### ISSUE TITLE
[CLI] Unable to import GPG key from sks-keyservers to check integrity for sift-cli binary v1.10.0

### ISSUE THREAD

**Issue by gds-ahine** [teamdfir/sift#534]
Unable to verify the integrity of the latest sift-cli binary as we're no longer able to import GPG keys from sks-keyservers.net. DNS records were removed for SKS Keyservers as part of a GDPR takedown request.

ref: https://www.reddit.com/r/crypto/comments/o7oh4w/skskeyserversnet_pool_dns_records_disabled/

From https://github.com/teamdfir/sift-cli README line step 3 -:

Import the PGP Key - gpg --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 22598A94

**Comment by ekristen** [comment]
For now you should be able to use pgp.mit.edu instead.

I'll look into just publishing the key on GitHub and updating the instructions.

**Comment by photoemulator** [comment]
> For now you should be able to use pgp.mit.edu instead.

How is this done?  What are the steps I need to replace to succeed here?

**Comment by matthewthomaskelly** [comment]
The following command worked for me:

> gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94

**Comment by ekristen** [comment]
Thanks for helping out.

I'm looking at overhauling this in the near future, not sure how just yet.

**Comment by ekristen** [comment]
Please see the updated README. The signing and validation of the binary has changed to use [cosign](https://github.com/sigstore/cosign)
