### ISSUE TITLE
CLI - Cannot successfully run "sift update" even after updating apt-get

### ISSUE THREAD

**Issue by mh725** [teamdfir/sift#535]
Hello, I get 1 error when updating sift and another when updating apt-get. I am running both from the SIFT Workstation in VMWare Player 16.

![image](https://user-images.githubusercontent.com/86366104/124950879-cffc0300-dfe0-11eb-9566-9cc869666f3d.png)

![image](https://user-images.githubusercontent.com/86366104/124950938-dd18f200-dfe0-11eb-91f1-35c913fd3d0b.png)
 
i386 architecture...? Unsure - would appreciate any insights! Thanks!

**Comment by ekristen** [comment]
Beginning of output lists a log file, please upload that.

**Comment by mh725** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/6786859/saltstack.log)

**Comment by ekristen** [comment]
Looks like a single file was unable to be downloaded and installed. Most likely just a transient error you can try again, the SIFT tool will only install what's missing or configure what's not configured, it is idempotent.

```
Error: HTTP 599: Timeout while connecting
      reading http://mirrors.kernel.org/ubuntu/pool/universe/p/pdftk-java/pdftk-java_3.1.1-1_all.deb\n"
```
