### ISSUE TITLE
CLI - Suggested location for sift-cli-linux.sha256.asc

### ISSUE THREAD

**Issue by anfokaboom** [teamdfir/sift#536]
Hi

Is sift-cli-linux.sha256.asc meant to be somewhere in particular before validating it in step 4 of instructions?

**Comment by ekristen** [comment]
Same directory as the binary

**Comment by ekristen** [comment]
Please see the updated README. The signing and validation of the binary has changed to use [cosign](https://github.com/sigstore/cosign)
