### ISSUE TITLE
[CLI] No "sift-cli-linux: OK" When Validating Signature

### ISSUE THREAD

**Issue by cle1861** [teamdfir/sift#538]
I followed all the steps but is there something I'm doing wrong? Any help is appreciated.
<img width="979" alt="Screen Shot 2021-08-10 at 7 57 52 PM" src="https://user-images.githubusercontent.com/47131999/128949863-28c28b42-e0ed-4d97-8879-432f876fc781.png">

**Comment by cle1861** [comment]
I'm using an ARM-based Ubuntu VM, does that have anything to do with my errors?

**Comment by ekristen** [comment]
ARM is definitely not supported

**Comment by ekristen** [comment]
@cle1861 please see the updated instructions, SIFT-CLI is now using the cosign tool for signing and validation, unfortunately ARM is not supported at this time.
