### ISSUE TITLE
[CLI] Proxy-Issues again

### ISSUE THREAD

**Issue by Daniel-CS-Team** [teamdfir/sift#540]
I found 2 older issues reagrding Proxy-Issues when using sift-cli.
However, the problem seems to be back.
```
$ export HTTPS_PROXY="http://**.**.**.**:8080/"
$ export HTTP_PROXY="http://**.**.**.**:8080/"
$ sudo ./sift-cli-linux install --mode=server
> sift-cli@1.11.0+0-g966729b
> sift-version: notinstalled

> mode: server

request to https://api.github.com/repos/teamdfir/sift-saltstack/releases failed, reason: getaddrinfo EAI_AGAIN api.github.com
HttpError: request to https://api.github.com/repos/teamdfir/sift-saltstack/releases failed, reason: getaddrinfo EAI_AGAIN api.github.com
    at /snapshot/sift-cli/node_modules/@octokit/request/dist-node/index.js:108:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getValidReleases (/snapshot/sift-cli/sift-cli.js:276:18)
    at async run (/snapshot/sift-cli/sift-cli.js:718:26)
    at async main (/snapshot/sift-cli/sift-cli.js:758:5)
```
The first install steps connecting to repo.saltproject.io work nicely over the configured proxy, but for this request, I do not even see a connection attempt in the proxy-logs. 

FYI: Environment is Ubuntu 20.04 running in WSL1 on Windows Server 2019

**Comment by Daniel-CS-Team** [comment]
Well, the workstation has no DNS-Resolution because all traffic must go via the proxy. This works well for all tools, which are proxy-aware. As mentioned above, for the first install steps, it works.

This means, that whatever tires to resolve api.github.com is not proxy-aware.

**Comment by ekristen** [comment]
@Daniel-CS-Team checking in.

**Comment by Daniel-CS-Team** [comment]
Hi @ekristen,

thank you for die update. Works now like expected.
