### ISSUE TITLE
SIFT Installer error: unable to validate hashes for sift-saltstack | On Ubuntu server 20.04 and v2021.9.0

### ISSUE THREAD

**Issue by AgnosticCrusader** [teamdfir/sift#546]
I have a basic installation of Ubuntu **Server** 20.04.3. I am following the instructions from _Option 2A: SIFT Easy Installation on Native Ubuntu System_

When I run _sudo sift install --mode=server_ , I get the error below.

Does SIFT expect Ubuntu Desktop? Or am I running into some other (unexpected) issue?

==============

t805959@tsirtforensicswest:/var/tmp$ sudo sift install --mode=server 
> sift-cli@1.13.1+0-g5ecd4f4
> sift-version: notinstalled

> mode: server
> downloading v2021.9.0
>> downloading sift-saltstack-v2021.9.0.tar.gz.asc
>> downloading sift-saltstack-v2021.9.0.tar.gz.sha256
>> downloading sift-saltstack-v2021.9.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2021.9.0.tar.gz
> validating file sift-saltstack-v2021.9.0.tar.gz

Hashes for sift-saltstack-v2021.9.0.tar.gz do not match. Expected: , Actual: bbb6b86d4269a9b6797496345b8f7cc852763ba2df1047b6a017e2abcc1c4606  /tmp/sift-saltstack-v2021.9.0.tar.gz

Error: Hashes for sift-saltstack-v2021.9.0.tar.gz do not match. Expected: , Actual: bbb6b86d4269a9b6797496345b8f7cc852763ba2df1047b6a017e2abcc1c4606  /tmp/sift-saltstack-v2021.9.0.tar.gz

    at validateFile (/snapshot/sift-cli/sift-cli.js:401:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:468:3)
    at async run (/snapshot/sift-cli/sift-cli.js:758:5)
    at async main (/snapshot/sift-cli/sift-cli.js:781:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**Comment by digitalsleuth** [comment]
Hi @AgnosticCrusader , it looks like there may not have been a download of the actual release file. This could happen if there was a network connectivity problem, or perhaps you might be behind a proxy. Could this be the case?

**Comment by AgnosticCrusader** [comment]
> Hi @AgnosticCrusader , it looks like there may not have been a download of the actual release file. This could happen if there was a network connectivity problem, or perhaps you might be behind a proxy. Could this be the case?

I noticed that. I am indeed behind a proxy, but /etc/environment is correctly set: 

http_proxy="http://###.###.##.25:8080/"
https_proxy="http://###.###.##.25:8080/"
HTTP_PROXY="http://###.###.##.25:8080/"
HTTPS_PROXY="http://###.###.##.25:8080/"

Having said that, some tools have their own config file for proxy declaration - they may not pick up on proxies defined in the environment variables. Is that the case here? Is there a magic config file where I need to declare my proxy?

**Comment by ekristen** [comment]
Make sure those environment variables are in your current shell and you should be ok.

**Comment by ekristen** [comment]
@AgnosticCrusader following up here.

**Comment by AgnosticCrusader** [comment]
None of the suggestions above worked. It looks like Saltstack has some issues with certain proxy types. I ended up deploying the SIFT appliance. I then tried to install REMnux on top of the SIFT appliance and ran into the same Saltstack issues.  Here is how I resolved those issues :

wget https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg

sudo mv salt-archive-keyring.gpg /usr/share/keyrings/

echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main" | sudo tee /etc/apt/sources.list.d/salt.list

sudo apt-get update

sudo apt-get install salt-minion

sudo service salt-minion stop

sudo vi /etc/salt/minion
  proxy_host: <you proxy IP>
  proxy_port: <your proxy port>

sudo apt-get install python3-tornado4

sudo apt-get install python3-pycurl

===

After that, Saltstack works fine through the proxy and I could install REMnux

=== 

sudo git clone https://github.com/REMnux/salt-states.git /srv/salt

clear;sudo salt-call -l info --local state.sls remnux.addon 

===

My workaround also works with a semi-manual installation of SIFT on a clean Ubuntu behind my troublesome proxy.

**Comment by ekristen** [comment]
You can just install `salt-common` via apt-get to get the `salt-call` command.

Nice note on the proxy_host and proxy_port variables, I can incorporate that into the updated CLI I'm working on.

**Comment by ekristen** [comment]
Closed the issue since you have a work around for your proxy problems.
