### ISSUE TITLE
[SALTSTACK] -  Rekall installation

### ISSUE THREAD

**Issue by itripc** [teamdfir/sift#547]
![image](https://user-images.githubusercontent.com/31646277/142741926-553c7d71-9b8c-4a06-99e1-8ec5232c2650.png)

Hello, I believe I got the most recent SIFT vm  from :  https://www.sans.org/tools/sift-workstation/?utm_medium=Display&utm_source=DFIR&utm_content=SIFT%20LAUNCH%20SPRING%2021_VMR&utm_campaign=DFIR%20Courses

then I installed the SIFT cli tools,  and did sift upgrade  and then  sift update , when I check the sift version it appears complete with no errors from what I can tell.  Yet, I cannot seem to launch Rekall from user or sudo   with either rekall -h  or rekal -h.   If Rekall is not suppose to be installed by default then that's my bad I thought it was in a SIFT vm in most my SANS courses. Thank you in advance.

**Comment by digitalsleuth** [comment]
Hi @itripc , Rekall is no longer in SIFT as it has been deprecated and no longer supported by the developers. However if you need rekall, you can download or build the docker from the REMnux repo (docker pull remnux/rekall:latest or build from https://github.com/REMnux/docker/tree/master/rekall).

Hope that helps!

**Comment by itripc** [comment]
Greatly appreciated.

**Comment by ekristen** [comment]
Thanks @digitalsleuth -- saw this over the weekend, you beat me to the response.
