### ISSUE TITLE
SIFT clean install errors - PDF posters

### ISSUE THREAD

**Issue by salty4n6** [teamdfir/sift#551]
Hi,
Looks like there is an issue with the links for a few of the SANS posters.

Here's a sample of the log.

comment: 'Failed to cache https://sansorg.egnyte.com/dd/hZjkv5VupH/: Error: HTTP
      403: Forbidden reading https://sansorg.egnyte.com/dd/hZjkv5VupH/'
    duration: 201.125
    name: /home/salty/Desktop/Network-Forensics-Poster.pdf
    result: false

Thanks,
Salty

[saltstack.log](https://github.com/teamdfir/sift/files/7836087/saltstack.log)

**Comment by ekristen** [comment]
Thanks for the report @salty4n6 -- we are aware of the issue. Unfortunately it's not a quite fix, some changes are being made with the backend on how these files are hosted and how access it provided. As soon as I have a solution I'll provide an update.

**Comment by salty4n6** [comment]
Thanks @ekristen .  I wasn't sure if you were aware or when the change happened.  Close the issue or leave it open, I'll leave that up to you.

Salty

**Comment by ekristen** [comment]
This is now fixed.
