### ISSUE TITLE
Trying to install sift 

### ISSUE THREAD

**Issue by lcsig156** [teamdfir/sift#552]
I am trying to install sift on ubuntu 20.4 and get this exit code not zero error...

sift install --mode=server --pre-release
> sift-cli@1.13.1+0-g5ecd4f4
> sift-version: notinstalled

> mode: server
> downloading v2021.12.5
>> downloading sift-saltstack-v2021.12.5.tar.gz.asc
>> downloading sift-saltstack-v2021.12.5.tar.gz.sha256
>> downloading sift-saltstack-v2021.12.5.tar.gz.sha256.asc
>> downloading sift-saltstack-v2021.12.5.tar.gz
> validating file sift-saltstack-v2021.12.5.tar.gz
> validating signature for sift-saltstack-v2021.12.5.tar.gz.sha256
> extracting update sift-saltstack-v2021.12.5.tar.gz
> performing update v2021.12.5
>> Log file: /var/cache/sift/cli/v2021.12.5/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:546:23)
[saltstack.log](https://github.com/teamdfir/sift/files/7900079/saltstack.log)

    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

I have attached my saltstack.log 
Any help is greatly appreciated

**Comment by ekristen** [comment]
Looks like you are actually hitting a python bug. Can you give me the output of `salt-call --versions-report`

**Comment by ekristen** [comment]
also provide `lsb_release -a` and `uname -a`

**Comment by lcsig156** [comment]
> 
 salt-call --versions-report


Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 439, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 30, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 35, in <module>
    import salt.utils.crypt
  File "/usr/lib/python3/dist-packages/salt/utils/crypt.py", line 22, in <module>
    import Crypto.Random  # nosec
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/__init__.py", line 32, in <module>
    from Crypto.Random.OSRNG.posix import new
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/posix.py", line 66
    except IOError, e:
                  ^

**Comment by ekristen** [comment]
Interesting this seems to be a new issue with the version of python. I can provide a sift-cli binary to test with to see if it resolves the issue.

**Comment by ekristen** [comment]
Actually if you'd like, you can test my new CLI tool https://github.com/ekristen/cast/releases/tag/v0.1.0, once you download the binary, you can put it into `/usr/local/bin/` or run it from the downloaded directory `./cast install --mode=server sift`

In the mean time I can update the sift-cli to see if an update will fix it.

**Comment by lcsig156** [comment]
Thank you for your time...I will try the test tool now...is this the download I need?  cast-v0.1.0-linux-amd64.tar.gz

**Comment by lcsig156** [comment]
I ran cast and this was the output...

WARN[0000] using unauthenticated github client, could result in API rate limiting
INFO[0000] checking operating system support             component=distro owner=teamdfir repo=sift-saltstack
INFO[0000] operating system is supported                 component=distro owner=teamdfir repo=sift-saltstack
INFO[0000] distro validated successfully                 command=install
INFO[0000] downloading archive file                      component=distro owner=teamdfir repo=sift-saltstack version=v2021.12.5
INFO[0002] downloading release file                      component=distro filename=sift-saltstack-v2021.12.5.tar.gz.asc owner=teamdfir repo=sift-saltstack
INFO[0002] downloading release file                      component=distro filename=sift-saltstack-v2021.12.5.tar.gz.sha256 owner=teamdfir repo=sift-saltstack
INFO[0002] downloading release file                      component=distro filename=sift-saltstack-v2021.12.5.tar.gz.sha256.asc owner=teamdfir repo=sift-saltstack
INFO[0002] validating file checksum                      component=distro filename=sift-saltstack-2021.12.5.tar.gz owner=teamdfir repo=sift-saltstack
INFO[0002] validating file pgp signature                 component=distro filename=sift-saltstack-2021.12.5.tar.gz owner=teamdfir repo=sift-saltstack
INFO[0002] extracting archive file                       component=distro owner=teamdfir repo=sift-saltstack version=v2021.12.5
INFO[0002] distro downloaded successfully                command=install
INFO[0002] installing using mode: server                 command=install
INFO[0002] checking if install can progress              component=installer
INFO[0002] running saltstack installer                   component=installer
INFO[0008] salt installed properly                       component=saltstack-installer
INFO[0008] running cast installer                        component=installer
INFO[0008] installing as user: ljames                    component=installer
INFO[0008] performing local install                      component=installer
INFO[0008] starting saltstack run                        component=installer
INFO[0008] log file location                             component=installer log=/var/cache/cast/installer/logs/saltstack.log
ERRO[0008] salt-call finished with errors                code=1 component=installer
WARN[0008]                                               component=installer

**Comment by ekristen** [comment]
Oh you are in WSL2, I haven't tested that environment, can you re-run with `./cast install -l debug --mode server sift` 

I've also published an RC of sift-cli that **might** address the issue https://github.com/teamdfir/sift-cli/releases/edit/v1.14.0-rc1

**Comment by lcsig156** [comment]
> Oh you are in WSL2, I haven't tested that environment, can you re-run with `./cast install -l debug --mode server sift`
> 
> I've also published an RC of sift-cli that **might** address the issue https://github.com/teamdfir/sift-cli/releases/edit/v1.14.0-rc1

This is the output at the end of the debug 

INFO[0002] distro downloaded successfully                command=install
INFO[0002] installing using mode: server                 command=install
INFO[0002] checking if install can progress              component=installer
DEBU[0002] configuring the installer                     component=installer
DEBU[0002] configuring saltstack installer               component=installer
INFO[0002] running saltstack installer                   component=installer
DEBU[0002] checking salt install on ubuntu               component=saltstack-installer
DEBU[0002] salt configured with apt                      component=saltstack-installer
INFO[0002] salt installed properly                       component=saltstack-installer
INFO[0002] running cast installer                        component=installer
INFO[0002] installing as user: ljames                    component=installer
INFO[0002] performing local install                      component=installer
INFO[0002] starting saltstack run                        component=installer
DEBU[0002] running command /usr/bin/salt-call [--config-dir /var/cache/cast/installer/salt --local --retcode-passthrough -l debug --out yaml --file-root /var/cache/cast/teamdfir_sift-saltstack/v2021.12.5/source --no-color state.apply sift.server pillar={sift_user: "ljames"}]  component=installer
DEBU[0002] executing cmd.start                           component=installer
DEBU[0002] waiting for stderr read to complete           component=installer
DEBU[0002] signaling stderr read is complete             component=installer
DEBU[0002] reading from stderr is done                   component=installer
INFO[0002] log file location                             component=installer log=/var/cache/cast/installer/logs/saltstack.log
ERRO[0002] salt-call finished with errors                code=1 component=installer
WARN[0002]                                               component=installer

**Comment by ekristen** [comment]
Ok, I know why that didn't work now.

Find salt.list or saltstack.list in /etc/apt/source.list.d/ and update it to `deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main` and then run `sudo curl -fsSL -o /usr/share/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg` and then finally `apt-get update && apt-get install salt-common` 

Then see if salt-call --versions-report works

**Comment by lcsig156** [comment]
This is the salt-call --versions output

Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: 4.0.9
     gitpython: 3.1.26
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.12.0
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.10.16.3-microsoft-standard-WSL2
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by ekristen** [comment]
Ok try using cast again. The SIFT cli will try and overwrite the install, which normally is ok, but we are having some issues.

**Comment by lcsig156** [comment]
you want me to run ./cast install --mode=server sift again?

**Comment by ekristen** [comment]
Yes please

**Comment by lcsig156** [comment]
This was the end of the output from re-running the prior command...it looks like it froze up

INFO[0925] state completed                               component=installer duration=5.423 state=/usr/local/bin/parseusn.py time_begin="16:35:09.422561" time_end="16:35:09.427984"
INFO[0925] running state                                 component=installer state=/usr/local/bin time_begin="16:35:09.428140"
DEBU[0925] signaling stderr read is complete             component=installer
DEBU[0925] reading from stderr is done                   component=installer

**Comment by ekristen** [comment]
Ok. I'll look into that, but it looks like to installed everything, or most everything.

**Comment by lcsig156** [comment]
I just ran it again no errors, and seems t have installed correctly!  Is there anything other info you need via logs?  I appreciate your time and assistance very much!  Thank You again

**Comment by ekristen** [comment]
The latest version now fixes the PDF issue, you can use the same tool as well. Cheers.
