### ISSUE TITLE
[CLI] Apple M1 ARM architecture support

### ISSUE THREAD

**Issue by blackph0en1x** [teamdfir/sift#554]
I've been using SANS SIFT VM since my FOR408 class and GCFE cert. I've been working on an Intel Macbook Pro and everything worked fine. Recently I switched to a new Macbook which has a M1 Pro processor with ARM architecture. I tried to use the sift-cli path because I thought it was written in some scripting language but it appears to be an x86-64 ELF executable.
It would be nice to have an ARM version of this installer-modder to be able to continue using the SANS SIFT platform in my daily tasks.
If I can be of any help please let me know.
Thank you.

**Comment by philhagen** [comment]
At this time, the build does not support the M1, and we do not yet have an estimate on when that may be supported.  With the hundreds of tools involved, it will take a significant amount of work to ensure a build on multiple architectures works consistently and accurately.

While this is a feature we are working on, I will close this issue so folks can find it on a search for M1.  It's not a "no" but a "we're working on it and are in the early stages of feasibility".  I promise we'll make a big deal about it if/when there is news to share!

**Comment by blackph0en1x** [comment]
Thank you. Let me know if there is something I can do or if you need beta testers.
