### ISSUE TITLE
sift-cli-linux install errors

### ISSUE THREAD

**Issue by watsoninfosec** [teamdfir/sift#555]
Hello Sift Team,

I am installing this SIFT workstation on my Ubuntu Mate OS. I have did a clean install twice with a fully update OS and I am getting these error messages when I try to install this script.

I tried to do a apt autoremove, apt update and apt upgrade commands and I still got this error message at the end.
I have done what the system asked for the commands below this code block, but no dice.

`Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
`

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**Comment by digitalsleuth** [comment]
Hi there @watsoninfosec , I'm pretty sure I have a good idea what the issue is, but to make sure, can you upload a copy of your saltstack.log for review?

**Comment by watsoninfosec** [comment]
[saltstack.log](https://github.com/teamdfir/sift/files/8093936/saltstack.log)
Done!

**Comment by watsoninfosec** [comment]
So, other than that I am ok? Will I have any problems with updating tools if needed be? Or Upgrades?

**Comment by digitalsleuth** [comment]
Yes, other than that you're good to go. You shouldn't have any problems updating to future versions, however this error will pop up again for the same reason. 
If you review the saltstack.log file, you'll see a number of `[ERROR   ] Can't parse...` lines. These can be ignored, but the lines which contain `[ERROR   ]` and don't contain the `Can't parse...` will help you identify the error.

If the errors you find are related to gsettings, gnome, or dash-to-dock, then you're fine.

**Comment by watsoninfosec** [comment]
Thank you!
