### ISSUE TITLE
sift installation on AWS EC2 UBUNTU 16.04

### ISSUE THREAD

**Issue by ShahJainam24** [teamdfir/sift#558]
hello! i am trying to install sift on AWS EC2 ubuntu 16.04 and i am getting the following errors!

ubuntu@ip-172-31-19-137:~$ sudo sift install

[sift-cli@1.5.1-beta.0-master.154cb2f](mailto:sift-cli@1.5.1-beta.0-master.154cb2f)
sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
--2022-04-01 11:03:34-- https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 99.86.231.38, 99.86.231.46, 99.86.231.54, ...
Connecting to repo.saltstack.com (repo.saltstack.com)|99.86.231.38|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-01 11:03:34 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

Error: Command failed: wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
--2022-04-01 11:03:34-- https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 99.86.231.38, 99.86.231.46, 99.86.231.54, ...
Connecting to repo.saltstack.com (repo.saltstack.com)|99.86.231.38|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-01 11:03:34 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

at ChildProcess.exithandler (child_process.js:205:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:194:7)
at maybeClose (internal/child_process.js:899:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
ubuntu@ip-172-31-19-137:~$

Please help me resolve this issue

**Comment by digitalsleuth** [comment]
Good morning @ShahJainam24 While Ubuntu 16.04 is no longer supported, the error you're receiving is due to Saltstack dropping support for Salt 3001 and Ubuntu 16.04. This will require us to update the sift cli to upgrade the version. Stay tuned for a new version.

**Comment by digitalsleuth** [comment]
Hi @ShahJainam24 , have you had the opportunity to download the latest CLI and try again? Additionally, if you look [here](https://github.com/teamdfir/sift#aws) you'll find that there are AMI's available on AWS which are already setup and configured for SIFT.

**Comment by DacoDev** [comment]
I'm running into the same issue using Ubuntu 20.04, the call for the version 3001 key just doesn't exist anymore - the AMI works but I believe anyone installing SIFT manually would run into failures now. The next closest in the dir is 3002, so I guess the options are to package the needed version in this repo or test+upgrade the version used in the installation.

**Comment by ekristen** [comment]
We are working on an updated AMI but running into a few issues getting the default user to work properly. If you manually upgrade to the latest CLI things should be good to go.

**Comment by DacoDev** [comment]
Roger that - 

I ran into that issue too when launching the AMI, and I sort of worked around it with: a [tls_private_key](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key) resource, an [aws_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair), then in the user-data script echo >> the tls_private_key.name.private_key_pem into /home/sansforensics/.ssh/authorized_keys, and using that aws_key_pair created from the tls_private_key on the instance. I also added a Host * StrictHostKeyChecking no to the  .ssh/config (that I create in an earlier step), but I did both at the same time so I'm not sure exactly which of the two or both were necessary.  But probably like you're seeing it doesn't seem to work consistently, sometimes the key is present for the user at launch and it proceeds, sometimes it's not. I'll follow up if I find out anything else!

**Comment by ekristen** [comment]
16.04 is no longer supported, 18.04 is being dropped as soon as https://github.com/teamdfir/sift-saltstack/pull/80 is merged.

20.04 and 22.04 will be supported while 20.04 LTS is still supported.
