### ISSUE TITLE
VM doesn't boot

### ISSUE THREAD

**Issue by simon0117** [teamdfir/sift#560]
Using MacOS VirtualBox 6.1.32, the SIFT-Workstation.ova doesn't boot into a GUI, just a blinking cursor. I can reset to see the GRUB boot menu, but neither normal nor recovery mode boot seems to do anything. Attached is the VirtualBox log file
[vm-2022-04-20-15-27-36.log](https://github.com/teamdfir/sift/files/8525193/vm-2022-04-20-15-27-36.log)
.

**Comment by simon0117** [comment]
I've gotten further by changing General - Basic - Version from Other/Unknown to "Other/Unknown (64-bit)"
![VirtualBox_SIFT Workstation_20_04_2022_16_39_42](https://user-images.githubusercontent.com/5805263/164327446-6c36077a-0a23-466d-9961-6de666230585.png)

**Comment by simon0117** [comment]
It seems that performance events error/warning was because I checked a couple of boxes while I'm trying to troubleshoot it. Finally I changed the VM Type to Linux and Version to Ubuntu (64-bit) and it is booting up now.

**Comment by ekristen** [comment]
@simon0117 good deal, I'm glad you figured it out. We recently identified this as a general problem with the OVA file and have made a correction to fix that going forward. Any new builds **should** be set to Ubuntu (64-bit) by default. Sorry you ran into issues, but glad you got it worked out.

**Comment by mheckman101** [comment]
I just downloaded the latest OVA today (9/1/22) and this is still a problem. You have to manually change the "Guest OS Type" to "Ubuntu (64-bit)" or the VM won't boot. I suppose I should open another ticket.

**Comment by ekristen** [comment]
It may be a virtualbox issue, but we'll take a look.
