### ISSUE TITLE
Log2timeline

### ISSUE THREAD

**Issue by cipherz404** [teamdfir/sift#561]
Hi, with the recent update at Log2timeline, the functionally of the tool is not working in SIFT. I have tried updated all dependencies with no luck. In trying to read an E01, it brings back many errors relating to libewf, and other dependencies.

**Comment by digitalsleuth** [comment]
Hi @cipherz404 is there any chance you can provide some more info? Preferably the error messages you're receiving and your saltstack.log file from your most recent install. This should help us resolve your issues.

**Comment by ekristen** [comment]
@cipherz404 please feel free to re-open if you have more details, we are not aware of specific problems at this time.
