### ISSUE TITLE
sift installation issue Ubuntu 20.04 on AWS EC2

### ISSUE THREAD

**Issue by abanerjee-svmk** [teamdfir/sift#562]
AWS EC2 base image ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220419 
EC2 m5.xlarge 100GB EBS

Steps followed for SIFT installation https://github.com/teamdfir/sift-cli#installation

After execution of all the steps I receive this at the end of sudo sift install

`sudo sift install
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: desktop
Installing and configuring SaltStack properly ...
> downloading v2022.01.22
>> downloading sift-saltstack-v2022.01.22.tar.gz.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz
> validating file sift-saltstack-v2022.01.22.tar.gz
> validating signature for sift-saltstack-v2022.01.22.tar.gz.sha256
> extracting update sift-saltstack-v2022.01.22.tar.gz
> performing update v2022.01.22
>> Log file: /var/cache/sift/cli/v2022.01.22/saltstack.log

>> Running: /etc/sift-version
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)`

Ran sudo apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease                                         
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease                                       
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                                                       
Hit:5 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease                                        
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                            
Get:7 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]                     
Hit:8 http://archive.ubuntu.com/ubuntu focal InRelease                                     
Get:9 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]                   
Hit:10 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease                                                 
Hit:11 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease
Fetched 246 kB in 1s (231 kB/s)                      
Reading package lists... Done

Ran sudo apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.

If I try running sudo sift install below is what I get
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: v2022.01.22

> mode: desktop
SIFT already installed, please use the update or upgrade command

If I try running sudo sift update
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: v2022.01.22

> mode: desktop
> downloading v2022.01.22

Goes through updates and then at the end...

`>> Running: /etc/sift-version
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
`

What is the issue here? Anything in specific that can give me a clean install would be very helpful. Thanks.

**Comment by digitalsleuth** [comment]
Hi @abanerjee-svmk can you provide the saltstack.log file, it may contain some useful information to resolve the issue. As well, there is already a [SIFT AMI](https://github.com/teamdfir/sift#aws) on the AWS cloud, so you might find that useful as well.

**Comment by abanerjee-svmk** [comment]
Thank you. Will take a look at the AMI. Attaching log.
[saltstack.log](https://github.com/teamdfir/sift/files/8730659/saltstack.log)

**Comment by abanerjee-svmk** [comment]
We ended up using the SIFT AMI. Thank you.
