### ISSUE TITLE
[CLI] SIFT doesn't install on a USB device running Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by smclinden** [teamdfir/sift#563]
I get:

```
Command failed> apt-get install -o Dpkg::Options::="force-confdef" -o Dpkg::Options::="force-confold" -y --allow-change-held-packages salt-common
E: Unable to correct problems., you have held broken packages.
```

This is with the current LTS download of 20.04.

I can't build from source because there is no documentation on what config.json should look like for sift-cli."

I would really like to be able to install from source rather than rely on packages that depend upon code that appears to be in flux.

**Comment by digitalsleuth** [comment]
Hi @smclinden , to build from source, you don't need the sift-cli repo, you only need the sift-saltstack repo and saltstack. However, the error you're having as listed above is indicative of an `apt` issue, not a `SIFT` issue.

Additionally the salt states aren't packages that depend upon code in flux, they're instructions to allow SaltStack to install those packages from source.
To install SIFT using the salt states, you will require that Salt 3004.1 and git be installed, then issue the commands found [here](https://github.com/teamdfir/sift-saltstack#alternate-manual)

The CLI tool will accomplish the above, but the broken packages issue you have will prevent this. You could try running:
`sudo apt-get install -f` to see if you can rectify the broken packages issue.

**Comment by ekristen** [comment]
Closing due to age. (stale)
