### ISSUE TITLE
invalid OS, unable to determine ubuntu version - Clean ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by MonolithInd** [teamdfir/sift#564]
Hi there. I'm trying to install SIFT workstation on my new clean install of Ubuntu 20.04 but I'm getting the error "invalid OS, unable to determine ubuntu version" I have carried out an apt update and apt upgrade and apt autoremove. Still no joy. It says this should be supported. 

root@host:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
root@host:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
root@host:~# exit
logout
sift@host:~/Downloads$ ./sift-cli-linux install
> sift-cli@1.14.0-rc1+0-g0582d2b

invalid OS, unable to determine ubuntu version
Error: invalid OS, unable to determine ubuntu version
    at validOS (/snapshot/sift-cli/sift-cli.js:176:11)
    at run (/snapshot/sift-cli/sift-cli.js:688:9)
    at async main (/snapshot/sift-cli/sift-cli.js:795:5)

**Comment by digitalsleuth** [comment]
Hello @MonolithInd , currently SIFT only supports Ubuntu 20.04 (focal), but your OS is actually 22.04 (jammy). There will be support soon for Jammy, but as of yet not all of the tools included in SIFT are available on Jammy. 

I hope this helps!

**Comment by digitalsleuth** [comment]
Hi @MonolithInd , have you made any progress with this?

**Comment by gmangus117** [comment]
@digitalsleuth do you have a timeline for when jammy will be supported?

**Comment by ekristen** [comment]
22.04 is imminent, likely within the next week. It's in testing now.

Please also note, that once https://github.com/teamdfir/sift-saltstack/pull/80 is merged, SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)
