### ISSUE TITLE
[CLI] sift update command failing with "exit code not zero"

### ISSUE THREAD

**Issue by stormblessed7** [teamdfir/sift#565]
I was able to successfully install sift on a fresh Ubuntu 20.04 VM. I did a reboot and all of the "theme" settings were applied (desktop image, desktop files, terminal theme, etc.). However, when attempting to run "sift update", I get a message stating "Update returned exit code not zero". I've tried the suggested fixes such as running "apt-get update" and "apt-get autoremove". "sudo sift upgrade" doesn't fail with an error, but since I'm not able to have it check for available updates, I'm not sure if that's a good validation that everything is working. 

After digging through numerous issue posts, I see that the saltstack.log file is normally requested for further diagnostics, so I've included that as well. Any help would be appreciated!

[saltstack.log](https://github.com/teamdfir/sift/files/8821120/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @stormblessed7 , it looks like issue is one which was introduced with the most recent version of SaltStack. If you run the following command, you should then be able to try the install again without an issue:
`sudo python3 -m pip install jinja2==3.0.3`

**Comment by ekristen** [comment]
Closing due to staleness.
