### ISSUE TITLE
SIFT .ova 490GB

### ISSUE THREAD

**Issue by wilsq36** [teamdfir/sift#566]
Why is the Sift .ova VM takin up 490GB on my hard drive?

**Comment by ekristen** [comment]
Did you tell it to provision all the space ahead of time?

**Comment by wilsq36** [comment]
Just imported it into VMWare Workstation. No changes were made.

**Comment by ekristen** [comment]
As far as I know the only reason for this is if the option to pre-provision all the space ahead of time is enabled, which it's not on the OVA the last time I checked.
