### ISSUE TITLE
>> Running: /etc/sift-version Update returned exit code not zero

### ISSUE THREAD

**Issue by IreSec73** [teamdfir/sift#567]
Hi Guys

I`m installing SIFT on Ubuntu (20.04.1-Ubuntu) in AWS using an EC2 (I cant use the AMIs you provided in my company because of guard rails) and I'm having the issue below - Any idea how I solve it please - As a test I ran it on my own private AWS account to make sure it wasn't something related to the company account and had the identical issue.

Thanks

>> Running: /etc/sift-version
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'

**Comment by digitalsleuth** [comment]
Hi @IreSec73, are you able to provide the saltstack.log file which gets generates so we can review the possible issue?

**Comment by IreSec73** [comment]
[
[saltstack.log](https://github.com/teamdfir/sift/files/9112473/saltstack.log)
](url)

**Comment by tompolth** [comment]
I am having a similar issue. The upgrade seems to be ok but there is a similar message to the one especified by IreSec73.
Here it is my log file
[saltstack.log](https://github.com/teamdfir/sift/files/9438739/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @tompolth , It looks like there was an issue finding a package from the repos, which in turn caused a couple of errors. Can you provide me a listing of your /etc/apt/sources.list.d directory and possibly try the installation again?

**Comment by tompolth** [comment]
Here is the list. 
[source.list.d.txt](https://github.com/teamdfir/sift/files/9439310/source.list.d.txt)
Probably there is some entrances coming from the previous version. Yesterday I upgraded the 18.04 version to the 20.04

**Comment by tompolth** [comment]
I've just reviewed the source.list.d directory removing some old entrances and enable the related with sift that were disabled during the dist-upgrade. After that I upgraded the Ubuntu again and then the sift. Voila!! It worked flawlessly.
Thanks for your help

**Comment by IreSec73** [comment]
[saltstack (3).log](https://github.com/teamdfir/sift/files/9443896/saltstack.3.log)

Hi digitalsleuth - Attached is the log file

**Comment by digitalsleuth** [comment]
Hi @IreSec73 , it looks like there's a network connectivity issue when trying to use and configure pip during the process. I'm guessing it's a configuration issue with the AMI, as it keeps trying to search a non-existent python index:
```bash
# [ERROR   ] Command '/usr/bin/python3' failed with return code: 1
# [ERROR   ] stdout: Looking in indexes: https://repo.forge.lmig.com/api/pypi/python/simple
# [ERROR   ] stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f634af038b0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/pypi/python/simple/pip/
```

Can you confirm that you can manually install a python package within your AMI instance?

**Comment by ekristen** [comment]
Closing due to staleness.
