### ISSUE TITLE
Saltstack repo no longer available

### ISSUE THREAD

**Issue by TBesss** [teamdfir/sift#570]
Hey team, 

Tried updating SIFT this morning and Saltstack v3001 doesnt appear to be hosted anymore and is causing an issue preventing the update/upgrade of SIFT. I attempted to amend the sources.list.d file to the latest release of Saltstack however the SIFT CLI looks for v3001 specifically. https://repo.saltproject.io/py3/ubuntu/20.04/amd64/
![image](https://user-images.githubusercontent.com/111031446/184053910-089367d1-da2d-4cb1-970d-eb9bb1af03f8.png)

**Comment by digitalsleuth** [comment]
Hi @TBesss , can you tell me which version of the SIFT installer you're using?

**Comment by TBesss** [comment]
Morning @digitalsleuth, I was running V 1.10. Just upgraded to the 1.14 and all is good! Thanks ;)

**Comment by digitalsleuth** [comment]
Awesome, great to hear!
