### ISSUE TITLE
(SOLVED) VirtualBox - VM Doesn't Boot - OS Type is "unknown"

### ISSUE THREAD

**Issue by mheckman101** [teamdfir/sift#575]
I downloaded the SIFT Workstation VM ova and imported it into VirtualBox. It doesn't boot. 

I fixed the problem by manually changing the "Guest OS Type" to "Ubuntu (64-bit)" when I import it.

This is a problem that was recognized in April but was not fixed.

**Comment by ekristen** [comment]
Fairly certain the OVA has been fixed, but mileage may vary especially when it comes to virtualbox.
