### ISSUE TITLE
Update returned exit code not zero while installing sift in Remnux

### ISSUE THREAD

**Issue by varunkrs33** [teamdfir/sift#578]
Tried installing Sift Cli in Remnux VM and it is displaying error codes below

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)
[saltstack.log](https://github.com/teamdfir/sift/files/9845576/saltstack.log)

**Comment by digitalsleuth** [comment]
It looks like this is an issue with importlib_metadata. I'll look to see if I can duplicate then resolve this issue.

**Comment by varunkrs33** [comment]
Sift CLI  - 1.14 and the python version is python 2.7 so do i need to update it to Python3 -V and try installing it ?

**Comment by varunkrs33** [comment]
Hi @digitalsleuth 
Now I tried it is working thanks
Cheers!

**Comment by pshef** [comment]
I'm getting the same error while trying to install on a REMnux box (using `sudo sift install --mode=packages-only`) and if I'm reading my [saltstack.log](https://github.com/teamdfir/sift/files/9955860/saltstack.log) correctly it's also an issue with importlib-metadata, however when I run `sudo python3 -m pip install importlib-metadata<=5.0.0` I get the following response:
```
bash: =5.0.0: No such file or directory
```

I'm on an Ubuntu 20.04 vm running in VirtualBox

**Comment by digitalsleuth** [comment]
Hi @pshef , the command is actually `sudo python3 -m pip install importlib_metadata<5.0.0`

Make note of the underscore, and ensure there is no = sign either. That should fix the issue for you.

**Comment by pshef** [comment]
`sudo python3 -m pip install "importlib-metadata<5.0.0"` is what ended up working. Thank you so much!
