### ISSUE TITLE
[CLI] sift-cli installer broken due to python dependency changes

### ISSUE THREAD

**Issue by opzesty** [teamdfir/sift#579]
Not sure if this should be under CLI or the main project....however

[SIFTSaltStack.log](https://github.com/teamdfir/sift/files/9863192/SIFTSaltStack.log)

Per the above SaltStack log, SIFT version v2022.01.22 breaks when attempting to run python utilizing the `importlib-metadata` library.

The latest version of this library appears to change its previous return type (was a dict, now is a list), which breaks quite a lot of code relying on this.  I believe they are not reverting this change, and code should be updated to work with lists.  Issue is listed [here](https://github.com/python/importlib_metadata/issues/409).

**Comment by digitalsleuth** [comment]
Hi @opzesty , we are tracking this issue. Can you tell me what OS you're attempting to install on, and the current version of Python it's running?

**Comment by opzesty** [comment]
Of course!

OS: Ubuntu 20.04 Focal Fossa
Python: 3.8.10

**Comment by digitalsleuth** [comment]
Could you try running the following and see if this works:

`sudo python3 -m pip install importlib-metadata==4.13.0`

Then try running the installer.

**Comment by opzesty** [comment]
running:
`$ sudo pip install -Iv 'importlib-metadata<5.0.0'`
(which I believe does the same thing)

then running the installer works

**Comment by opzesty** [comment]
checked and running 

`sudo python3 -m pip install importlib-metadata==4.13.0`

does allow SIFT to install.

**Comment by digitalsleuth** [comment]
Hi @opzesty , you're correct, your command would work as well, I just wanted to make sure importlib-metadata was pinned to a confirmed working version, but anything under 5 is acceptable anyways.  
Glad to hear you got this working. I'll see if I can come up with a way to prevent this issue in the future, but I know the SaltStack team is also working on it.

Cheers!

**Comment by ekristen** [comment]
Please also note, that once https://github.com/teamdfir/sift-saltstack/pull/80 is merged, SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)
