### ISSUE TITLE
WSL SIFT Ubuntu 20.04

### ISSUE THREAD

**Issue by chris200712** [teamdfir/sift#583]
The first problem I faced during installations is SIFT would fail to write to the Windows 10 Desktop.

The second problem I am facing Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

Saltstack.log is attached
[saltstack.log](https://github.com/teamdfir/sift/files/10018945/saltstack.log)

**Comment by chris200712** [comment]
I am trying to install the Windows version of SIFT on WSL Ubuntu 18.04.  

Windows 10 Pro. 20H2 build 19042.2251

**Comment by digitalsleuth** [comment]
Hi @chris200712 , SIFT no longer supports 18.04, but is supporting 20.04. You should be able to successfully install SIFT in WSL using 20.04 without a problem.

**Comment by chris200712** [comment]
I tried 20.04 and it fails at the very end when trying to copy over the sans posters

**Comment by chris200712** [comment]
Yes.  Here you are.
[saltstack.log](https://github.com/teamdfir/sift/files/10032005/saltstack.log)

**Comment by chris200712** [comment]
Also getting this error when trying to update

Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

forensics@DESKTOP-TION3KE:~$ sudo sift update
[sudo] password for forensics:
> sift-cli@1.8.3
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

**Comment by chris200712** [comment]
forensics@DESKTOP-TION3KE:~$ ls -lah /usr/local/bin/sift
-rwxrwxrwx 1 root root 58M Nov 16 07:25 /usr/local/bin/sift

**Comment by chris200712** [comment]
I will upload it soon.  Thank you.

**Comment by chris200712** [comment]
This is a brand-new install of Ubuntu 20.04 

sudo sift install

**Comment by chris200712** [comment]
-rwxr-xr-x 1 forensics forensics 56M Jan 19  2022 /usr/local/bin/sift
forensics@DESKTOP-TION3KE:/var/cache/sift/cli/v2022.01.22$

**Comment by digitalsleuth** [comment]
Hi @chris200712 , for this particular install (20.04), the errors you're getting are related to the inability to setup a desktop-style environment. When installing SIFT in WSL, use the command `sudo sift install --mode server` and you should have better luck.

**Comment by chris200712** [comment]
So one cannot mimic the VM produced in the FOR508 class?

Are there any work arounds?

**Comment by ekristen** [comment]
You can't mimic using WSL2. If you use VMware you can. With WSL2 the closest you can get is installing the packages, but there is no UI.

**Comment by chris200712** [comment]
Could you provide the instructions to replicate the Windows SIFT in VMware

**Comment by ekristen** [comment]
Windows SIFT is entirely different and not supported by this project. This is the Linux SIFT.

**Comment by digitalsleuth** [comment]
Hi @chris200712, you might want to take a look at Win-FOR to create your own Windows-based VM, which would contain some of the same Windows tools as the Windows-based SIFT. I'm in the midst of organizing the desktop icon layout (using Nimi Places) or another method. Hopefully this might help, but otherwise @ekristen is right, there is no generating the GUI for the Linux SIFT in WSL.

**Comment by chris200712** [comment]
Just wondering if it is a permission related issue writing from WSL to Windows? Makes me think how was it generated for the SANS course FOR508 and even GREM. Maybe on a dedicated machine perhaps and custom configuration on the Windows environment. 

I noticed the only thing that is different between th installation of SIFT on Windows is Zimmerman tools are added to the env

**Comment by digitalsleuth** [comment]
@chris200712 Did you have an issue writing to the host machine when you tried installing SIFT in 20.04 using the `--mode=server`?

I've been re-reading everything you've posted and you've only once indicated an error while using 18.04, but didn't provide any feedback from using the `server` install mode.

I've been using the SIFT CLI in WSL2 since WSL2 came out with no major issues, and any minor ones have been resolved quickly.

Please give the `server` install a try and let us know how it went, and any details regarding specific errors you might be encountering.

**Comment by chris200712** [comment]
Thank you all.  I have successfully installed --mode=server.  I am now testing the WIN-FOR installer at this time
    On Sunday, November 20, 2022 at 02:47:44 PM GMT+1, Digital Sleuth ***@***.***> wrote:  
 
 


@chris200712 Did you have an issue writing to the host machine when you tried installing SIFT in 20.04 using the --mode=server?

I've been re-reading everything you've posted and you've only once indicated an error while using 18.04, but didn't provide any feedback from using the server install mode.

I've been using the SIFT CLI in WSL2 since WSL2 came out with no major issues, and any minor ones have been resolved quickly.

Please give the server install a try and let us know how it went, and any details regarding specific errors you might be encountering.
