### ISSUE TITLE
[CLI] Error with installing SIFT in Azure VM

### ISSUE THREAD

**Issue by imrobberting** [teamdfir/sift#586]
Hello - I've encountered an issue installing SIFT in an Azure Ubuntu 20.04 VM. 

Saltstack log as follows: [saltstack log.txt](https://github.com/teamdfir/sift/files/10344354/saltstack.log.txt)

Error code as follows.

> Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**Comment by digitalsleuth** [comment]
Hi @imrobberting, it looks like you ran out of space in your instance: `Unable to manage file: [Errno 28] No space left on device`

If possible, I'd recommend increasing the space available and trying again, or freeing up some space if the instance was already in use prior to the installation.
