### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by zaqes** [teamdfir/sift#588]
I'm having some issues with this.

Any idea how I can run sift-cli authenticated to Github?

**Comment by ekristen** [comment]
@zaqes I just looked, I thought I had built in a way, but it doesn't appear that I have, so unfortunately, there's no way to authenticate at the moment.

**Comment by ekristen** [comment]
sift-cli is being replaced with [cast](https://github.com/ekristen/cast) -- it's making it's debut with 22.04 support for SIFT.
