### ISSUE TITLE
SIFT CLI not installing on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by 0ax-christin** [teamdfir/sift#594]
`sudo sift install` on ubuntu after following the previous steps of the installation gives me a ton of errors. I was installing using sift cli rather than sift vm because for some reason it doesnt work for me (the vm boots up but doesnt let me log in with the username and password, it temporarily logs in, and everything looks weird and then logs back out, this loops)
![siftError](https://user-images.githubusercontent.com/65183619/218149943-c8b04745-cf52-48f4-ba30-ec8dcb5ec8b0.PNG)
This was the error i am getting currently. There was another error before but it no longer shows

**Comment by digitalsleuth** [comment]
Hi @christinabrahamalex , the sift-cli is being deprecated in favor of [Cast](https://github.com/ekristen/cast). Please install Cast and use the command:
`sudo cast install teamdfir/sift-saltstack`

**Comment by ekristen** [comment]
While `sift-cli` is nearing end of life, it should still work, I'll take a look and see what's up, but I would recommend moving to `cast` nonetheless.

**Comment by digitalsleuth** [comment]
Looks like it might be the 'v' missing from the release.

**Comment by ekristen** [comment]
Yup, that's what it is .. let me see why that's happening.

**Comment by digitalsleuth** [comment]
Each of the pre-releases since the last full release, and this release, are all missing the `v` when they were uploaded. Since they were all tested with cast, there wasn't an issue, but the sift-cli is looking for the `v`.

**Comment by ekristen** [comment]
cast iterates the asset downloads, sift-cli is hard coded :(

**Comment by ekristen** [comment]
@digitalsleuth maybe, I'll look into it this afternoon.

**Comment by aloibeth** [comment]
I'm also having this issue.  Does cast support installing on WSL (i.e. –mode=server)?

**Comment by digitalsleuth** [comment]
@aloibeth Yes cast does support the installation of server mode, and shouldn't have any issues within a WSL environment. Your command would simply be: `sudo cast install --mode=server teamdfir/sift-saltstack`

**Comment by transcend3nt** [comment]
i've a silly question. how do you install the cast binary? it doesn't appear to be a well-known app. the instructions is _cast install <owner/repo|alias>_ but it doesn't explain how cast should be installed

**Comment by digitalsleuth** [comment]
Hi @transcend3nt , since the cast binary is a debian package, you can download the one which matches your architecture (AMD/ARM etc). 

Once you have it downloaded you can run either:
`sudo apt-get install -y <full path to the file>` 
or 
`sudo dpkg -i <full path to the file>`

Then you can run the cast command:
`sudo cast install sift`

In this context, `sift` is an alias for the SIFT repo `teamdfir/sift-saltstack`

Let us know how this works out for you!

**Comment by ekristen** [comment]
@transcend3nt wrong issue maybe? with [cast](https://github.com/ekristen/cast) it manages saltstack for you, so did sift-cli, but with cast it uses a single binary so it doesn't actually install salt-stack on the system.

I'll work on adding some additional installation instructions.

**Comment by transcend3nt** [comment]
> Hi @transcend3nt , since the cast binary is a debian package, you can download the one which matches your architecture (AMD/ARM etc).
> 
> Once you have it downloaded you can run either: `sudo apt-get install -y <full path to the file>` or `sudo dpkg -i <full path to the file>`
> 
> Then you can run the cast command: `sudo cast install sift`
> 
> In this context, `sift` is an alias for the SIFT repo `teamdfir/sift-saltstack`
> 
> Let us know how this works out for you!

Thanks for the quick replies everyone. I'm not familiar with cast, salt and saltstack solutions and I'm trying to avoid having to invest too much time into those as I just want to get sift installed onto an ubuntu 22.04 ec2 instance on aws. Where can I find the binary to download and install manually using the package manager? Thanks a bunch

**Comment by transcend3nt** [comment]
> Hi @transcend3nt , since the cast binary is a debian package, you can download the one which matches your architecture (AMD/ARM etc).
> 
> Once you have it downloaded you can run either: `sudo apt-get install -y <full path to the file>` or `sudo dpkg -i <full path to the file>`
> 
> Then you can run the cast command: `sudo cast install sift`
> 
> In this context, `sift` is an alias for the SIFT repo `teamdfir/sift-saltstack`
> 
> Let us know how this works out for you!

Thanks both for the quick reply and your hard work, this works well. For readers out there like me who skim through documentation and might miss out on details, the deb file can be found in the 'Release' right-hand side section of [cast](https://github.com/ekristen/cast). I used dpkg to install. It works magically on Ubuntu 22.04 amd x64 on AWS EC2.

**Comment by christinabrahamalex** [comment]
> Hi @christinabrahamalex , the sift-cli is being deprecated in favor of [Cast](https://github.com/ekristen/cast). Please install Cast and use the command: `sudo cast install teamdfir/sift-saltstack`

Thanks alot you guys for the quick response and troubleshooting! I got it installed using cast shortly after posting. Works perfect

**Comment by forenzyx** [comment]
> Hi @transcend3nt , since the cast binary is a debian package, you can download the one which matches your architecture (AMD/ARM etc).
> 
> Once you have it downloaded you can run either: `sudo apt-get install -y <full path to the file>` or `sudo dpkg -i <full path to the file>`
> 
> Then you can run the cast command: `sudo cast install sift`
> 
> In this context, `sift` is an alias for the SIFT repo `teamdfir/sift-saltstack`
> 
> Let us know how this works out for you!

And where exactly do I find the debian package for CAST?

**Comment by digitalsleuth** [comment]
Hi @forenzyx , you can find the Cast binary [here](https://github.com/ekristen/cast).

**Comment by forenzyx** [comment]
> Hi @forenzyx , you can find the Cast binary [here](https://github.com/ekristen/cast).

Can you give me the EXACT syntax needed to install Cast on Ubuntu?  I am just not getting it.  Thanks.

**Comment by forenzyx** [comment]
Hi @digitalsleuth can you give me the EXACT syntax to install CAST on Ubuntu?  I am just not getting it.  Thanks

**Comment by digitalsleuth** [comment]
Hi @forenzyx , did you manage to get this working?

**Comment by Devops-sudarshan** [comment]
Hi @digitalsleuth I am installing SIFT with the help of CAST. When I start installation using command "sudo cast install teamdfir/sift-saltstack" after 70 mins of installation it gives the message that " Low Disk Space "Filesystem root" (Screenshot Attached).
And at the time of creating VM (Ubuntu 20.04) I had increased HDD space (Screenshot Attached).

![image](https://github.com/teamdfir/sift/assets/91316825/a78d8e70-beaa-433a-b1f8-9662d06b86a9)

![image](https://github.com/teamdfir/sift/assets/91316825/2f8cb401-d3e6-4771-a3a4-2287981ad787)

**Comment by Devops-sudarshan** [comment]
Hi @digitalsleuth, I checked and it is showing Disk Capacity 64.4 GB. Also attached screenshot


![image](https://github.com/teamdfir/sift/assets/91316825/c2cb3e72-615a-43dc-aa58-cfe8320a5f2c)

![image](https://github.com/teamdfir/sift/assets/91316825/df57847b-9bab-443f-9d4a-586150668ef0)

**Comment by Devops-sudarshan** [comment]
Hi @digitalsleuth

![image](https://github.com/teamdfir/sift/assets/91316825/62ae057b-7945-4ca4-a124-31dc3f8fc4a9)

**Comment by digitalsleuth** [comment]
Hi @Devops-sudarshan , you can use tools like `parted` or `gparted` to resize your partition to use all of the available free space, then try the install again. Unfortunately this isn't a SIFT or Cast issue, however once you resize your partition you should be good to go.

**Comment by Devops-sudarshan** [comment]
Hi @digitalsleuth Successfully installed SIFT with help of CAST. Thank You so much for your support...
