### ISSUE TITLE
get error when enters 'sudo sift install'

### ISSUE THREAD

**Issue by wilsonLam2002** [teamdfir/sift#596]
after I enter sudo sift install i get a error like this
![image](https://user-images.githubusercontent.com/132616101/236321105-1eb2b97d-c15e-4fdd-b857-b4444c003c66.png)

how do i solve this

**Comment by digitalsleuth** [comment]
Hi @wilsonLam2002 , can you confirm that you have internet access on that machine? If so, you can use the new [Cast](https://github.com/ekristen/cast/releases) installer which will be the replacement for the sift CLI you're currently using.

Visit the link above and download the release for your system and architecture, then install it using `sudo dpkg -i <downloaded_file>`.

Once installed, you can use the command: `sudo cast install sift`. If you want to use a different mode (ie: server), you would modify it with `sudo cast install --mode server sift`.

If you give that a shot, it should work. Let us know how that goes and we can go from there.

**Comment by wilsonLam2002** [comment]
thanks for the info, but after i enter sudo dpkg -i command it returns dpkg: error: archive 'downloaded file name' is not a regular file. did i download the wrong file?

**Comment by digitalsleuth** [comment]
No you likely didn't. When I put <downloaded_file> that's a placeholder for whatever the actual name is of the file you downloaded, since I don't know the name of the file you chose to download. Try it again with the actual file name.

**Comment by digitalsleuth** [comment]
@wilsonLam2002 The file name should end in .deb so you'll have to include that in the command:

`sudo dpkg -i cast_v0.14.0_linux_amd64.deb`

And make sure you run the command in the directory where you downloaded the file.

**Comment by wilsonLam2002** [comment]
thank you very much it worked

**Comment by wilsonLam2002** [comment]
i've just finish installing, but shouldn't it be login in to sansforensics?

**Comment by digitalsleuth** [comment]
Hi @wilsonLam2002 , the username should be your username, and it should be set up with all of the options which come with SIFT if the install completed successfully. Right now, only the VM has the default user of sansforensics.

**Comment by digitalsleuth** [comment]
Hi @wilsonLam2002 , did the last answer I provided resolve your issue / question?

**Comment by wilsonLam2002** [comment]
> Hi @wilsonLam2002 , did the last answer I provided resolve your issue / question?

Oh yes, thanks for the help

**Comment by wilsonLam2002** [comment]
I'll close this page.

**Comment by wilsonLam2002** [comment]
Hahaha
