### ISSUE TITLE
SIFT AMI not found in AWS eu-* regions

### ISSUE THREAD

**Issue by MrGuidedVengeance** [teamdfir/sift#597]
Hi,

I am not able to find the SIFT AMI for the AWS regions eu-central-1, eu-west-1, or eu-west-2, searching with the IDs listed on the Team SIFT DFIR page.

Were these removed, or is there a plan to upload them in the future?

Thanks!

**Comment by ekristen** [comment]
@MrGuidedVengeance this has been resolved. All the images should be available again.
