### ISSUE TITLE
AWS SIFT AMI not present in ap-south-1

### ISSUE THREAD

**Issue by MrGuidedVengeance** [teamdfir/sift#598]
Could the SIFT team please see about releasing this AMI into the AWS ap-south-1 (Mumbai)?  It is not currently present neither in the list of AMI IDs nor by searching the AMI name in that region.

Thanks!

**Comment by MrGuidedVengeance** [comment]
Any chance there is a timeframe for the SIFT AMI to be deployed in the ap-south-1 region?  I'll just need to make other plans if not.

**Comment by ekristen** [comment]
I will add it to my list to look at today

**Comment by ekristen** [comment]
[ami-05eb673def32aa77a](https://ap-south-1.console.aws.amazon.com/ec2/home?region=ap-south-1#ImageDetails:imageId=ami-05eb673def32aa77a)
