### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by tomhilkAWS** [teamdfir/sift#606]
Download the latest CLI installer from https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.deb to your Ubuntu workstation. 
Then you will run:
sudo dpkg -i cast_v0.14.0_linux_amd64.deb from the directory where you downloaded the release

Worked well.  Once installed the Sift release, I have no launcher.  Is the Ubuntu 20.04 install method supposed to remove the launcher?

**Comment by digitalsleuth** [comment]
Hi @tomhilkAWS , When you say you have no launcher, can you clarify what you mean? When installed using `sudo cast install --mode desktop sift`, it will install the full desktop environment, including the background, terminal, and application menu customization. Is this the "launcher" to which you're referring?

**Comment by tomhilkAWS** [comment]
Left side, “activities”.  For example, I’m not seeing “Autopsy” anywhere?  Imaging or forensic tools? ---None.

Less than 80 icons.  

But I did run “sudo cast install teamdfir/sift”.

**Comment by digitalsleuth** [comment]
Hi @tomhilkAWS , can you provide the saltstack.log file so we can confirm that everything installed correctly?

**Comment by tomhilkAWS** [comment]
Sure, It may be tomorrow, but I do think everything is installed correctly.

 

Please close the ticket.

 

Tom
