### ISSUE TITLE
CLI: SIFT CLI Transparency Log Error

### ISSUE THREAD

**Issue by ginabeana007** [teamdfir/sift#607]
All,

I am trying to install SIFT Workstation via the command line. I entered all commands without a hitch until it was time to verify signatures, and I received the following error: 

cosign verify-blob --key sift-cli.pub --signature sift-cli-linux.sig sift-cli-linux
Error: signature not found in the transparency log
main.go:74: error during command execution: signature not found in transparency log

Background:
1) I am new to both the cyber and digital forensics world. So am I willing to learn.
2) I have Googled and YouTubed any solutions to no avail prior to posting to this forum.
3) I am using Ubuntu 20.04 since, according to SIFT Workstation's website, it is compatible with this version of Ubuntu.
4) I am using VMWare as well.
5) I ensured that I downloaded cosign for Linux, Go programming language for Linux, and all SIFT latest releases files.

Any help will be greatly appreciated. And if you are local to Cincinnati, I will gladly buy you coffee.

Thank you!

**Comment by digitalsleuth** [comment]
Hi @ginabeana007 , the commands you're entering seem like they might be a little off. If you're downloading the latest version of [cast](https://github.com/ekristen/cast), then you should be entering the commands found [here](https://github.com/ekristen/cast/releases/tag/v0.14.0):
```bash
cosign verify-blob \
  --key https://github.com/ekristen/cast/releases/download/v0.14.0/cosign.pub \
  --signature https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.tar.gz.sig \
  https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.tar.gz
```
