### ISSUE TITLE
Best tool to upgrade Sift workstation

### ISSUE THREAD

**Issue by ShanHolo** [teamdfir/sift#608]
Good Afternoon 

After several months I tried to update my SIFT workstation running the tool sift-cli-linux here:

https://github.com/teamdfir/sift-cli/releases/tag/v1.14.0-rc1

I realized the project was depreciated from March 2023 and now any user wants to update sift has to run cast tool.

So are you using cast  tool for any update on sift workstation?

Thanks in advance!

**Comment by digitalsleuth** [comment]
Hi @ShanHolo , yes we're using Cast to install SIFT now. You can find instructions on the [main page](https://github.com/teamdfir/sift) of the repo for where to get Cast, and how to use it to install SIFT.

Let us know if you have any issues and we'll be happy to help!

**Comment by ShanHolo** [comment]
Hi @digitalsleuth 

Thanks again for your support in Remnux and now for Sift ;)

I just upgraded Sift running cast tool. I t works much better than the old times with sift-cli ;) 

Thanks so much!

**Comment by digitalsleuth** [comment]
Glad to hear @ShanHolo , cheers!
