### ISSUE TITLE
Error with authenticating github client

### ISSUE THREAD

**Issue by Sherlocked97** [teamdfir/sift#612]
When installing sift like this:

`sudo cast install --mode desktop teamdfir/sift-saltstack`

I get the following warning:

`﻿﻿WARN[0000] using unauthenticated github client, could result in API rate limiting`

Which then leads to the following 404 error when it gets to the point where it should download the tar file:

- INFO[0004] checksum validated                            component=distro filename=manifest.yml owner=teamdfir repo=sift-saltstack
- INFO[0004] extracting archive file                       component=distro owner=teamdfir repo=sift-saltstack version=v2023.02.06
- INFO[0004] distro downloaded successfully                command=install
- INFO[0004] installing using mode: desktop                command=install
- INFO[0004] checking if install can progress              component=installer
- INFO[0004] preparing pillar data                         component=installer
- INFO[0004] running saltstack installer                   component=installer
- INFO[0004] downloading tar.gz file                       component=saltstack-installer handler=install-binary
- FATA[0005] received error code 404 attempting to download 

Prior to that I wasn't able to verify the release like this but I´m not sure if there is any correlation :

`cosign verify-blob \
  --key https://github.com/ekristen/cast/releases/download/v0.14.0/cosign.pub \
  --signature https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.tar.gz.sig \
  https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.tar.gz`

or when even when I downloaded the keys and signature for the arm64 version.

`Error: signature not found in transparency log
main.go:74: error during command execution: signature not found in transparency log`

**Comment by digitalsleuth** [comment]
Hi @Sherlocked97 , are you able to confirm that your Ubuntu system actually has connectivity prior to the attempted install, and that you're not behind a proxy?

**Comment by Sherlocked97** [comment]
Hey @digitalsleuth,
Yeah i tried pinging other websites and downloading other packages via apt and had no problems. I don't have a proxy installed either. 

Also prior steps that include downloading files work without a problem:
`INFO[0005] downloading release file                      component=distro filename=sift-saltstack-2023.02.06.tar.gz.sha256.asc owner=teamdfir repo=sift-saltstack`

I work on a freshly installed and updated ubuntu 22.04 VM with UTM on a MacBook with M1 so maybe there could be a problem caused by that?

**Comment by ekristen** [comment]
Looks like something might have broken upstream. I'll take a look today.

**Comment by ekristen** [comment]
Something I am not logging which I realize I should be is OS Architecture. What is the architecture of the hardware? I just ran the command without issue, getting a 404 there's only a few things I can think of that can lead to that, one being architecture mismatch.

**Comment by Sherlocked97** [comment]
Architecure is ARM64. 
I used to prebuild Ubuntu VM from UTM: https://mac.getutm.app/gallery/ubuntu-20-04

**Comment by Sherlocked97** [comment]
Sad to hear, but thank you anyway for the fast repsonse and help!
