### ISSUE TITLE
No expected Hash when attempting to install 

### ISSUE THREAD

**Issue by njmbb8** [teamdfir/sift#618]
The screenshot says it all, more or less. I'm trying to install and I'm getting a hash mismatch because there is no expected hash

![image](https://github.com/teamdfir/sift/assets/11412483/97939700-4b33-48bf-a02e-eb84bc897dc4)

**Comment by digitalsleuth** [comment]
Hi @njmbb8 , the previous SIFT installer is no longer supported for installing SIFT. The current supported method is by using the [Cast installer](https://github.com/ekristen/cast). Once you download and install Cast, you can install SIFT by running:
```bash
sudo cast install sift
```

**Comment by hasamba** [comment]
i think it's better if the main page instructions will point to the newer cast installation...

**Comment by njmbb8** [comment]
> i think it's better if the main page instructions will point to the newer cast installation...

those are the instructions i was following

**Comment by digitalsleuth** [comment]
@hasamba , those instructions are found on the main page of the [SIFT Repo](https://github.com/teamdfir/sift) in the first section of the README.

**Comment by ekristen** [comment]
@hasamba the website has been updated.
