### ISSUE TITLE
CAnnot install the SIFT stack on Kali Linux

### ISSUE THREAD

**Issue by parablazer** [teamdfir/sift#619]
└─$ sudo cast install teamdfir/sift
WARN[0000] using unauthenticated github client, could result in API rate limiting 
ERRO[0000] repository has no releases                    component=distro owner=teamdfir repo=sift
FATA[0000] repository has no releases 

Running these commands  as per the instructions but getting error. 

Thank  you 

└─$ cast --version
cast version v0.14.12

**Comment by ekristen** [comment]
I recently realized people might do that. 

I need to out in a patch or a fix somehow but for now use 

teamdfir/sift-saltstack
