### ISSUE TITLE
Update PowerShell 

### ISSUE THREAD

**Issue by salty4n6** [teamdfir/sift#620]
Hi,
Is it possible to update PowerShell?  Installing 7.2.6 is a bit outdated.

~Salty

**Comment by ekristen** [comment]
Yes @salty4n6

**Comment by salty4n6** [comment]
Sorry I should have been clearer.  I meant as part of the install not after the fact.

~Salty

**Comment by ekristen** [comment]
Fixed here -- https://github.com/teamdfir/sift-saltstack/pull/94 -- will be in the next version we cut.
